import type { Metadata } from "next";
import Link from "next/link";
import { Container } from "@/components/ui/Container";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";

export const metadata: Metadata = {
  title: "Privacy Center — How AuraCheck Handles Your Data",
  description:
    "Complete transparency on how AuraCheck handles your data. Everything stays in your browser. No images uploaded, no external AI, no tracking. Learn what is and isn't collected.",
  openGraph: {
    title: "AuraCheck Privacy Center — Your Data, Your Browser",
    description:
      "Everything stays local. No images uploaded, no external AI, no tracking. Full transparency on what is and isn't collected.",
    type: "website",
  },
};

const sections = [
  {
    title: "What stays in your browser",
    content: "All data is stored locally in your browser's localStorage. This includes uploaded images, audit results, orders, analytics events, leads, referral data, challenge entries, progress comparisons, commerce click data, and user preferences. Nothing is uploaded to any external server unless you explicitly configure Supabase.",
  },
  {
    title: "What is not collected",
    content: "AuraCheck does not collect your name, email, phone number, IP address, location, device information, or browsing history unless you voluntarily provide it (e.g., in a lead form or payment request). We do not use cookies, trackers, or analytics services.",
  },
  {
    title: "What AuraCheck does not infer",
    content: "AuraCheck does not infer caste, religion, ethnicity, sexuality, health conditions, medical status, exact income, or any protected personal trait. The app analyzes visual presentation signals only — lighting, clarity, composition, background, outfit fit, and profile text coherence.",
  },
  {
    title: "How image analysis works",
    content: "Your image is processed entirely in your browser using native JavaScript and canvas APIs. Pixel data is read from the canvas to estimate lighting, clarity, contrast, saturation, and composition scores. No image data leaves your device. No external AI or cloud service is used in this MVP.",
  },
  {
    title: "Local-only manual payment",
    content: "Premium reports are unlocked via manual UPI transfer. AuraCheck does not automatically verify payments. You must contact the owner to receive an unlock code after sending payment. No payment information is stored or transmitted through any external payment gateway.",
  },
  {
    title: "How to delete your data",
    content: "You can clear specific data types or all AuraCheck data from the Data Management page. Go to Settings → Your Local Data. Select what to clear and type DELETE to confirm. All AuraCheck localStorage keys (prefixed with 'auracheck:') will be removed. Alternatively, clearing your browser's site data will remove all AuraCheck data.",
  },
  {
    title: "How to export your data",
    content: "You can download all your local data as a JSON file from the Data Management page. This includes audits, orders, analytics, leads, commerce clicks, and all other stored information.",
  },
  {
    title: "Safety and scoring limitations",
    content: "AuraCheck scores are generated by rule-based algorithms running in your browser. They are guidance, not objective truth. Scores do not measure human worth, attractiveness, or value. Archetypes describe presentation style, not identity.",
  },
  {
    title: "Data retention",
    content: "Your data persists in localStorage until you delete it or clear your browser data. Images are compressed to reduce storage impact. The app displays your current storage usage so you can manage space. No data is automatically purged by the application.",
  },
];

export default function PrivacyCenterPage() {
  const supportEmail = process.env.NEXT_PUBLIC_SUPPORT_EMAIL;

  return (
    <Container className="py-16">
      <div className="mx-auto max-w-3xl">
        <div className="mb-10 text-center">
          <h1 className="bg-gradient-to-r from-[#1c1917] via-[#E14434] to-[#c0341f] bg-clip-text text-3xl font-bold text-transparent sm:text-4xl">
            Privacy Center
          </h1>
          <p className="mt-3 text-[#6f675e]">
            How AuraCheck handles your data — completely transparent, completely local.
          </p>
        </div>

        <div className="space-y-6">
          {sections.map((s) => (
            <Card key={s.title}>
              <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">{s.title}</h2>
              <p className="text-sm leading-relaxed text-[#6f675e]">{s.content}</p>
            </Card>
          ))}
        </div>

        {/* Key statements */}
        <Card className="mt-8 border-red-500/20 bg-red-500/5">
          <h2 className="mb-4 text-lg font-semibold text-[#1C1917]">What AuraCheck states clearly</h2>
          <ul className="space-y-3 text-sm text-[#4a443d]">
            <li className="flex items-start gap-2">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-red-400" />
              No external AI is used in this MVP
            </li>
            <li className="flex items-start gap-2">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-red-400" />
              No image is uploaded to a server
            </li>
            <li className="flex items-start gap-2">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-red-400" />
              No automatic payment verification
            </li>
            <li className="flex items-start gap-2">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-red-400" />
              Scores are guidance, not objective truth
            </li>
            <li className="flex items-start gap-2">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-red-400" />
              AuraCheck analyzes presentation signals, not human worth
            </li>
            <li className="flex items-start gap-2">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-red-400" />
              It does not infer caste, religion, ethnicity, sexuality, health, exact income, or protected traits
            </li>
          </ul>
        </Card>

        {/* CTAs */}
        <div className="mt-8 flex flex-wrap justify-center gap-4">
          <Link href="/data">
            <Button variant="outline" size="lg">Manage My Local Data</Button>
          </Link>
          <Link href="/audit/new">
            <Button size="lg">Start Aura Check</Button>
          </Link>
        </div>

        {supportEmail && (
          <p className="mt-8 text-center text-xs text-[#9c9184]">
            Questions about privacy? Contact {supportEmail}
          </p>
        )}
      </div>
    </Container>
  );
}
