import Link from "next/link";
import { Container } from "@/components/ui/Container";
import { Card } from "@/components/ui/Card";

const supportEmail = typeof process !== "undefined" ? process.env.NEXT_PUBLIC_SUPPORT_EMAIL : undefined;

export default function TermsPage() {
  return (
    <Container className="py-12">
      <div className="mx-auto max-w-3xl">
        <h1 className="mb-8 text-3xl font-bold text-white">Terms of Service</h1>

        <div className="space-y-6">
          <Card>
            <h2 className="mb-3 text-lg font-semibold text-white">Purpose</h2>
            <p className="text-sm text-gray-300">
              AuraCheck is an informational and entertainment tool for self-assessment and presentation guidance. It analyzes uploaded photos using local browser-based rules to provide scores and recommendations for self-improvement purposes. AuraCheck is not a professional financial, dating, medical, or legal advisory service.
            </p>
          </Card>

          <Card>
            <h2 className="mb-3 text-lg font-semibold text-white">Use at Your Own Risk</h2>
            <p className="text-sm text-gray-300">
              AuraCheck is an MVP (Minimum Viable Product). Scores and recommendations are generated by rule-based logic running entirely in your browser. They should be treated as guidance, not objective truth. Use the app at your own discretion.
            </p>
          </Card>

          <Card>
            <h2 className="mb-3 text-lg font-semibold text-white">No Guaranteed Outcomes</h2>
            <p className="text-sm text-gray-300">
              AuraCheck makes no guarantees about the accuracy, completeness, or usefulness of any scores, recommendations, or insights provided. AuraCheck does not guarantee dating success, social outcomes, career advancement, or any other real-world results. Profile guidance is for presentation clarity, not dating guarantees. Glow-up plans are self-improvement guidance, not a guarantee of social outcomes.
            </p>
          </Card>

          <Card>
            <h2 className="mb-3 text-lg font-semibold text-white">User Responsibilities</h2>
            <ul className="list-inside list-disc space-y-1 text-sm text-gray-300">
              <li>You must own the images you upload or have permission to use them.</li>
              <li>You must not upload images of other people without their explicit consent.</li>
              <li>You must not use AuraCheck to harass, shame, bully, or publicly rank others.</li>
              <li>You must not use AuraCheck to infer or assert conclusions about protected traits (caste, religion, ethnicity, race, sexuality, gender identity, health, or any other protected characteristic).</li>
              <li>You must not use AuraCheck for any illegal purpose.</li>
              <li>You must not attempt to manipulate, exploit, or abuse the manual payment/unlock system.</li>
            </ul>
          </Card>

          <Card>
            <h2 className="mb-3 text-lg font-semibold text-white">Manual Payment / Unlock Limitations</h2>
            <p className="text-sm text-gray-300">
              The current MVP uses a manual UPI payment flow. Payments are not automatically verified. Unlock codes are manually generated and shared by the owner/admin. AuraCheck is not responsible for payment processing errors, delays, or disputes. Refunds and support are handled manually by the owner on a case-by-case basis.
            </p>
          </Card>

          <Card>
            <h2 className="mb-3 text-lg font-semibold text-white">Local Data Risk</h2>
            <p className="text-sm text-gray-300">
              All data is stored locally in your browser&apos;s localStorage. You are responsible for backing up any data you wish to keep. Clearing browser data, using private/incognito mode, or switching browsers/devices may result in permanent data loss. AuraCheck recommends exporting data from the <Link href="/data" className="text-purple-400 hover:underline">Data page</Link> before clearing browser data.
            </p>
          </Card>

          <Card>
            <h2 className="mb-3 text-lg font-semibold text-white">Limitation of Liability</h2>
            <p className="text-sm text-gray-300">
              AuraCheck and its creator are not liable for any decisions, actions, or outcomes based on the app&apos;s output. This includes but is not limited to financial decisions, relationship decisions, career decisions, or any other real-world actions. The app is provided &quot;as is&quot; without any warranty, express or implied.
            </p>
          </Card>

          <Card>
            <h2 className="mb-3 text-lg font-semibold text-white">Not Professional Advice</h2>
            <p className="text-sm text-gray-300">
              AuraCheck does not provide professional financial, dating, medical, legal, or psychological advice. Consult qualified professionals for advice in these areas.
            </p>
          </Card>

          <Card>
            <h2 className="mb-3 text-lg font-semibold text-white">Refund / Support</h2>
            <p className="text-sm text-gray-300">
              Since this is a local-only MVP, refunds and support are handled manually by the owner. If you experience issues with payment or unlock codes, contact the owner directly{supportEmail ? ` at ` : "."}
              {supportEmail && <a href={`mailto:${supportEmail}`} className="text-purple-400 hover:underline">{supportEmail}</a>}
            </p>
          </Card>

          <Card>
            <h2 className="mb-3 text-lg font-semibold text-white">Changes</h2>
            <p className="text-sm text-gray-300">
              These terms may be updated at any time. Continued use after changes constitutes acceptance of the new terms.
            </p>
          </Card>
        </div>
      </div>
    </Container>
  );
}
