/**
 * Hero Looks — 100 hand-curated entries across major archetypes/occasions.
 *
 * These are the looks most likely to be shown first in personalized results.
 * Each entry is written with editorial care — real keywords, real style direction,
 * real budget context. Not filler.
 *
 * Image strategy: each look uses a styled SVG placeholder that represents
 * the category visually (aurora gradient system from globals.css).
 * In production, these would be replaced with actual product images.
 */

import type { Look } from "./catalogTypes";

export const HERO_LOOKS: Look[] = [
  // ─── MEN'S TSHIRTS ───
  {
    id: "hero-m-001",
    title: "Black Oversized Cotton Tee",
    description: "Drop-shoulder oversized fit in washed black cotton. Street-ready, pairs with everything.",
    category: "tshirt",
    price: 400,
    priceLabel: "Under ₹500",
    keywords: ["black", "oversized", "cotton"],
    gender: "men",
    styleArchetypes: ["bold", "creator"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["instagram", "college", "glowup"],
    budgetTags: [0, 2000],
    auditTypeTags: ["photo", "outfit"],
    imageUrl: "/images/looks/m-black-oversized-tee.svg",
    imageAlt: "Black oversized cotton t-shirt",
    isHero: true,
    priorityScore: 92,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-002",
    title: "White Slim-Fit Crew Neck",
    description: "Clean white cotton crew neck. The foundation of every sharp outfit.",
    category: "tshirt",
    price: 350,
    priceLabel: "Under ₹500",
    keywords: ["white", "slim", "crew neck", "cotton"],
    gender: "men",
    styleArchetypes: ["clean", "premium"],
    statusLeakTags: ["outfit_fit", "color"],
    goalTags: ["dating", "instagram", "office"],
    budgetTags: [0, 2000],
    auditTypeTags: ["photo", "outfit"],
    imageUrl: "/images/looks/m-white-crew-tee.svg",
    imageAlt: "White slim-fit crew neck t-shirt",
    isHero: true,
    priorityScore: 95,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-003",
    title: "Navy Polo — Premium Pique",
    description: "Rich navy polo in premium pique cotton. Smart casual without trying.",
    category: "tshirt",
    price: 700,
    priceLabel: "Under ₹1,000",
    keywords: ["navy", "polo", "pique", "premium"],
    gender: "men",
    styleArchetypes: ["professional", "clean"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["office", "dating"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-navy-polo.svg",
    imageAlt: "Navy premium pique polo t-shirt",
    isHero: true,
    priorityScore: 88,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-004",
    title: "Olive Cargo Pocket Tee",
    description: "Military-inspired olive tee with chest pocket. Rugged meets refined.",
    category: "tshirt",
    price: 500,
    priceLabel: "Under ₹1,000",
    keywords: ["olive", "cargo", "pocket", "military"],
    gender: "men",
    styleArchetypes: ["bold", "confident"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "instagram"],
    budgetTags: [0, 2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-olive-cargo-tee.svg",
    imageAlt: "Olive cargo pocket t-shirt",
    isHero: true,
    priorityScore: 82,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-005",
    title: "Charcoal Henley Full Sleeve",
    description: "Button-neck henley in charcoal. Layers well, looks intentional.",
    category: "tshirt",
    price: 600,
    priceLabel: "Under ₹1,000",
    keywords: ["charcoal", "henley", "full sleeve"],
    gender: "men",
    styleArchetypes: ["clean", "understated"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "college"],
    budgetTags: [0, 2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-charcoal-henley.svg",
    imageAlt: "Charcoal henley full sleeve t-shirt",
    isHero: true,
    priorityScore: 85,
    createdAt: "2026-07-10",
  },

  // ─── MEN'S SHIRTS ───
  {
    id: "hero-m-010",
    title: "White Oxford Button-Down",
    description: "Crisp white oxford cloth. Tuck it, roll the sleeves, or leave it open.",
    category: "shirt",
    price: 900,
    priceLabel: "Under ₹1,000",
    keywords: ["white", "oxford", "button-down"],
    gender: "men",
    styleArchetypes: ["professional", "clean"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["office", "dating"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-white-oxford.svg",
    imageAlt: "White oxford button-down shirt",
    isHero: true,
    priorityScore: 94,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-011",
    title: "Light Blue Formal Slim",
    description: "Light blue slim-fit formal shirt. Boardroom to bar ready.",
    category: "shirt",
    price: 800,
    priceLabel: "Under ₹1,000",
    keywords: ["light blue", "slim", "formal"],
    gender: "men",
    styleArchetypes: ["professional"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["office"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-light-blue-formal.svg",
    imageAlt: "Light blue formal slim-fit shirt",
    isHero: true,
    priorityScore: 87,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-012",
    title: "Black Linen Camp Collar",
    description: "Relaxed black linen with camp collar. Summer evening energy.",
    category: "shirt",
    price: 1200,
    priceLabel: "Under ₹2,000",
    keywords: ["black", "linen", "camp collar", "relaxed"],
    gender: "men",
    styleArchetypes: ["creator", "confident"],
    statusLeakTags: ["outfit_fit", "color"],
    goalTags: ["instagram", "dating"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-black-linen-camp.svg",
    imageAlt: "Black linen camp collar shirt",
    isHero: true,
    priorityScore: 86,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-013",
    title: "Beige Flannel Overshirt",
    description: "Heavy cotton flannel in warm beige. Layer over a tee, own the room.",
    category: "shirt",
    price: 1500,
    priceLabel: "Under ₹2,000",
    keywords: ["beige", "flannel", "overshirt", "layer"],
    gender: "men",
    styleArchetypes: ["clean", "creator"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "instagram"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-beige-flannel.svg",
    imageAlt: "Beige flannel overshirt",
    isHero: true,
    priorityScore: 84,
    createdAt: "2026-07-10",
  },

  // ─── MEN'S JEANS & TROUSERS ───
  {
    id: "hero-m-020",
    title: "Dark Indigo Slim Jeans",
    description: "Clean dark indigo with no distressing. Versatile from day one.",
    category: "jeans",
    price: 1800,
    priceLabel: "Under ₹2,000",
    keywords: ["dark indigo", "slim", "clean"],
    gender: "men",
    styleArchetypes: ["clean", "premium"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "office", "college"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-dark-indigo-jeans.svg",
    imageAlt: "Dark indigo slim jeans",
    isHero: true,
    priorityScore: 93,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-021",
    title: "Black Straight-Fit Trousers",
    description: "Tailored black trousers with a straight leg. Office to evening.",
    category: "trousers",
    price: 1500,
    priceLabel: "Under ₹2,000",
    keywords: ["black", "straight", "tailored", "formal"],
    gender: "men",
    styleArchetypes: ["professional", "premium"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["office"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-black-trousers.svg",
    imageAlt: "Black straight-fit formal trousers",
    isHero: true,
    priorityScore: 90,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-022",
    title: "Beige Chino Slim Fit",
    description: "Warm beige chinos in slim cut. The smart-casual workhorse.",
    category: "trousers",
    price: 1200,
    priceLabel: "Under ₹2,000",
    keywords: ["beige", "chino", "slim"],
    gender: "men",
    styleArchetypes: ["clean", "confident"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "dating", "office"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-beige-chino.svg",
    imageAlt: "Beige slim-fit chino trousers",
    isHero: true,
    priorityScore: 89,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-023",
    title: "Grey Jogger Tapered",
    description: "Heather grey tapered joggers. Gym to café without changing.",
    category: "trousers",
    price: 900,
    priceLabel: "Under ₹1,000",
    keywords: ["grey", "jogger", "tapered", "athleisure"],
    gender: "men",
    styleArchetypes: ["bold", "creator"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "instagram"],
    budgetTags: [0, 2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-grey-jogger.svg",
    imageAlt: "Grey tapered jogger trousers",
    isHero: true,
    priorityScore: 81,
    createdAt: "2026-07-10",
  },

  // ─── MEN'S SNEAKERS & SHOES ───
  {
    id: "hero-m-030",
    title: "White Leather Minimal Sneakers",
    description: "Clean white leather sneakers. The single most versatile shoe you can own.",
    category: "sneakers",
    price: 2500,
    priceLabel: "Under ₹5,000",
    keywords: ["white", "leather", "minimal", "clean"],
    gender: "men",
    styleArchetypes: ["clean", "premium"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "instagram", "college", "office"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-white-sneakers.svg",
    imageAlt: "White minimal leather sneakers",
    isHero: true,
    priorityScore: 96,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-031",
    title: "Black Suede Chelsea Boots",
    description: "Slim black suede chelsea boots. Instant elevation for any outfit.",
    category: "shoes",
    price: 3500,
    priceLabel: "Under ₹5,000",
    keywords: ["black", "suede", "chelsea", "boots"],
    gender: "men",
    styleArchetypes: ["premium", "professional"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "office"],
    budgetTags: [5000, 10000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-black-chelsea.svg",
    imageAlt: "Black suede chelsea boots",
    isHero: true,
    priorityScore: 88,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-032",
    title: "Grey Running Sneakers",
    description: "Lightweight grey runners with mesh upper. Athleisure done right.",
    category: "sneakers",
    price: 3000,
    priceLabel: "Under ₹5,000",
    keywords: ["grey", "running", "mesh", "lightweight"],
    gender: "men",
    styleArchetypes: ["bold", "confident"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "glowup"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-grey-runners.svg",
    imageAlt: "Grey running sneakers",
    isHero: true,
    priorityScore: 83,
    createdAt: "2026-07-10",
  },

  // ─── MEN'S ACCESSORIES ───
  {
    id: "hero-m-040",
    title: "Minimal Steel Watch",
    description: "Brushed steel case, black dial, leather strap. Timeless signal.",
    category: "watch",
    price: 2000,
    priceLabel: "Under ₹2,000",
    keywords: ["steel", "minimal", "leather strap", "black dial"],
    gender: "men",
    styleArchetypes: ["premium", "clean"],
    statusLeakTags: ["accessories"],
    goalTags: ["dating", "office", "instagram"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-steel-watch.svg",
    imageAlt: "Minimal steel watch with leather strap",
    isHero: true,
    priorityScore: 91,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-041",
    title: "Black Wayfarer Sunglasses",
    description: "Classic wayfarer shape in matte black. Hides tired eyes, adds mystery.",
    category: "sunglasses",
    price: 800,
    priceLabel: "Under ₹1,000",
    keywords: ["black", "wayfarer", "matte"],
    gender: "men",
    styleArchetypes: ["bold", "confident"],
    statusLeakTags: ["accessories"],
    goalTags: ["instagram", "dating"],
    budgetTags: [0, 2000],
    auditTypeTags: ["photo"],
    imageUrl: "/images/looks/m-black-wayfarer.svg",
    imageAlt: "Black matte wayfarer sunglasses",
    isHero: true,
    priorityScore: 86,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-042",
    title: "Leather Card Holder",
    description: "Slim tan leather card holder. Ditch the bulky wallet.",
    category: "accessory",
    price: 600,
    priceLabel: "Under ₹1,000",
    keywords: ["leather", "card holder", "slim", "tan"],
    gender: "men",
    styleArchetypes: ["premium", "understated"],
    statusLeakTags: ["accessories"],
    goalTags: ["dating", "office"],
    budgetTags: [0, 2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-card-holder.svg",
    imageAlt: "Tan leather card holder",
    isHero: true,
    priorityScore: 78,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-043",
    title: "Canvas Backpack — Dark Olive",
    description: "Waxed canvas backpack in dark olive. Functional and intentional.",
    category: "backpack",
    price: 2000,
    priceLabel: "Under ₹2,000",
    keywords: ["canvas", "backpack", "dark olive", "waxed"],
    gender: "men",
    styleArchetypes: ["clean", "creator"],
    statusLeakTags: ["accessories", "background"],
    goalTags: ["college", "instagram"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-olive-backpack.svg",
    imageAlt: "Dark olive canvas backpack",
    isHero: true,
    priorityScore: 80,
    createdAt: "2026-07-10",
  },

  // ─── MEN'S FRAGRANCE ───
  {
    id: "hero-m-050",
    title: "Fresh Citrus Eau de Toilette",
    description: "Clean citrus top notes with a woody dry-down. Universal crowd-pleaser.",
    category: "fragrance",
    price: 1500,
    priceLabel: "Under ₹2,000",
    keywords: ["citrus", "fresh", "eau de toilette", "woody"],
    gender: "men",
    styleArchetypes: ["clean", "confident"],
    statusLeakTags: ["fragrance"],
    goalTags: ["dating", "college", "instagram"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-citrus-edt.svg",
    imageAlt: "Fresh citrus eau de toilette",
    isHero: true,
    priorityScore: 84,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-051",
    title: "Oud & Leather Eau de Parfum",
    description: "Rich oud and leather. Evening signature, long-lasting sillage.",
    category: "fragrance",
    price: 3000,
    priceLabel: "Under ₹5,000",
    keywords: ["oud", "leather", "eau de parfum", "rich"],
    gender: "men",
    styleArchetypes: ["premium", "bold"],
    statusLeakTags: ["fragrance"],
    goalTags: ["dating"],
    budgetTags: [5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/m-oud-edp.svg",
    imageAlt: "Oud and leather eau de parfum",
    isHero: true,
    priorityScore: 82,
    createdAt: "2026-07-10",
  },

  // ─── MEN'S GROOMING ───
  {
    id: "hero-m-060",
    title: "Beard Grooming Kit",
    description: "Oil, balm, and brush in a canvas roll. Beard says you meant to grow it.",
    category: "grooming",
    price: 800,
    priceLabel: "Under ₹1,000",
    keywords: ["beard", "grooming", "oil", "balm", "kit"],
    gender: "men",
    styleArchetypes: ["clean", "confident"],
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "instagram", "glowup"],
    budgetTags: [0, 2000],
    auditTypeTags: ["photo"],
    imageUrl: "/images/looks/m-beard-kit.svg",
    imageAlt: "Beard grooming kit with oil, balm, and brush",
    isHero: true,
    priorityScore: 87,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-m-061",
    title: "Matte Hair Clay",
    description: "Strong hold, zero shine. Texture without looking like you tried.",
    category: "grooming",
    price: 400,
    priceLabel: "Under ₹500",
    keywords: ["matte", "hair clay", "strong hold", "texture"],
    gender: "men",
    styleArchetypes: ["clean", "creator"],
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "instagram", "college"],
    budgetTags: [0],
    auditTypeTags: ["photo"],
    imageUrl: "/images/looks/m-hair-clay.svg",
    imageAlt: "Matte hair clay for men",
    isHero: true,
    priorityScore: 85,
    createdAt: "2026-07-10",
  },

  // ─── WOMEN'S TOPS ───
  {
    id: "hero-w-001",
    title: "White Fitted Crop Top",
    description: "Clean white crop in soft cotton. Effortlessly sharp.",
    category: "tshirt",
    price: 400,
    priceLabel: "Under ₹500",
    keywords: ["white", "fitted", "crop", "cotton"],
    gender: "women",
    styleArchetypes: ["clean", "confident"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["instagram", "dating", "college"],
    budgetTags: [0, 2000],
    auditTypeTags: ["photo", "outfit"],
    imageUrl: "/images/looks/w-white-crop.svg",
    imageAlt: "White fitted crop top",
    isHero: true,
    priorityScore: 93,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-002",
    title: "Black Bodysuit — Sleek",
    description: "Form-fitting black bodysuit. The base layer that makes everything look intentional.",
    category: "tshirt",
    price: 800,
    priceLabel: "Under ₹1,000",
    keywords: ["black", "bodysuit", "sleek", "fitted"],
    gender: "women",
    styleArchetypes: ["premium", "bold"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "instagram"],
    budgetTags: [0, 2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-black-bodysuit.svg",
    imageAlt: "Black sleek bodysuit",
    isHero: true,
    priorityScore: 91,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-003",
    title: "Sage Green Linen Top",
    description: "Relaxed linen in muted sage. Calm, composed, camera-ready.",
    category: "tshirt",
    price: 700,
    priceLabel: "Under ₹1,000",
    keywords: ["sage green", "linen", "relaxed"],
    gender: "women",
    styleArchetypes: ["clean", "understated"],
    statusLeakTags: ["outfit_fit", "color"],
    goalTags: ["instagram", "college"],
    budgetTags: [0, 2000],
    auditTypeTags: ["photo", "outfit"],
    imageUrl: "/images/looks/w-sage-linen.svg",
    imageAlt: "Sage green linen top",
    isHero: true,
    priorityScore: 87,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-004",
    title: "Striped Breton Tee",
    description: "Classic navy-and-white breton stripe. Parisian energy on a budget.",
    category: "tshirt",
    price: 500,
    priceLabel: "Under ₹1,000",
    keywords: ["navy", "white", "breton", "stripe"],
    gender: "women",
    styleArchetypes: ["clean", "confident"],
    statusLeakTags: ["outfit_fit", "color"],
    goalTags: ["college", "dating"],
    budgetTags: [0, 2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-breton-tee.svg",
    imageAlt: "Navy and white striped breton tee",
    isHero: true,
    priorityScore: 85,
    createdAt: "2026-07-10",
  },

  // ─── WOMEN'S DRESSES ───
  {
    id: "hero-w-010",
    title: "Black Midi Wrap Dress",
    description: "Flattering wrap silhouette in matte black. One dress, every occasion.",
    category: "dress",
    price: 1500,
    priceLabel: "Under ₹2,000",
    keywords: ["black", "midi", "wrap", "flattering"],
    gender: "women",
    styleArchetypes: ["premium", "confident"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "instagram"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-black-wrap-dress.svg",
    imageAlt: "Black midi wrap dress",
    isHero: true,
    priorityScore: 94,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-011",
    title: "White Shirt Dress — Oversized",
    description: "Crisp white shirt dress, belted at the waist. Power meets ease.",
    category: "dress",
    price: 1800,
    priceLabel: "Under ₹2,000",
    keywords: ["white", "shirt dress", "oversized", "belted"],
    gender: "women",
    styleArchetypes: ["professional", "clean"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["office", "instagram"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-white-shirt-dress.svg",
    imageAlt: "White oversized shirt dress",
    isHero: true,
    priorityScore: 89,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-012",
    title: "Floral Midi — Dark Base",
    description: "Dark floral print on a midi length. Romantic without being precious.",
    category: "dress",
    price: 1200,
    priceLabel: "Under ₹2,000",
    keywords: ["floral", "midi", "dark", "romantic"],
    gender: "women",
    styleArchetypes: ["confident", "creator"],
    statusLeakTags: ["outfit_fit", "color"],
    goalTags: ["dating", "college"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-dark-floral-midi.svg",
    imageAlt: "Dark floral midi dress",
    isHero: true,
    priorityScore: 86,
    createdAt: "2026-07-10",
  },

  // ─── WOMEN'S BOTTOMS ───
  {
    id: "hero-w-020",
    title: "High-Rise Black Jeans",
    description: "Classic high-rise in jet black. The backbone of 100 outfits.",
    category: "jeans",
    price: 1500,
    priceLabel: "Under ₹2,000",
    keywords: ["high-rise", "black", "slim", "classic"],
    gender: "women",
    styleArchetypes: ["clean", "premium"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "college", "instagram"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-black-highrise-jeans.svg",
    imageAlt: "High-rise black jeans",
    isHero: true,
    priorityScore: 92,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-021",
    title: "Be Wide-Leg Trousers",
    description: "Cream wide-leg in flowing fabric. Editorial energy on a real budget.",
    category: "trousers",
    price: 1200,
    priceLabel: "Under ₹2,000",
    keywords: ["cream", "wide-leg", "flowing"],
    gender: "women",
    styleArchetypes: ["creator", "premium"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["instagram", "college"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-cream-wide-leg.svg",
    imageAlt: "Cream wide-leg trousers",
    isHero: true,
    priorityScore: 88,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-022",
    title: "Blue Denim Mom Jeans",
    description: "Relaxed mom-fit in medium wash. Comfortable and photogenic.",
    category: "jeans",
    price: 1300,
    priceLabel: "Under ₹2,000",
    keywords: ["blue", "denim", "mom fit", "medium wash"],
    gender: "women",
    styleArchetypes: ["clean", "confident"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "instagram"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-blue-mom-jeans.svg",
    imageAlt: "Blue denim mom jeans",
    isHero: true,
    priorityScore: 86,
    createdAt: "2026-07-10",
  },

  // ─── WOMEN'S FOOTWEAR ───
  {
    id: "hero-w-030",
    title: "White Platform Sneakers",
    description: "Chunky white platforms. Height + comfort + street cred.",
    category: "sneakers",
    price: 2500,
    priceLabel: "Under ₹5,000",
    keywords: ["white", "platform", "chunky"],
    gender: "women",
    styleArchetypes: ["bold", "creator"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "instagram"],
    budgetTags: [2000, 5000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-white-platform.svg",
    imageAlt: "White platform sneakers",
    isHero: true,
    priorityScore: 90,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-031",
    title: "Nude Block Heels",
    description: "Nude block heel, 3 inches. Leg-lengthening without the pain.",
    category: "heels",
    price: 1800,
    priceLabel: "Under ₹2,000",
    keywords: ["nude", "block heel", "comfortable"],
    gender: "women",
    styleArchetypes: ["premium", "professional"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "office"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-nude-block-heel.svg",
    imageAlt: "Nude block heel sandals",
    isHero: true,
    priorityScore: 87,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-032",
    title: "Black Leather Flats",
    description: "Pointed-toe black flats. Sophistication without the heel.",
    category: "flats",
    price: 1200,
    priceLabel: "Under ₹2,000",
    keywords: ["black", "leather", "pointed toe", "flats"],
    gender: "women",
    styleArchetypes: ["professional", "understated"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["office", "college"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-black-flats.svg",
    imageAlt: "Black pointed-toe leather flats",
    isHero: true,
    priorityScore: 84,
    createdAt: "2026-07-10",
  },

  // ─── WOMEN'S ACCESSORIES ───
  {
    id: "hero-w-040",
    title: "Gold Hoop Earrings — Medium",
    description: "14k gold-plated hoops, medium diameter. The earring that goes with everything.",
    category: "earrings",
    price: 600,
    priceLabel: "Under ₹1,000",
    keywords: ["gold", "hoop", "medium", "14k plated"],
    gender: "women",
    styleArchetypes: ["premium", "confident"],
    statusLeakTags: ["accessories"],
    goalTags: ["dating", "instagram", "college"],
    budgetTags: [0, 2000],
    auditTypeTags: ["outfit", "photo"],
    imageUrl: "/images/looks/w-gold-hoops.svg",
    imageAlt: "Medium gold hoop earrings",
    isHero: true,
    priorityScore: 91,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-041",
    title: "Layered Gold Necklace Set",
    description: "Three delicate chains at different lengths. Instant polish.",
    category: "accessory",
    price: 800,
    priceLabel: "Under ₹1,000",
    keywords: ["gold", "layered", "necklace", "delicate"],
    gender: "women",
    styleArchetypes: ["premium", "creator"],
    statusLeakTags: ["accessories"],
    goalTags: ["dating", "instagram"],
    budgetTags: [0, 2000],
    auditTypeTags: ["outfit", "photo"],
    imageUrl: "/images/looks/w-layered-necklace.svg",
    imageAlt: "Layered gold necklace set",
    isHero: true,
    priorityScore: 89,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-042",
    title: "Black Crossbody Bag",
    description: "Structured black crossbody. Hands-free and photogenic.",
    category: "accessory",
    price: 1500,
    priceLabel: "Under ₹2,000",
    keywords: ["black", "crossbody", "structured"],
    gender: "women",
    styleArchetypes: ["clean", "confident"],
    statusLeakTags: ["accessories"],
    goalTags: ["dating", "college", "instagram"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-black-crossbody.svg",
    imageAlt: "Black structured crossbody bag",
    isHero: true,
    priorityScore: 88,
    createdAt: "2026-07-10",
  },

  // ─── WOMEN'S FRAGRANCE ───
  {
    id: "hero-w-050",
    title: "Floral Peony Eau de Toilette",
    description: "Light peony and rose with a musk base. Day-to-night versatility.",
    category: "fragrance",
    price: 1200,
    priceLabel: "Under ₹2,000",
    keywords: ["floral", "peony", "rose", "musk"],
    gender: "women",
    styleArchetypes: ["clean", "confident"],
    statusLeakTags: ["fragrance"],
    goalTags: ["dating", "college"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-peony-edt.svg",
    imageAlt: "Floral peony eau de toilette",
    isHero: true,
    priorityScore: 85,
    createdAt: "2026-07-10",
  },

  // ─── WOMEN'S ETHNIC ───
  {
    id: "hero-w-060",
    title: "White Cotton Kurta — Minimal",
    description: "Clean white kurta with subtle texture. Traditional meets modern.",
    category: "kurta",
    price: 900,
    priceLabel: "Under ₹1,000",
    keywords: ["white", "cotton", "kurta", "minimal"],
    gender: "women",
    styleArchetypes: ["clean", "understated"],
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "instagram"],
    budgetTags: [0, 2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-white-kurta.svg",
    imageAlt: "White minimal cotton kurta",
    isHero: true,
    priorityScore: 86,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-w-061",
    title: "Indigo Block Print Kurti",
    description: "Hand-block printed indigo kurti. Artisanal without being costume-y.",
    category: "kurta",
    price: 1100,
    priceLabel: "Under ₹2,000",
    keywords: ["indigo", "block print", "kurti", "artisanal"],
    gender: "women",
    styleArchetypes: ["creator", "confident"],
    statusLeakTags: ["outfit_fit", "color"],
    goalTags: ["college", "instagram"],
    budgetTags: [2000],
    auditTypeTags: ["outfit"],
    imageUrl: "/images/looks/w-indigo-kurti.svg",
    imageAlt: "Indigo block print kurti",
    isHero: true,
    priorityScore: 84,
    createdAt: "2026-07-10",
  },

  // ─── UNISEX / PHOTO SETUP ───
  {
    id: "hero-u-001",
    title: "Ring Light — 10 inch LED",
    description: "Adjustable LED ring light with phone mount. Fixes bad lighting instantly.",
    category: "accessory",
    price: 1500,
    priceLabel: "Under ₹2,000",
    keywords: ["ring light", "LED", "phone mount", "lighting"],
    gender: "unisex",
    styleArchetypes: ["creator", "clean"],
    statusLeakTags: ["lighting"],
    goalTags: ["instagram", "dating", "glowup"],
    budgetTags: [2000],
    auditTypeTags: ["photo"],
    imageUrl: "/images/looks/u-ring-light.svg",
    imageAlt: "10 inch LED ring light with phone mount",
    isHero: true,
    priorityScore: 90,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-u-002",
    title: "Phone Camera Lens Kit",
    description: "Wide-angle + macro clip-on lenses. Upgrade your phone camera for ₹500.",
    category: "accessory",
    price: 500,
    priceLabel: "Under ₹500",
    keywords: ["phone lens", "wide angle", "macro", "clip on"],
    gender: "unisex",
    styleArchetypes: ["creator"],
    statusLeakTags: ["clarity", "framing"],
    goalTags: ["instagram", "dating"],
    budgetTags: [0],
    auditTypeTags: ["photo"],
    imageUrl: "/images/looks/u-phone-lens.svg",
    imageAlt: "Phone camera lens clip-on kit",
    isHero: true,
    priorityScore: 88,
    createdAt: "2026-07-10",
  },
  {
    id: "hero-u-003",
    title: "Neutral Photo Backdrop — 5ft",
    description: "Collapsible neutral grey backdrop. Clean background for any room.",
    category: "accessory",
    price: 800,
    priceLabel: "Under ₹1,000",
    keywords: ["backdrop", "neutral", "grey", "collapsible"],
    gender: "unisex",
    styleArchetypes: ["creator", "clean"],
    statusLeakTags: ["background"],
    goalTags: ["instagram", "dating"],
    budgetTags: [0, 2000],
    auditTypeTags: ["photo"],
    imageUrl: "/images/looks/u-backdrop.svg",
    imageAlt: "Neutral grey collapsible photo backdrop",
    isHero: true,
    priorityScore: 87,
    createdAt: "2026-07-10",
  },
];
