import type { Product } from "@/types/product";

export const PRODUCTS: Product[] = [
  {
    id: "clean-white-sneakers",
    title: "Clean White Sneakers",
    category: "shoes",
    price: 1800,
    priceLabel: "₹1,800",
    description: "Minimal white sneakers that go with almost any outfit.",
    whyItWorks: "Clean, neutral footwear signals attention to detail without needing an expensive brand.",
    visualSignalImproved: "Footwear presentation — first thing people notice in full-body frames",
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "college", "glowup"],
    auditTypeTags: ["outfit"],
    budgetTags: [2000, 5000],
    priorityScore: 75,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "black-overshirt",
    title: "Black Overshirt / Shacket",
    category: "outfit",
    price: 2200,
    priceLabel: "₹2,200",
    description: "A versatile black overshirt that layers well over tees and shirts.",
    whyItWorks: "Layering instantly makes any outfit look more intentional and put-together.",
    visualSignalImproved: "Outfit depth — layered looks signal style awareness",
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "office", "glowup"],
    auditTypeTags: ["outfit", "photo"],
    budgetTags: [5000, 10000],
    priorityScore: 80,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "solid-tee-pack",
    title: "Pack of Solid-Color Tees (3-Pack)",
    category: "outfit",
    price: 1200,
    priceLabel: "₹1,200",
    description: "Three high-quality solid tees in neutral tones — black, white, grey.",
    whyItWorks: "Solid colors create a cleaner visual signal than logos or busy patterns in photos.",
    visualSignalImproved: "Top-half presentation — the most visible part of any frame",
    statusLeakTags: ["outfit_fit", "background"],
    goalTags: ["dating", "college", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating"],
    budgetTags: [2000],
    priorityScore: 90,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "basic-metal-watch",
    title: "Minimal Metal Watch",
    category: "accessory",
    price: 1500,
    priceLabel: "₹1,500",
    description: "A clean, minimal watch with a silver or black metal strap.",
    whyItWorks: "A single visible accessory signals intentionality without being loud.",
    visualSignalImproved: "Wrist signal — subtle but noticed in profile photos",
    statusLeakTags: ["accessories"],
    goalTags: ["dating", "office", "glowup"],
    auditTypeTags: ["photo", "outfit"],
    budgetTags: [2000, 5000],
    priorityScore: 65,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "minimal-black-belt",
    title: "Minimal Black Belt",
    category: "accessory",
    price: 600,
    priceLabel: "₹600",
    description: "Simple black belt with a minimal buckle.",
    whyItWorks: "A belt that matches your shoes is a small detail that signals visual coherence.",
    visualSignalImproved: "Outfit cohesion — small details signal higher standards",
    statusLeakTags: ["outfit_fit", "accessories"],
    goalTags: ["dating", "office", "college"],
    auditTypeTags: ["outfit"],
    budgetTags: [2000],
    priorityScore: 50,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "clean-phone-case",
    title: "Clean Minimal Phone Case",
    category: "phone_accessory",
    price: 400,
    priceLabel: "₹400",
    description: "A solid-color, non-yellowing phone case without logos or graphics.",
    whyItWorks: "Your phone case appears in photos and video calls — a clean case signals care.",
    visualSignalImproved: "Phone presentation — reduces visual noise in hand-held frames",
    statusLeakTags: ["phone_condition"],
    goalTags: ["dating", "college", "glowup"],
    auditTypeTags: ["photo", "room"],
    budgetTags: [2000],
    priorityScore: 45,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "lens-cleaning-cloth",
    title: "Lens Cleaning Cloth (3-Pack)",
    category: "photo_setup",
    price: 150,
    priceLabel: "₹150",
    description: "Microfiber cloths for cleaning phone and camera lenses.",
    whyItWorks: "A dirty lens is the #1 cause of soft/blurry photos. Cleaning it costs near nothing.",
    visualSignalImproved: "Image clarity — removes the haze that makes photos look low-effort",
    statusLeakTags: ["clarity", "resolution"],
    goalTags: ["dating", "instagram", "college", "office", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating"],
    budgetTags: [0, 2000],
    priorityScore: 95,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "basic-phone-tripod",
    title: "Basic Phone Tripod",
    category: "photo_setup",
    price: 800,
    priceLabel: "₹800",
    description: "A small adjustable tripod for steady phone shots and video calls.",
    whyItWorks: "A steady frame immediately looks more intentional and premium than a handheld shot.",
    visualSignalImproved: "Frame stability — eliminates shaky/blurry frames",
    statusLeakTags: ["clarity", "framing"],
    goalTags: ["dating", "instagram", "college", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating", "outfit", "room"],
    budgetTags: [2000],
    priorityScore: 88,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "clip-on-ring-light",
    title: "Clip-On Ring Light",
    category: "photo_setup",
    price: 600,
    priceLabel: "₹600",
    description: "A small LED ring light that clips onto your phone for even lighting.",
    whyItWorks: "Good lighting is the single highest-impact upgrade for photo quality under ₹1,000.",
    visualSignalImproved: "Lighting quality — even lighting makes any subject look better",
    statusLeakTags: ["lighting"],
    goalTags: ["dating", "instagram", "college", "office", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating", "outfit", "room"],
    budgetTags: [2000],
    priorityScore: 96,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "room-led-lamp",
    title: "Warm LED Desk Lamp",
    category: "room",
    price: 900,
    priceLabel: "₹900",
    description: "A warm-tone LED lamp that softens room lighting for photos and video calls.",
    whyItWorks: "Harsh overhead light is a top status leak. A warm directional lamp fixes it cheaply.",
    visualSignalImproved: "Room lighting — soft directional light creates premium-looking frames",
    statusLeakTags: ["lighting", "room_clutter"],
    goalTags: ["dating", "college", "office", "glowup"],
    auditTypeTags: ["photo", "room"],
    budgetTags: [2000],
    priorityScore: 92,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "neutral-bedsheet-backdrop",
    title: "Neutral Bedsheet / Backdrop Cloth",
    category: "room",
    price: 500,
    priceLabel: "₹500",
    description: "A large solid-color bedsheet in white, grey, or beige to use as photo background.",
    whyItWorks: "A clean background removes the biggest visual distraction in most casual photos.",
    visualSignalImproved: "Background cleanliness — instantly frames the subject better",
    statusLeakTags: ["background", "room_clutter"],
    goalTags: ["dating", "instagram", "college", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating", "room"],
    budgetTags: [2000],
    priorityScore: 90,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "basic-grooming-kit",
    title: "Basic Grooming Kit",
    category: "grooming",
    price: 700,
    priceLabel: "₹700",
    description: "Nail clipper, eyebrow trimmer, tweezers, and a comb in one kit.",
    whyItWorks: "Grooming details like nails and brows are noticed in close-up frames and dating profiles.",
    visualSignalImproved: "Personal grooming signal — small details that say 'I take care of myself'",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "college", "office", "glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: [2000],
    priorityScore: 82,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "hair-clay-wax",
    title: "Hair Styling Clay / Wax",
    category: "grooming",
    price: 350,
    priceLabel: "₹350",
    description: "A matte-finish hair clay for a clean, natural look.",
    whyItWorks: "Well-styled hair in photos signals intentionality and awareness.",
    visualSignalImproved: "Hair presentation — a polished look without being overdone",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "college", "office", "glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: [2000],
    priorityScore: 70,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "mild-perfume",
    title: "Mild Perfume / Deodorant",
    category: "fragrance",
    price: 900,
    priceLabel: "₹900",
    description: "A fresh, mild fragrance suitable for daily wear and dates.",
    whyItWorks: "Scent is not visible in photos, but consistent grooming habits create overall confidence.",
    visualSignalImproved: "Overall grooming habit — signals that you pay attention to details",
    statusLeakTags: ["grooming", "fragrance"],
    goalTags: ["dating", "office", "glowup"],
    auditTypeTags: ["dating", "outfit"],
    budgetTags: [2000, 5000],
    priorityScore: 60,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "simple-backpack",
    title: "Simple Solid-Color Backpack",
    category: "bag",
    price: 1100,
    priceLabel: "₹1,100",
    description: "A clean, unbranded backpack in black or grey.",
    whyItWorks: "Your bag appears in full-body frames and daily context photos — a clean bag signals order.",
    visualSignalImproved: "Carry signal — a minimal bag looks more premium than branded alternatives",
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "office", "glowup"],
    auditTypeTags: ["outfit"],
    budgetTags: [2000, 5000],
    priorityScore: 55,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "sunglasses",
    title: "Minimal Sunglasses",
    category: "accessory",
    price: 800,
    priceLabel: "₹800",
    description: "Clean-frame sunglasses with no large logos.",
    whyItWorks: "Sunglasses in outdoor photos add a lifestyle signal without looking try-hard.",
    visualSignalImproved: "Lifestyle context — suggests an active outdoor element",
    statusLeakTags: ["accessories"],
    goalTags: ["dating", "instagram", "college"],
    auditTypeTags: ["photo", "outfit"],
    budgetTags: [2000],
    priorityScore: 55,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "collar-shirt",
    title: "Well-Fitted Collar Shirt",
    category: "outfit",
    price: 1400,
    priceLabel: "₹1,400",
    description: "A solid-color collar shirt that fits well at shoulders and chest.",
    whyItWorks: "A good-fitting collar shirt works for dating, office, and social profiles equally well.",
    visualSignalImproved: "Upper body silhouette — correct fit signals body awareness",
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "office", "college"],
    auditTypeTags: ["photo", "outfit"],
    budgetTags: [2000, 5000],
    priorityScore: 78,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "slim-wallet",
    title: "Slim Minimal Wallet",
    category: "accessory",
    price: 500,
    priceLabel: "₹500",
    description: "A slim cardholder or wallet that does not bulge in pockets.",
    whyItWorks: "A bulging pocket in photos is a subtle but real status leak that is easy to fix.",
    visualSignalImproved: "Silhouette cleanliness — no visible pocket bulge in photos",
    statusLeakTags: ["outfit_fit", "accessories"],
    goalTags: ["dating", "office", "college"],
    auditTypeTags: ["outfit"],
    budgetTags: [2000],
    priorityScore: 40,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "steamer-iron",
    title: "Clothes Steamer / Iron (Placeholder)",
    category: "room",
    price: 1500,
    priceLabel: "₹1,500",
    description: "A basic garment steamer or iron to keep clothes wrinkle-free.",
    whyItWorks: "Wrinkle-free clothes in photos signal effort and attention instantly.",
    visualSignalImproved: "Outfit freshness — wrinkled clothes weaken even expensive outfits",
    statusLeakTags: ["outfit_fit", "room_clutter"],
    goalTags: ["dating", "office", "college", "glowup"],
    auditTypeTags: ["outfit"],
    budgetTags: [2000, 5000],
    priorityScore: 72,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "budget-sneakers",
    title: "Budget Casual Sneakers (Under ₹1,000)",
    category: "shoes",
    price: 800,
    priceLabel: "₹800",
    description: "Simple, clean sneakers under ₹1,000 that look decent in photos.",
    whyItWorks: "Even at low budget, clean shoes signal better than expensive dirty shoes.",
    visualSignalImproved: "Footwear baseline — clean shoes always beat dirty premium shoes",
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "glowup"],
    auditTypeTags: ["outfit"],
    budgetTags: [2000],
    priorityScore: 65,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "barber-service",
    title: "Local Barber / Salon Visit (Placeholder)",
    category: "service",
    price: 300,
    priceLabel: "₹300+",
    description: "A professional haircut and basic grooming session near your area.",
    whyItWorks: "A fresh haircut is the most visible signal upgrade for under ₹500.",
    visualSignalImproved: "Overall grooming — a good haircut improves every type of photo",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "college", "office", "glowup"],
    auditTypeTags: ["photo", "dating", "outfit"],
    budgetTags: [2000, 5000],
    priorityScore: 88,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "profile-photoshoot",
    title: "Local Profile Photo Session (Placeholder)",
    category: "service",
    price: 2500,
    priceLabel: "₹2,500+",
    description: "Find a local photographer or friend for a mini profile photo session.",
    whyItWorks: "A dedicated photo session produces 10x better profile photos than casual selfies.",
    visualSignalImproved: "Overall photo quality — professional framing, lighting, and direction",
    statusLeakTags: ["lighting", "clarity", "framing", "background"],
    goalTags: ["dating", "instagram", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating"],
    budgetTags: [5000, 10000, 25000],
    priorityScore: 85,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "room-storage-box",
    title: "Room Storage / Organizer Box",
    category: "room",
    price: 400,
    priceLabel: "₹400",
    description: "A simple storage box to reduce visible clutter in room photos.",
    whyItWorks: "Decluttering the visible area costs almost nothing but dramatically improves background signals.",
    visualSignalImproved: "Background cleanliness — clutter is one of the most common status leaks",
    statusLeakTags: ["background", "room_clutter"],
    goalTags: ["dating", "college", "glowup"],
    auditTypeTags: ["photo", "room"],
    budgetTags: [2000],
    priorityScore: 78,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "fitness-plan",
    title: "Fitness / Grooming Program (3-Month)",
    category: "service",
    price: 6000,
    priceLabel: "₹6,000",
    description: "A 3-month commitment to basic fitness or grooming improvement.",
    whyItWorks: "Long-term physical presentation improvement compounds across every photo and interaction.",
    visualSignalImproved: "Overall physical presentation — the highest-ROI long-term upgrade",
    statusLeakTags: ["grooming"],
    goalTags: ["glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: [10000, 25000],
    priorityScore: 80,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "neutral-hoodie",
    title: "Solid-Color Hoodie",
    category: "outfit",
    price: 1100,
    priceLabel: "₹1,100",
    description: "A plain hoodie without graphics in grey, black, or navy.",
    whyItWorks: "A clean hoodie works for casual contexts and signals relaxed intentionality.",
    visualSignalImproved: "Casual outfit baseline — clean basics beat branded casuals",
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "glowup"],
    auditTypeTags: ["outfit", "photo"],
    budgetTags: [2000, 5000],
    priorityScore: 68,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "leather-loafers",
    title: "Minimal Leather Loafers",
    category: "shoes",
    price: 3500,
    priceLabel: "₹3,500",
    description: "Simple leather loafers for dressier contexts and date outfits.",
    whyItWorks: "Footwear that matches the outfit formality is a high-trust signal.",
    visualSignalImproved: "Outfit coherence — shoes matched to outfit level signals attention",
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "office"],
    auditTypeTags: ["outfit"],
    budgetTags: [5000, 10000],
    priorityScore: 72,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "canvas-shoes",
    title: "Canvas Casual Shoes",
    category: "shoes",
    price: 1000,
    priceLabel: "₹1,000",
    description: "Lightweight canvas shoes in white or black for daily wear.",
    whyItWorks: "Clean canvas shoes look intentional and youthful without being expensive.",
    visualSignalImproved: "Footwear freshness — clean casual shoes suit college and dating profiles",
    statusLeakTags: ["outfit_fit"],
    goalTags: ["college", "dating", "glowup"],
    auditTypeTags: ["outfit"],
    budgetTags: [2000],
    priorityScore: 65,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "wireless-earbuds",
    title: "Minimal Wireless Earbuds",
    category: "phone_accessory",
    price: 1200,
    priceLabel: "₹1,200",
    description: "Simple wireless earbuds without aggressive branding.",
    whyItWorks: "Tangled wires or cheap-looking earphones in photos can weaken the frame.",
    visualSignalImproved: "Tech accessories presentation — clean wireless look feels more premium",
    statusLeakTags: ["phone_condition", "accessories"],
    goalTags: ["college", "glowup"],
    auditTypeTags: ["photo"],
    budgetTags: [2000, 5000],
    priorityScore: 50,
    affiliateUrl: "#",
    isSponsored: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "facial-cleanser",
    title: "Basic Facial Cleanser / Skincare",
    category: "grooming",
    price: 300,
    priceLabel: "₹300",
    description: "A basic gentle facial cleanser for daily use.",
    whyItWorks: "Clear skin in close-up photos signals health and grooming without saying a word.",
    visualSignalImproved: "Skin presentation in close-up frames and profile photos",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: [2000],
    priorityScore: 72,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "denim-jacket",
    title: "Classic Denim Jacket",
    category: "outfit",
    price: 2000,
    priceLabel: "₹2,000",
    description: "A well-fitted denim jacket in a medium wash.",
    whyItWorks: "A denim jacket is one of the most universally flattering layering pieces for photos.",
    visualSignalImproved: "Outfit depth — layering adds visual interest to any frame",
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "college", "glowup"],
    auditTypeTags: ["outfit", "photo"],
    budgetTags: [5000],
    priorityScore: 74,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "white-shirt",
    title: "Crisp White Shirt",
    category: "outfit",
    price: 1000,
    priceLabel: "₹1,000",
    description: "A well-fitted crisp white shirt — the most versatile piece in any wardrobe.",
    whyItWorks: "A white shirt works for every goal — dating, office, college, glowup. Highest versatility.",
    visualSignalImproved: "Versatile outfit signal — works across all contexts and frame types",
    statusLeakTags: ["outfit_fit"],
    goalTags: ["dating", "college", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating"],
    budgetTags: [2000],
    priorityScore: 85,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "local-vendor-stylist",
    title: "Local Stylist / Image Consultant (Placeholder)",
    category: "vendor",
    price: 5000,
    priceLabel: "₹5,000+",
    description: "Find a local stylist or image consultant for a one-time session.",
    whyItWorks: "Professional advice can identify blind spots that self-assessment misses.",
    visualSignalImproved: "Overall style coherence — professional feedback accelerates improvement",
    statusLeakTags: ["grooming", "outfit_fit", "accessories", "background"],
    goalTags: ["dating", "glowup"],
    auditTypeTags: ["photo", "outfit"],
    budgetTags: [10000, 25000],
    priorityScore: 70,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "phone-backup-charger",
    title: "Slim Power Bank",
    category: "phone_accessory",
    price: 900,
    priceLabel: "₹900",
    description: "A slim power bank that doesn't bulge in pockets or bags.",
    whyItWorks: "A dead phone means no photos — being prepared signals reliability.",
    visualSignalImproved: "Readiness signal — small prep items suggest an organized lifestyle",
    statusLeakTags: ["accessories"],
    goalTags: ["college", "office"],
    auditTypeTags: ["photo"],
    budgetTags: [2000],
    priorityScore: 35,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "wall-art-poster",
    title: "Simple Wall Art / Poster",
    category: "room",
    price: 400,
    priceLabel: "₹400",
    description: "A minimal framed poster or wall art to improve background visual interest.",
    whyItWorks: "A thoughtfully decorated background suggests intentionality without being loud.",
    visualSignalImproved: "Background personality — signals curated taste without clutter",
    statusLeakTags: ["background", "room_clutter"],
    goalTags: ["dating", "instagram", "college"],
    auditTypeTags: ["room", "photo"],
    budgetTags: [2000],
    priorityScore: 45,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "beard-trimmer",
    title: "Basic Beard Trimmer",
    category: "grooming",
    price: 600,
    priceLabel: "₹600",
    description: "A basic beard trimmer for maintaining clean facial hair.",
    whyItWorks: "Well-maintained facial hair signals grooming awareness more than any product.",
    visualSignalImproved: "Facial hair grooming — clean lines improve close-up photo impact",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "office", "glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: [2000],
    priorityScore: 76,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "outfit-bundle-5k",
    title: "Complete Outfit Bundle: Shirt + Shoes + Watch",
    category: "outfit",
    price: 4500,
    priceLabel: "₹4,500",
    description: "A coordinated outfit bundle with shirt, shoes, and watch within ₹5,000.",
    whyItWorks: "A coordinated outfit creates a cohesive visual signal that individual pieces cannot match.",
    visualSignalImproved: "Full outfit coherence — coordinated look signals higher style awareness",
    statusLeakTags: ["outfit_fit", "accessories"],
    goalTags: ["dating", "office", "glowup"],
    auditTypeTags: ["outfit", "photo", "dating"],
    budgetTags: [5000, 10000],
    priorityScore: 82,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
];
