import type { CommerceProduct, StoreKey } from "@/types/commerce";

const now = "2026-01-01T00:00:00.000Z";

function makeOffer(
  id: string,
  storeKey: StoreKey,
  storeName: string,
  productName: string,
  price: number,
  mrp: number | undefined,
  url: string,
  isAffiliate: boolean,
  isSponsored: boolean
) {
  const discountPercent =
    mrp && mrp > price ? Math.round(((mrp - price) / mrp) * 100) : undefined;
  return {
    id,
    storeKey,
    storeName,
    productName,
    price,
    mrp,
    discountPercent,
    url,
    isAffiliate,
    isSponsored,
    availabilityStatus: "available" as const,
    lastCheckedText: "Listed in AuraCheck catalog",
    updatedAt: now,
  };
}

const MNY = "Myntra";
const AJI = "AJIO";
const AMZ = "Amazon Fashion";
const FLP = "Flipkart Fashion";
const TCL = "Tata CLiQ";
const NYK = "Nykaa Fashion";
const MEE = "Meesho";
const SNI = "Snitch";
const SOU = "The Souled Store";
const BEW = "Bewakoof";
const HMI = "H&M India";

function mkMyntra(path: string) {
  return `https://www.myntra.com${path}`;
}
function mkAjio(path: string) {
  return `https://www.ajio.com${path}`;
}
function mkAmazon(path: string) {
  return `https://www.amazon.in${path}`;
}
function mkFlipkart(path: string) {
  return `https://www.flipkart.com${path}`;
}
function mkTata(path: string) {
  return `https://www.tatacliq.com${path}`;
}
function mkNykaa(path: string) {
  return `https://www.nykaafashion.com${path}`;
}
function mkMeesho(path: string) {
  return `https://www.meesho.com${path}`;
}

const M = "myntra" as StoreKey;
const A = "ajio" as StoreKey;
const Z = "amazon_fashion" as StoreKey;
const F = "flipkart_fashion" as StoreKey;
const C = "tata_cliq" as StoreKey;
const N = "nykaa_fashion" as StoreKey;
const E = "meesho" as StoreKey;
const S = "snitch" as StoreKey;
const O = "souled_store" as StoreKey;
const B = "bewakoof" as StoreKey;
const H = "hm_india" as StoreKey;

// ─── T-Shirts ───
const TSHIRTS: CommerceProduct[] = [
  {
    id: "tshirt_plain_white",
    title: "Plain White T-Shirt",
    category: "tshirt",
    styleDirections: ["clean_basic", "college_casual", "understated_confident", "dating_warm"],
    auraLeakTags: ["outfit_inconsistency", "too_plain", "color_mismatch", "over_flex"],
    goalTags: ["casual", "everyday", "social", "dating"],
    colorTags: ["white", "neutral"],
    fitTags: ["regular", "slim"],
    description: "The most versatile wardrobe essential. A clean white tee works with jeans, chinos, trousers, or layered under an overshirt.",
    whyItImprovesAura: "White reflects light onto your face, creating a cleaner, brighter first impression. It signals simplicity and confidence.",
    stylingTip: "Tuck loosely into dark jeans with a brown belt for a casual but intentional look.",
    avoidIf: "If you are very fair-skinned or have strong yellow undertones, try off-white or cream instead of pure white.",
    priorityScore: 95,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("tsw_m1", M, MNY, "Roadster Plain White T-Shirt", 399, 799, mkMyntra("/roadster-plain-white-t-shirt"), false, false),
      makeOffer("tsw_a1", A, AJI, "White Solid T-Shirt", 449, 999, mkAjio("/white-solid-t-shirt"), false, false),
      makeOffer("tsw_z1", Z, AMZ, "Symbol Basic Cotton T-Shirt White", 349, 699, mkAmazon("/symbol-basic-cotton-white"), false, false),
      makeOffer("tsw_f1", F, FLP, "Campus Sutra White T-Shirt", 299, 599, mkFlipkart("/campus-sutra-white-tshirt"), false, false),
      makeOffer("tsw_s1", S, SNI, "Snitch White Crew Neck", 599, 999, "https://www.snitch.co.in/collections/t-shirts", false, false),
      makeOffer("tsw_b1", B, BEW, "Bewakoof White T-Shirt", 349, 749, "https://www.bewakoof.com/men-white-t-shirts", false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tshirt_plain_black",
    title: "Plain Black T-Shirt",
    category: "tshirt",
    styleDirections: ["premium_minimal", "urban_aspirational", "street_smart", "clean_basic"],
    auraLeakTags: ["outfit_inconsistency", "too_plain", "low_premium_signal", "color_mismatch"],
    goalTags: ["casual", "everyday", "night", "social", "dating"],
    colorTags: ["black", "dark"],
    fitTags: ["regular", "slim"],
    description: "The black tee is the instant edge-giver. It signals understated confidence and works with virtually anything.",
    whyItImprovesAura: "Black frames your face and creates contrast. It signals seriousness and intentionality.",
    stylingTip: "Pair with dark jeans and white sneakers for a clean street-casual look that photographs well.",
    avoidIf: "Avoid black tee on black skin if you want contrast — try dark blue or burgundy instead for definition.",
    priorityScore: 90,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("tsb_m1", M, MNY, "Roadster Black T-Shirt", 399, 799, mkMyntra("/roadster-black-t-shirt"), false, false),
      makeOffer("tsb_a1", A, AJI, "Black Solid T-Shirt", 449, 999, mkAjio("/black-solid-t-shirt"), false, false),
      makeOffer("tsb_z1", Z, AMZ, "Symbol Black T-Shirt", 349, 699, mkAmazon("/symbol-basic-cotton-black"), false, false),
      makeOffer("tsb_f1", F, FLP, "Campus Sutra Black T-Shirt", 299, 599, mkFlipkart("/campus-sutra-black"), false, false),
      makeOffer("tsb_h1", H, HMI, "H&M Black Jersey Top", 499, 999, "https://www2.hm.com/en_in/productpage.123456.html", false, false),
      makeOffer("tsb_o1", O, SOU, "The Souled Store Black T-Shirt", 449, 799, "https://www.thesouledstore.com/collections/plain-t-shirts", false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tshirt_navy",
    title: "Solid Navy T-Shirt",
    category: "tshirt",
    styleDirections: ["clean_basic", "college_casual", "corporate_sharp", "dating_warm"],
    auraLeakTags: ["outfit_inconsistency", "too_plain", "color_mismatch"],
    goalTags: ["casual", "college", "everyday", "dating"],
    colorTags: ["navy", "blue", "dark"],
    fitTags: ["regular", "slim"],
    description: "Navy is the safe-smart option. More intentional than black, more structured than white.",
    whyItImprovesAura: "Navy signals calm confidence. It photographs well and pairs with every bottomwear color.",
    stylingTip: "Roll the sleeves slightly and pair with beige chinos for a smart-casual balance.",
    avoidIf: "If you are navy-on-navy head to toe, add a contrast piece like a white layer or brown shoes.",
    priorityScore: 85,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("tsn_m1", M, MNY, "Roadster Navy T-Shirt", 399, 799, mkMyntra("/roadster-navy-t-shirt"), false, false),
      makeOffer("tsn_z1", Z, AMZ, "Symbol Navy T-Shirt", 349, 699, mkAmazon("/symbol-basic-cotton-navy"), false, false),
      makeOffer("tsn_f1", F, FLP, "Campus Sutra Navy T-Shirt", 299, 599, mkFlipkart("/campus-sutra-navy"), false, false),
      makeOffer("tsn_s1", S, SNI, "Snitch Navy T-Shirt", 599, 999, "https://www.snitch.co.in/collections/t-shirts", false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tshirt_beige",
    title: "Solid Beige / Cream T-Shirt",
    category: "tshirt",
    styleDirections: ["premium_minimal", "soft_luxury", "dating_warm", "clean_basic"],
    auraLeakTags: ["too_plain", "color_mismatch", "low_premium_signal"],
    goalTags: ["casual", "smart", "dating", "vacation"],
    colorTags: ["beige", "cream", "neutral", "warm"],
    fitTags: ["regular", "relaxed"],
    description: "Beige/cream tees look more premium than white or black. They give a soft, approachable, elevated look.",
    whyItImprovesAura: "Warm neutrals make you look more approachable and photo-ready. Great for dating profile photos.",
    stylingTip: "Wear with olive cargo pants or dark blue jeans. Add a silver watch for a soft-luxury feel.",
    avoidIf: "Avoid cream/beige if you are prone to spills or sweat stains — keep it for clean controlled settings.",
    priorityScore: 82,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("tsbe_m1", M, MNY, "Roadster Beige T-Shirt", 449, 849, mkMyntra("/roadster-beige-t-shirt"), false, false),
      makeOffer("tsbe_a1", A, AJI, "Cream Solid T-Shirt", 499, 999, mkAjio("/cream-solid-t-shirt"), false, false),
      makeOffer("tsbe_z1", Z, AMZ, "Symbol Beige T-Shirt", 399, 699, mkAmazon("/symbol-basic-cotton-beige"), false, false),
      makeOffer("tsbe_o1", O, SOU, "The Souled Store Cream T-Shirt", 499, 799, "https://www.thesouledstore.com/collections/plain-t-shirts", false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Overshirts ───
const OVERSHIRTS: CommerceProduct[] = [
  {
    id: "overshirt_black",
    title: "Black Overshirt",
    category: "overshirt",
    styleDirections: ["urban_aspirational", "street_smart", "creator_bold", "clean_basic"],
    auraLeakTags: ["outfit_inconsistency", "low_premium_signal", "too_plain"],
    goalTags: ["casual", "smart", "social", "night", "creator"],
    colorTags: ["black", "dark"],
    fitTags: ["regular", "oversized"],
    description: "A black overshirt (shirt-jacket) layers over a tee to immediately upgrade any outfit from basic to intentional.",
    whyItImprovesAura: "Layering signals style effort. A black overshirt adds structure and visual weight to your silhouette.",
    stylingTip: "Wear open over a white tee with black jeans and white sneakers. This is the easiest high-impact upgrade.",
    avoidIf: "Avoid if you are already wearing a black tee — you need contrast between layers.",
    priorityScore: 92,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("osb_m1", M, MNY, "Roadster Black Overshirt", 1199, 2499, mkMyntra("/roadster-black-overshirt"), false, false),
      makeOffer("osb_a1", A, AJI, "Black Overshirt", 1299, 2799, mkAjio("/black-overshirt"), false, false),
      makeOffer("osb_z1", Z, AMZ, "Men's Cotton Overshirt Black", 999, 1999, mkAmazon("/cotton-overshirt-black"), false, false),
      makeOffer("osb_s1", S, SNI, "Snitch Layer Shirt Black", 1499, 2499, "https://www.snitch.co.in/collections/shirts", false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "overshirt_beige",
    title: "Beige / Olive Overshirt",
    category: "overshirt",
    styleDirections: ["premium_minimal", "soft_luxury", "dating_warm", "understated_confident"],
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency", "too_plain"],
    goalTags: ["smart", "dating", "vacation", "social"],
    colorTags: ["beige", "olive", "neutral", "warm"],
    fitTags: ["regular", "relaxed"],
    description: "A beige or olive overshirt is the premium-minimal uniform. It signals taste without trying hard.",
    whyItImprovesAura: "Earthy tones are associated with high social intuition. They suggest you understand presentation.",
    stylingTip: "Layer over a navy or black tee with cream/beige trousers for a monochrome premium look.",
    avoidIf: "Avoid with black jeans — go for blue or beige bottoms to keep the warm tone cohesive.",
    priorityScore: 88,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("osbe_m1", M, MNY, "Roadster Olive Overshirt", 1299, 2599, mkMyntra("/roadster-olive-overshirt"), false, false),
      makeOffer("osbe_a1", A, AJI, "Beige Overshirt", 1399, 2999, mkAjio("/beige-overshirt"), false, false),
      makeOffer("osbe_z1", Z, AMZ, "Cotton Overshirt Beige", 1099, 2199, mkAmazon("/cotton-overshirt-beige"), false, false),
      makeOffer("osbe_f1", F, FLP, "Metronaut Beige Overshirt", 999, 1999, mkFlipkart("/metronaut-beige-overshirt"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "overshirt_denim",
    title: "Denim Overshirt",
    category: "overshirt",
    styleDirections: ["college_casual", "street_smart", "clean_basic", "understated_confident"],
    auraLeakTags: ["outfit_inconsistency", "too_plain", "color_mismatch"],
    goalTags: ["casual", "college", "everyday", "social"],
    colorTags: ["blue", "denim"],
    fitTags: ["regular"],
    description: "A denim overshirt is a timeless layer. It adds texture and ruggedness without being loud.",
    whyItImprovesAura: "Denim signals durability and groundedness. It pairs with almost any bottom and shoe color.",
    stylingTip: "Wear over a white tee with black chinos and brown boots or clean sneakers.",
    avoidIf: "Avoid double-denim (denim overshirt + denim jeans) unless you intentionally style the Canadian tuxedo.",
    priorityScore: 83,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("osd_m1", M, MNY, "Roadster Denim Overshirt", 1399, 2799, mkMyntra("/roadster-denim-overshirt"), false, false),
      makeOffer("osd_a1", A, AJI, "Denim Overshirt", 1499, 2999, mkAjio("/denim-overshirt"), false, false),
      makeOffer("osd_z1", Z, AMZ, "Denim Shirt Jacket", 1199, 2499, mkAmazon("/denim-shirt-jacket"), false, false),
      makeOffer("osd_f1", F, FLP, "Campus Sutra Denim Overshirt", 1099, 2199, mkFlipkart("/campus-sutra-denim-overshirt"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Shirts ───
const SHIRTS: CommerceProduct[] = [
  {
    id: "shirt_oxford_white",
    title: "White Oxford Shirt",
    category: "shirt",
    styleDirections: ["corporate_sharp", "dating_warm", "clean_basic", "premium_minimal"],
    auraLeakTags: ["outfit_inconsistency", "low_premium_signal", "professional_mismatch", "dating_warmth_missing"],
    goalTags: ["office", "formal", "dating", "smart", "interview"],
    colorTags: ["white", "neutral"],
    fitTags: ["regular", "slim"],
    description: "The Oxford shirt is the most versatile formal-casual piece. It works in boardrooms, dates, and dinners.",
    whyItImprovesAura: "A crisp Oxford signals that you take yourself and the occasion seriously. It commands respect.",
    stylingTip: "Wear untucked with chinos for smart-casual, or tucked with trousers for formal settings.",
    avoidIf: "Avoid if you can't keep it ironed — a wrinkled Oxford looks worse than a clean t-shirt.",
    priorityScore: 89,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("oxw_m1", M, MNY, "Roadster White Oxford Shirt", 999, 1999, mkMyntra("/roadster-white-oxford-shirt"), false, false),
      makeOffer("oxw_z1", Z, AMZ, "U.S. Polo White Oxford Shirt", 1599, 2999, mkAmazon("/uspolo-white-oxford"), false, false),
      makeOffer("oxw_f1", F, FLP, "Van Heusen Oxford White", 1399, 2799, mkFlipkart("/van-heusen-oxford-white"), false, false),
      makeOffer("oxw_h1", H, HMI, "H&M Linen-Blend Shirt White", 1299, 2499, "https://www2.hm.com/en_in/", false, false),
      makeOffer("oxw_a1", A, AJI, "White Oxford Casual Shirt", 1099, 2399, mkAjio("/white-oxford-casual-shirt"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shirt_linen_white",
    title: "White Linen Shirt",
    category: "shirt",
    styleDirections: ["soft_luxury", "dating_warm", "premium_minimal", "clean_basic"],
    auraLeakTags: ["low_premium_signal", "professional_mismatch", "dating_warmth_missing"],
    goalTags: ["dating", "vacation", "summer", "smart", "social"],
    colorTags: ["white", "neutral"],
    fitTags: ["relaxed"],
    description: "Linen breathes confidence. A white linen shirt is the warm-weather power move.",
    whyItImprovesAura: "Linen signals that you understand fabric and texture — a subtle sign of refined taste.",
    stylingTip: "Roll sleeves to elbow, leave top 1-2 buttons open, pair with beige trousers or dark jeans.",
    avoidIf: "Linen wrinkles easily. If you can't handle the wrinkles (they are part of the look), choose a cotton-blend instead.",
    priorityScore: 80,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("linw_m1", M, MNY, "Roadster Linen Shirt White", 1199, 2499, mkMyntra("/roadster-linen-shirt-white"), false, false),
      makeOffer("linw_a1", A, AJI, "White Linen Shirt", 1299, 2799, mkAjio("/white-linen-shirt"), false, false),
      makeOffer("linw_z1", Z, AMZ, "Men's Linen Shirt White", 1099, 2299, mkAmazon("/linen-shirt-white"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shirt_black_casual",
    title: "Black Casual Shirt",
    category: "shirt",
    styleDirections: ["urban_aspirational", "creator_bold", "street_smart", "dating_warm"],
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency", "too_plain"],
    goalTags: ["night", "dating", "social", "creator"],
    colorTags: ["black", "dark"],
    fitTags: ["slim", "regular"],
    description: "A black shirt buttoned or worn open over a tee creates a sharp, intentional silhouette for evening settings.",
    whyItImprovesAura: "Black structured fabric signals formality and intention. It photographs well in low light.",
    stylingTip: "Wear fully buttoned with silver accessories for night, or open over a white tee for smart-casual.",
    avoidIf: "Avoid in direct sunlight or daytime heat — black absorbs heat and can look too heavy for daytime.",
    priorityScore: 78,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("blk_m1", M, MNY, "Roadster Black Casual Shirt", 899, 1799, mkMyntra("/roadster-black-casual-shirt"), false, false),
      makeOffer("blk_a1", A, AJI, "Black Slim Shirt", 999, 2199, mkAjio("/black-slim-shirt"), false, false),
      makeOffer("blk_z1", Z, AMZ, "Black Cotton Casual Shirt", 849, 1699, mkAmazon("/black-cotton-casual-shirt"), false, false),
      makeOffer("blk_f1", F, FLP, "Campus Sutra Black Shirt", 799, 1599, mkFlipkart("/campus-sutra-black-shirt"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Bottoms ───
const BOTTOMS: CommerceProduct[] = [
  {
    id: "jeans_dark_straight",
    title: "Dark Blue Straight Jeans",
    category: "jeans",
    styleDirections: ["clean_basic", "college_casual", "premium_minimal", "urban_aspirational"],
    auraLeakTags: ["outfit_inconsistency", "color_mismatch", "low_premium_signal"],
    goalTags: ["casual", "everyday", "college", "social", "dating"],
    colorTags: ["blue", "dark"],
    fitTags: ["straight", "regular"],
    description: "Dark straight jeans are the default bottom for almost any casual outfit. No rips, no fade — clean and intentional.",
    whyItImprovesAura: "Dark denim elongates your legs and creates a clean visual line. It pairs with every top color.",
    stylingTip: "Pair with any sneaker and a tucked tee for a clean, masculine silhouette that photographs well.",
    avoidIf: "Avoid with a denim jacket or denim overshirt unless you are intentionally styling double denim.",
    priorityScore: 91,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("djs_m1", M, MNY, "Roadster Dark Straight Jeans", 1399, 2799, mkMyntra("/roadster-dark-straight-jeans"), false, false),
      makeOffer("djs_a1", A, AJI, "Dark Blue Straight Jeans", 1499, 2999, mkAjio("/dark-blue-straight-jeans"), false, false),
      makeOffer("djs_z1", Z, AMZ, "Men's Dark Straight Jeans", 1299, 2599, mkAmazon("/dark-straight-jeans"), false, false),
      makeOffer("djs_f1", F, FLP, "Campus Sutra Dark Jeans", 1099, 2199, mkFlipkart("/campus-sutra-dark-jeans"), false, false),
      makeOffer("djs_h1", H, HMI, "H&M Slim Straight Jeans Dark Blue", 1799, 3499, "https://www2.hm.com/en_in/", false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "jeans_relaxed",
    title: "Relaxed Fit Jeans (Light Wash)",
    category: "jeans",
    styleDirections: ["college_casual", "street_smart", "clean_basic"],
    auraLeakTags: ["outfit_inconsistency"],
    goalTags: ["casual", "college", "everyday"],
    colorTags: ["blue", "light"],
    fitTags: ["relaxed"],
    description: "Relaxed light-wash jeans for casual everyday wear. Comfortable and approachable.",
    whyItImprovesAura: "Light wash denim signals relaxed confidence — you are comfortable in your own skin.",
    stylingTip: "Keep the fit intentional — relaxed does not mean baggy. Cuff the hem for cleaner lines.",
    avoidIf: "Avoid for dating or formal settings — light wash is too casual. Stick with dark for those.",
    priorityScore: 72,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("rlx_m1", M, MNY, "Roadster Relaxed Light Jeans", 1199, 2399, mkMyntra("/roadster-relaxed-light-jeans"), false, false),
      makeOffer("rlx_z1", Z, AMZ, "Men's Relaxed Light Wash Jeans", 1149, 2299, mkAmazon("/relaxed-light-wash-jeans"), false, false),
      makeOffer("rlx_f1", F, FLP, "Campus Sutra Relaxed Jeans", 999, 1999, mkFlipkart("/campus-sutra-relaxed-jeans"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "chinos_beige",
    title: "Beige Chinos",
    category: "chinos",
    styleDirections: ["premium_minimal", "clean_basic", "corporate_sharp", "dating_warm"],
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency", "professional_mismatch"],
    goalTags: ["smart", "office", "dating", "social"],
    colorTags: ["beige", "neutral", "warm"],
    fitTags: ["slim", "regular"],
    description: "Beige chinos bridge casual and formal. They are the Swiss Army knife of bottoms.",
    whyItImprovesAura: "Chinos signal that you thought about your outfit. Beige specifically is versatile and approachable.",
    stylingTip: "Pair with a navy tee and white sneakers for the perfect smart-casual uniform.",
    avoidIf: "Avoid if the fit is too tight or too loose — chinos need a tailored-looking fit to work.",
    priorityScore: 88,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("chb_m1", M, MNY, "Roadster Beige Chinos", 1299, 2499, mkMyntra("/roadster-beige-chinos"), false, false),
      makeOffer("chb_a1", A, AJI, "Beige Slim Chinos", 1399, 2899, mkAjio("/beige-slim-chinos"), false, false),
      makeOffer("chb_z1", Z, AMZ, "Men's Cotton Chinos Beige", 1199, 2499, mkAmazon("/cotton-chinos-beige"), false, false),
      makeOffer("chb_f1", F, FLP, "Campus Sutra Beige Chinos", 999, 1999, mkFlipkart("/campus-sutra-beige-chinos"), false, false),
      makeOffer("chb_h1", H, HMI, "H&M Chinos Beige", 1399, 2999, "https://www2.hm.com/en_in/", false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "trousers_neutral",
    title: "Neutral Tailored Trousers",
    category: "trousers",
    styleDirections: ["corporate_sharp", "premium_minimal", "understated_confident"],
    auraLeakTags: ["low_premium_signal", "professional_mismatch", "outfit_inconsistency"],
    goalTags: ["office", "formal", "smart", "interview"],
    colorTags: ["grey", "black", "neutral"],
    fitTags: ["slim", "regular", "tailored"],
    description: "Tailored trousers in grey or black for formal and professional settings. The non-jeans option for when you need to be taken seriously.",
    whyItImprovesAura: "Trousers signal that you understand dress codes and can adapt your presentation to the context.",
    stylingTip: "Pair with an Oxford shirt and belt that matches your shoes. No sneakers with these.",
    avoidIf: "Avoid if you mostly dress casual — start with chinos if you are not ready for trousers.",
    priorityScore: 76,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("trn_m1", M, MNY, "Roadster Grey Trousers", 1499, 2999, mkMyntra("/roadster-grey-trousers"), false, false),
      makeOffer("trn_a1", A, AJI, "Slim Trousers Grey", 1599, 3299, mkAjio("/slim-trousers-grey"), false, false),
      makeOffer("trn_z1", Z, AMZ, "Men's Formal Trousers Grey", 1399, 2799, mkAmazon("/formal-trousers-grey"), false, false),
      makeOffer("trn_f1", F, FLP, "Van Heusen Grey Trousers", 1799, 3599, mkFlipkart("/van-heusen-grey-trousers"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Footwear ───
const FOOTWEAR: CommerceProduct[] = [
  {
    id: "sneakers_white",
    title: "White Sneakers",
    category: "sneakers",
    styleDirections: ["clean_basic", "premium_minimal", "college_casual", "dating_warm", "corporate_sharp"],
    auraLeakTags: ["outfit_inconsistency", "low_premium_signal", "color_mismatch"],
    goalTags: ["casual", "everyday", "college", "dating", "social"],
    colorTags: ["white", "neutral"],
    fitTags: ["regular"],
    description: "Clean white sneakers are the most impactful footwear choice for improving visual presentation. They work with jeans, chinos, and even some trousers.",
    whyItImprovesAura: "White sneakers signal that you pay attention to detail. Dirty white sneakers do the opposite — keep them clean.",
    stylingTip: "Keep them clean. Scuffed white sneakers reduce aura more than wearing black shoes.",
    avoidIf: "Avoid if you need formal footwear — white sneakers are for smart-casual at most.",
    priorityScore: 94,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("snw_m1", M, MNY, "Roadster White Sneakers", 1499, 2999, mkMyntra("/roadster-white-sneakers"), false, false),
      makeOffer("snw_a1", A, AJI, "White Casual Sneakers", 1599, 3499, mkAjio("/white-casual-sneakers"), false, false),
      makeOffer("snw_z1", Z, AMZ, "Men's White Sneakers", 1399, 2999, mkAmazon("/white-sneakers"), false, false),
      makeOffer("snw_f1", F, FLP, "Campus Sutra White Sneakers", 1199, 2399, mkFlipkart("/campus-sutra-white-sneakers"), false, false),
      makeOffer("snw_s1", S, SNI, "Snitch White Sneakers", 1999, 3999, "https://www.snitch.co.in/collections/footwear", false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sneakers_black",
    title: "Black Sneakers",
    category: "sneakers",
    styleDirections: ["urban_aspirational", "street_smart", "creator_bold", "clean_basic"],
    auraLeakTags: ["outfit_inconsistency", "color_mismatch"],
    goalTags: ["casual", "night", "social", "everyday"],
    colorTags: ["black", "dark"],
    fitTags: ["regular"],
    description: "Black sneakers are the darker, edgier alternative to white. They hide dirt better and work for nighttime outfits.",
    whyItImprovesAura: "Black sneakers ground darker outfits. They are less noticeable than white but still signal intentional footwear choice.",
    stylingTip: "Wear with black jeans or dark chinos for a monochrome lower half that elongates.",
    avoidIf: "Avoid with shorts or light-colored bottoms — contrast is better with black sneakers.",
    priorityScore: 82,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("snb_m1", M, MNY, "Roadster Black Sneakers", 1499, 2999, mkMyntra("/roadster-black-sneakers"), false, false),
      makeOffer("snb_a1", A, AJI, "Black Casual Sneakers", 1599, 3499, mkAjio("/black-casual-sneakers"), false, false),
      makeOffer("snb_z1", Z, AMZ, "Men's Black Sneakers", 1399, 2999, mkAmazon("/black-sneakers"), false, false),
      makeOffer("snb_f1", F, FLP, "Campus Sutra Black Sneakers", 1199, 2399, mkFlipkart("/campus-sutra-black-sneakers"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "formal_shoes_brown",
    title: "Brown Formal Shoes",
    category: "formal_shoes",
    styleDirections: ["corporate_sharp", "understated_confident"],
    auraLeakTags: ["low_premium_signal", "professional_mismatch"],
    goalTags: ["formal", "office", "interview", "smart"],
    colorTags: ["brown", "dark"],
    fitTags: ["regular"],
    description: "Brown leather formal shoes for professional settings. Essential for interviews, office, and formal events.",
    whyItImprovesAura: "Formal shoes signal that you respect the context. Brown specifically suggests warmth and grounded confidence.",
    stylingTip: "Match belt to shoe color. Dark brown shoes need a dark brown belt.",
    avoidIf: "Avoid with casual outfits — formal shoes with jeans can look try-hard unless styled carefully.",
    priorityScore: 70,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("fsb_m1", M, MNY, "Red Tape Brown Formal Shoes", 1999, 3999, mkMyntra("/red-tape-brown-formal-shoes"), false, false),
      makeOffer("fsb_z1", Z, AMZ, "Men's Brown Formal Shoes", 1799, 3999, mkAmazon("/brown-formal-shoes"), false, false),
      makeOffer("fsb_f1", F, FLP, "Metronaut Brown Formal Shoes", 1599, 3499, mkFlipkart("/metronaut-brown-formal-shoes"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Accessories ───
const ACCESSORIES: CommerceProduct[] = [
  {
    id: "watch_minimal",
    title: "Minimal Analog Watch",
    category: "watch",
    styleDirections: ["premium_minimal", "clean_basic", "corporate_sharp", "dating_warm", "understated_confident"],
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency"],
    goalTags: ["smart", "formal", "dating", "everyday"],
    colorTags: ["silver", "black", "neutral"],
    fitTags: ["regular"],
    description: "A minimal analog watch with a clean dial and leather or metal strap. The single highest-ROI accessory for aura improvement.",
    whyItImprovesAura: "A watch signals that you value time and details. Even a budget clean watch looks intentional.",
    stylingTip: "Match the strap to your belt and shoe color. Silver case, brown or black strap.",
    avoidIf: "Avoid oversized digital sports watches with formal or smart-casual outfits.",
    priorityScore: 93,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("wtc_m1", M, MNY, "Fastrack Minimal Analog Watch", 1495, 2995, mkMyntra("/fastrack-minimal-analog-watch"), false, false),
      makeOffer("wtc_z1", Z, AMZ, "Titan Minimalist Watch", 2995, 5995, mkAmazon("/titan-minimalist-watch"), false, false),
      makeOffer("wtc_f1", F, FLP, "Noise Minimal Analog Watch", 1499, 2999, mkFlipkart("/noise-minimal-analog-watch"), false, false),
      makeOffer("wtc_a1", A, AJI, "Casual Minimalist Watch", 1799, 3999, mkAjio("/casual-minimalist-watch"), false, false),
      makeOffer("wtc_c1", C, TCL, "Titan Edge Analog Watch", 4995, 9995, mkTata("/titan-edge-watch"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "belt_black",
    title: "Black Leather Belt",
    category: "belt",
    styleDirections: ["clean_basic", "corporate_sharp", "premium_minimal", "understated_confident"],
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency"],
    goalTags: ["formal", "smart", "everyday"],
    colorTags: ["black", "dark"],
    fitTags: ["regular"],
    description: "A simple black leather belt with a minimal buckle. It completes every outfit that has belt loops.",
    whyItImprovesAura: "A belt signals completion — your outfit looks finished. No belt with tucked shirt is an immediate signal gap.",
    stylingTip: "Match your belt to your shoes. Black shoes need a black belt.",
    avoidIf: "Avoid oversized logo buckles for smart settings. Keep it minimal.",
    priorityScore: 85,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("bltb_m1", M, MNY, "Roadster Black Leather Belt", 599, 1299, mkMyntra("/roadster-black-leather-belt"), false, false),
      makeOffer("bltb_z1", Z, AMZ, "Men's Black Leather Belt", 499, 999, mkAmazon("/black-leather-belt"), false, false),
      makeOffer("bltb_f1", F, FLP, "Campus Sutra Black Belt", 449, 899, mkFlipkart("/campus-sutra-black-belt"), false, false),
      makeOffer("bltb_a1", A, AJI, "Black Leather Strap Belt", 599, 1299, mkAjio("/black-leather-belt"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "belt_brown",
    title: "Brown Leather Belt",
    category: "belt",
    styleDirections: ["clean_basic", "dating_warm", "corporate_sharp", "premium_minimal"],
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency"],
    goalTags: ["formal", "smart", "everyday", "dating"],
    colorTags: ["brown", "warm"],
    fitTags: ["regular"],
    description: "A brown belt adds warmth to your outfit. Best paired with chinos, beige trousers, or blue jeans.",
    whyItImprovesAura: "Brown shows attention to color coordination. It pairs naturally with warmer outfit palettes.",
    stylingTip: "Match to brown shoes. Use black belt for black/grey outfits, brown for blue/beige/earth tones.",
    priorityScore: 80,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("bltbr_m1", M, MNY, "Roadster Brown Leather Belt", 599, 1299, mkMyntra("/roadster-brown-leather-belt"), false, false),
      makeOffer("bltbr_z1", Z, AMZ, "Men's Brown Leather Belt", 499, 999, mkAmazon("/brown-leather-belt"), false, false),
      makeOffer("bltbr_f1", F, FLP, "Campus Sutra Brown Belt", 449, 899, mkFlipkart("/campus-sutra-brown-belt"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sunglasses_wayfarer",
    title: "Classic Wayfarer Sunglasses",
    category: "sunglasses",
    styleDirections: ["premium_minimal", "creator_bold", "street_smart", "dating_warm"],
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency"],
    goalTags: ["summer", "vacation", "social", "creator"],
    colorTags: ["black", "neutral"],
    fitTags: ["regular"],
    description: "Classic wayfarer-style sunglasses. A timeless shape that works on most face shapes and outfit styles.",
    whyItImprovesAura: "Sunglasses add an element of curated mystery. They also protect your eyes from squinting in photos.",
    stylingTip: "Black or tortoise-shell wayfarers work with almost any casual outfit. Clean them before wearing.",
    avoidIf: "Avoid novelty or heavily tinted colored lenses for a general style upgrade.",
    priorityScore: 75,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("sun_m1", M, MNY, "Roadster Wayfarer Sunglasses", 599, 1499, mkMyntra("/roadster-wayfarer-sunglasses"), false, false),
      makeOffer("sun_a1", A, AJI, "Classic Wayfarer Sunglasses", 699, 1599, mkAjio("/classic-wayfarer-sunglasses"), false, false),
      makeOffer("sun_z1", Z, AMZ, "Men's Wayfarer Sunglasses", 549, 1299, mkAmazon("/wayfarer-sunglasses"), false, false),
      makeOffer("sun_f1", F, FLP, "Campus Sutra Wayfarer", 499, 999, mkFlipkart("/campus-sutra-wayfarer"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Outerwear ───
const OUTERWEAR: CommerceProduct[] = [
  {
    id: "hoodie_neutral",
    title: "Neutral / Grey Hoodie",
    category: "hoodie",
    styleDirections: ["college_casual", "clean_basic", "street_smart", "understated_confident"],
    auraLeakTags: ["outfit_inconsistency", "too_plain"],
    goalTags: ["casual", "college", "everyday", "winter"],
    colorTags: ["grey", "neutral"],
    fitTags: ["regular", "relaxed"],
    description: "A neutral grey hoodie is the comfortable-but-intentional layer for cold days or casual settings.",
    whyItImprovesAura: "A clean, non-branded hoodie signals comfort with yourself. Avoid oversized logos.",
    stylingTip: "Layer under a denim or black overshirt for a structured casual look.",
    avoidIf: "Avoid if going to a formal or dating setting — hoodies are too casual for those contexts.",
    priorityScore: 68,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("hdn_m1", M, MNY, "Roadster Grey Hoodie", 999, 1999, mkMyntra("/roadster-grey-hoodie"), false, false),
      makeOffer("hdn_z1", Z, AMZ, "Men's Grey Cotton Hoodie", 899, 1799, mkAmazon("/grey-cotton-hoodie"), false, false),
      makeOffer("hdn_f1", F, FLP, "Campus Sutra Grey Hoodie", 799, 1599, mkFlipkart("/campus-sutra-grey-hoodie"), false, false),
      makeOffer("hdn_o1", O, SOU, "The Souled Store Grey Hoodie", 999, 1999, "https://www.thesouledstore.com/collections/hoodies", false, false),
      makeOffer("hdn_b1", B, BEW, "Bewakoof Pullover Grey", 849, 1699, "https://www.bewakoof.com/hoodies", false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "jacket_bomber",
    title: "Black Bomber Jacket",
    category: "jacket",
    styleDirections: ["urban_aspirational", "street_smart", "creator_bold"],
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency"],
    goalTags: ["social", "night", "creator", "winter"],
    colorTags: ["black", "dark"],
    fitTags: ["regular"],
    description: "A black bomber jacket is the easiest outerwear upgrade. It adds instant edge without being loud.",
    whyItImprovesAura: "A bomber jacket signals casual toughness. It creates a V-shape silhouette that photographs well.",
    stylingTip: "Wear with a white tee and dark jeans for a timeless look. Keep it unzipped for better lines.",
    avoidIf: "Avoid shiny/patent material bombers — go for matte cotton or nylon finish.",
    priorityScore: 84,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("bmb_m1", M, MNY, "Roadster Black Bomber Jacket", 1799, 3599, mkMyntra("/roadster-black-bomber-jacket"), false, false),
      makeOffer("bmb_a1", A, AJI, "Black Bomber Jacket", 1999, 3999, mkAjio("/black-bomber-jacket"), false, false),
      makeOffer("bmb_z1", Z, AMZ, "Men's Black Bomber Jacket", 1699, 3499, mkAmazon("/black-bomber-jacket"), false, false),
      makeOffer("bmb_f1", F, FLP, "Campus Sutra Bomber Jacket", 1499, 2999, mkFlipkart("/campus-sutra-bomber-jacket"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Ethnic ───
const ETHNIC: CommerceProduct[] = [
  {
    id: "kurta_clean",
    title: "Clean White / Ivory Kurta",
    category: "kurta",
    styleDirections: ["ethnic_clean", "soft_luxury"],
    auraLeakTags: ["outfit_inconsistency", "color_mismatch"],
    goalTags: ["ethnic", "festival", "wedding", "formal"],
    colorTags: ["white", "ivory", "neutral"],
    fitTags: ["regular", "relaxed"],
    description: "A clean ivory kurta with minimal or no embroidery. The ethnic equivalent of the white tee — versatile and intentional.",
    whyItImprovesAura: "A clean kurta signals respect for cultural dress codes. It suggests balance between modern and traditional.",
    stylingTip: "Pair with neutral churidar or trousers and clean mojari or sneakers for a fusion look.",
    avoidIf: "Avoid heavily embroidered or shiny kurtas for everyday ethnic wear — keep it simple.",
    priorityScore: 74,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("krt_m1", M, MNY, "Roadster Ivory Kurta", 999, 1999, mkMyntra("/roadster-ivory-kurta"), false, false),
      makeOffer("krt_z1", Z, AMZ, "Men's Cotton Kurta White", 899, 1799, mkAmazon("/cotton-kurta-white"), false, false),
      makeOffer("krt_f1", F, FLP, "Campus Sutra White Kurta", 799, 1599, mkFlipkart("/campus-sutra-white-kurta"), false, false),
      makeOffer("krt_a1", A, AJI, "Clean White Kurta", 999, 2199, mkAjio("/clean-white-kurta"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Grooming & Photo Setup ───
const EXTRAS: CommerceProduct[] = [
  {
    id: "grooming_kit",
    title: "Basic Grooming Kit (Comb, Trimmer, Moisturizer)",
    category: "grooming",
    styleDirections: ["clean_basic", "premium_minimal", "college_casual", "corporate_sharp"],
    auraLeakTags: ["weak_clarity", "outfit_inconsistency"],
    goalTags: ["grooming", "everyday"],
    colorTags: [],
    fitTags: [],
    description: "A basic grooming set: good comb, beard trimmer, and moisturizer. Grooming directly impacts perceived aura.",
    whyItImprovesAura: "Grooming signals self-respect. Clean hair, shaped facial hair, and moisturized skin make any outfit look better.",
    stylingTip: "Shape your eyebrows and trim nose hair before photos. These are the most commonly missed grooming details.",
    avoidIf: "Avoid over-grooming — natural is better than over-styled.",
    priorityScore: 90,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("grw_m1", M, MNY, "Men's Grooming Kit Set", 499, 999, mkMyntra("/mens-grooming-kit"), false, false),
      makeOffer("grw_z1", Z, AMZ, "Basic Grooming Kit", 399, 799, mkAmazon("/basic-grooming-kit"), false, false),
      makeOffer("grw_f1", F, FLP, "Grooming Essentials Kit", 449, 899, mkFlipkart("/grooming-essentials-kit"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "perfume_fresh",
    title: "Fresh Daily Perfume / Deodorant",
    category: "perfume",
    styleDirections: ["clean_basic", "dating_warm", "soft_luxury", "urban_aspirational"],
    auraLeakTags: ["dating_warmth_missing"],
    goalTags: ["grooming", "dating", "everyday"],
    colorTags: [],
    fitTags: [],
    description: "A fresh, clean fragrance for daily wear. Choose citrus or aquatic notes for daytime, woody for evening.",
    whyItImprovesAura: "Scent is the invisible signal. A clean fragrance suggests you care about the full sensory experience.",
    stylingTip: "Spray on pulse points (wrists, neck, behind ears). One spray is enough — don't overdo it.",
    avoidIf: "Avoid heavy, sweet, or cloying fragrances for daytime. Save those for dates or evenings.",
    priorityScore: 77,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("prf_m1", M, MNY, "Park Avenue Fresh Perfume", 449, 899, mkMyntra("/park-avenue-fresh-perfume"), false, false),
      makeOffer("prf_z1", Z, AMZ, "Men's Fresh Deodorant Pack", 399, 799, mkAmazon("/fresh-deodorant-pack"), false, false),
      makeOffer("prf_f1", F, FLP, "Wild Stone Fresh Perfume", 499, 999, mkFlipkart("/wild-stone-fresh-perfume"), false, false),
      makeOffer("prf_n1", N, NYK, "Nykaa Men Perfume", 599, 1299, mkNykaa("/nykaa-men-perfume"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "photo_tripod",
    title: "Phone Tripod Stand",
    category: "photo_accessory",
    styleDirections: ["clean_basic", "creator_bold"],
    auraLeakTags: ["weak_lighting", "weak_framing", "weak_clarity", "busy_background"],
    goalTags: ["photo", "content"],
    colorTags: [],
    fitTags: [],
    description: "A basic phone tripod for consistent framing and hands-free photo taking. Essential for profile photo improvement.",
    whyItImprovesAura: "A tripod lets you take multiple shots at the same angle. This is the #1 tool for improving photo quality without a photographer.",
    stylingTip: "Set at chest height, slightly tilted down. Use the 2-second timer to avoid shaky hands.",
    avoidIf: "Avoid ultra-cheap tripods that can't hold your phone steady. Invest ₹500+ for stability.",
    priorityScore: 89,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("trp_z1", Z, AMZ, "Boya Phone Tripod", 599, 1299, mkAmazon("/boya-phone-tripod"), false, false),
      makeOffer("trp_f1", F, FLP, "Universal Phone Tripod", 499, 999, mkFlipkart("/universal-phone-tripod"), false, false),
      makeOffer("trp_m1", M, MNY, "Phone Tripod Stand", 699, 1499, mkMyntra("/phone-tripod-stand"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ring_light",
    title: "Ring Light (10-inch)",
    category: "photo_accessory",
    styleDirections: ["clean_basic", "creator_bold"],
    auraLeakTags: ["weak_lighting", "weak_clarity"],
    goalTags: ["photo", "content"],
    colorTags: [],
    fitTags: [],
    description: "A 10-inch ring light with adjustable brightness and color temperature. The single biggest upgrade for photo lighting.",
    whyItImprovesAura: "Good lighting is the #1 factor in photo quality. A ring light eliminates harsh shadows and adds catchlights to your eyes.",
    stylingTip: "Position at face height, slightly to the side (not directly in front) for better shadow definition.",
    avoidIf: "Avoid if you have good natural lighting — ring lights are best for indoor/low-light situations.",
    priorityScore: 95,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("rng_z1", Z, AMZ, "10-inch Ring Light with Stand", 799, 1599, mkAmazon("/ring-light-10-inch"), false, false),
      makeOffer("rng_f1", F, FLP, "Ring Light with Tripod", 699, 1499, mkFlipkart("/ring-light-with-tripod"), false, false),
      makeOffer("rng_m1", M, MNY, "Digitek Ring Light", 999, 1999, mkMyntra("/digitek-ring-light"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bg_cloth_neutral",
    title: "Neutral Background Cloth (Grey/White)",
    category: "background_item",
    styleDirections: ["clean_basic", "creator_bold"],
    auraLeakTags: ["busy_background", "weak_clarity"],
    goalTags: ["photo", "content"],
    colorTags: ["grey", "white", "neutral"],
    fitTags: [],
    description: "A large neutral-colored cloth or sheet to create a clean background for photos. Instantly removes background clutter.",
    whyItImprovesAura: "A clean background removes visual noise. The subject (you) becomes the focus of the photo.",
    stylingTip: "Drape over a chair or door. Grey gives a professional studio look, white looks clean and airy.",
    avoidIf: "Avoid if you have a naturally clean, neutral wall available.",
    priorityScore: 85,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("bgc_z1", Z, AMZ, "Photo Background Cloth Grey", 349, 699, mkAmazon("/photo-background-cloth-grey"), false, false),
      makeOffer("bgc_f1", F, FLP, "Muslin Background Sheet", 299, 599, mkFlipkart("/muslin-background-sheet"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "lens_cloth",
    title: "Microfiber Lens Cleaning Cloth",
    category: "photo_accessory",
    styleDirections: ["clean_basic", "creator_bold"],
    auraLeakTags: ["weak_clarity"],
    goalTags: ["photo"],
    colorTags: [],
    fitTags: [],
    description: "A simple microfiber cloth to clean your phone camera lens before taking photos. The most underrated photo improvement tool.",
    whyItImprovesAura: "A dirty lens reduces clarity and sharpness. Cleaning it takes 2 seconds and instantly improves photo quality.",
    stylingTip: "Wipe your camera lens before every photo session. Keep the cloth in your pocket or bag.",
    avoidIf: "Never use your shirt or rough fabric — they can scratch the lens coating.",
    priorityScore: 88,
    isSponsored: false,
    isActive: true,
    offers: [
      makeOffer("lns_z1", Z, AMZ, "Microfiber Lens Cleaning Cloth Pack", 199, 399, mkAmazon("/microfiber-lens-cloth"), false, false),
      makeOffer("lns_f1", F, FLP, "Lens Cleaning Cloth Set", 149, 299, mkFlipkart("/lens-cleaning-cloth-set"), false, false),
      makeOffer("lns_m1", M, MNY, "Camera Lens Cleaning Cloth", 249, 499, mkMyntra("/camera-lens-cleaning-cloth"), false, false),
    ],
    createdAt: now,
    updatedAt: now,
  },
];

export const WARDROBE_CATALOG: CommerceProduct[] = [
  ...TSHIRTS,
  ...OVERSHIRTS,
  ...SHIRTS,
  ...BOTTOMS,
  ...FOOTWEAR,
  ...ACCESSORIES,
  ...OUTERWEAR,
  ...ETHNIC,
  ...EXTRAS,
];

export function getProductById(id: string): CommerceProduct | undefined {
  return WARDROBE_CATALOG.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): CommerceProduct[] {
  return WARDROBE_CATALOG.filter((p) => p.category === category);
}

export function getProductsByStyleDirection(direction: string): CommerceProduct[] {
  return WARDROBE_CATALOG.filter((p) => p.styleDirections.includes(direction as any));
}

export function getProductsByLeakTag(tag: string): CommerceProduct[] {
  return WARDROBE_CATALOG.filter((p) => p.auraLeakTags.includes(tag as any));
}
