import type { AuraLeakTag, AuraStyleDirection, WardrobeCategory } from "@/types/commerce";

export interface CelebrityTrendPreset {
  id: string;
  label: string;
  celebrity: string;
  imageSrc: string;
  avatarLabel: string;
  avatarGradient: string;
  region: "India" | "Global";
  trendDateLabel: string;
  sourceLabel: string;
  sourceUrl: string;
  summary: string;
  styleDirection: AuraStyleDirection;
  auraLeakTags: AuraLeakTag[];
  recommendedCategories: WardrobeCategory[];
  searchQuery: string;
  budgetMax?: number;
}

export const CELEBRITY_TREND_PRESETS: CelebrityTrendPreset[] = [
  {
    id: "oscars-wide-leg-tailoring",
    label: "Relaxed Red Carpet Tailoring",
    celebrity: "Red Carpet Approved",
    imageSrc: "/celebs/oscars-wide-leg-tailoring.jpg",
    avatarLabel: "MB",
    avatarGradient: "from-slate-200 via-zinc-300 to-amber-200",
    region: "Global",
    trendDateLabel: "March 2026",
    sourceLabel: "GQ Oscars 2026 best-dressed",
    sourceUrl: "https://www.gq.com/story/oscars-2026-best-dressed-celebrities-red-carpet-menswear",
    summary:
      "Wide-leg tailoring and cleaner formal lines are the smarter 2026 move versus stiff, old-school slim formalwear.",
    styleDirection: "understated_confident",
    auraLeakTags: ["professional_mismatch", "low_premium_signal", "too_plain"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "watch", "jacket"],
    searchQuery: "wide leg trousers relaxed tailoring formal shoes understated confident",
    budgetMax: 15000,
  },
  {
    id: "timothee-clean-minimal",
    label: "Effortless Clean Basics",
    celebrity: "Off-Duty Minimalist",
    imageSrc: "/celebs/timothee-clean-minimal.jpg",
    avatarLabel: "TC",
    avatarGradient: "from-stone-200 via-neutral-300 to-gray-400",
    region: "Global",
    trendDateLabel: "May 2026",
    sourceLabel: "GQ relaxed tailoring trend",
    sourceUrl: "https://www.gq.com/story/relaxed-tailoring-trend-2026",
    summary:
      "Oversized tees, raw-hem trousers, and layered lightweight outerwear — the art of looking undone without looking unkempt.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "trousers", "sneakers", "jacket", "hoodie"],
    searchQuery: "oversized tshirt relaxed trousers clean basics minimalist menswear",
    budgetMax: 6000,
  },
  {
    id: "hrithik-resort-luxe",
    label: "Soft Luxury Resort Wear",
    celebrity: "Resort-Ready Edit",
    imageSrc: "/celebs/hrithik-dating-warm.jpg",
    avatarLabel: "HR",
    avatarGradient: "from-amber-200 via-orange-300 to-rose-400",
    region: "India",
    trendDateLabel: "February 2026",
    sourceLabel: "Vogue India resort collection trends",
    sourceUrl: "https://www.vogue.in/content/resort-collection-trends-2026",
    summary:
      "Linen shirts, tailored shorts, and premium accessories — resort wear that transitions from brunch to evening effortlessly.",
    styleDirection: "soft_luxury",
    auraLeakTags: ["low_premium_signal", "color_mismatch", "dating_warmth_missing"],
    recommendedCategories: ["shirt", "trousers", "sunglasses", "watch", "perfume"],
    searchQuery: "linen shirt tailored shorts resort wear pastel luxury summer",
    budgetMax: 10000,
  },
  {
    id: "ranveer-creator-bold",
    label: "Bold Creator Edge",
    celebrity: "Bold & Unapologetic",
    imageSrc: "/celebs/ranveer-creator-bold.jpg",
    avatarLabel: "RS",
    avatarGradient: "from-yellow-300 via-orange-400 to-red-500",
    region: "India",
    trendDateLabel: "April 2026",
    sourceLabel: "GQ India bold print styling",
    sourceUrl: "https://www.gqindia.com/content/ranveer-singh-bold-print-fashion-trend",
    summary:
      "Bold prints, clashing textures, and fearless colour-blocking — for when you want your outfit to start the conversation.",
    styleDirection: "creator_bold",
    auraLeakTags: ["over_flex", "color_mismatch", "creator_energy_missing"],
    recommendedCategories: ["jacket", "tshirt", "sneakers", "sunglasses", "watch"],
    searchQuery: "printed shirt bold colors statement jacket sneakers street style",
    budgetMax: 10000,
  },
  {
    id: "ibrahim-college-casual",
    label: "Campus Cool Refresh",
    celebrity: "Campus Street Energy",
    imageSrc: "/celebs/ibrahim-college-casual.jpg",
    avatarLabel: "IA",
    avatarGradient: "from-blue-200 via-indigo-300 to-slate-400",
    region: "India",
    trendDateLabel: "March 2026",
    sourceLabel: "Vogue India college street style",
    sourceUrl: "https://www.vogue.in/content/college-street-style-trends-2026",
    summary:
      "Clean denim, retro sneakers, boxy tees, and bomber jackets — the freshest campus look that says effortless without trying.",
    styleDirection: "college_casual",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["jeans", "tshirt", "sneakers", "jacket", "hoodie"],
    searchQuery: "clean denim retro sneakers bomber jacket campus streetwear",
    budgetMax: 7000,
  },
  {
    id: "shahid-corporate-sharp",
    label: "Boardroom Sharp Edit",
    celebrity: "Power Dressing Edit",
    imageSrc: "/celebs/shahid-corporate-sharp.jpg",
    avatarLabel: "SK",
    avatarGradient: "from-gray-300 via-zinc-400 to-blue-600",
    region: "India",
    trendDateLabel: "January 2026",
    sourceLabel: "GQ India sharp suiting trend",
    sourceUrl: "https://www.gqindia.com/content/sharp-suiting-trends-workwear-2026",
    summary:
      "Precise tailoring, slim-lapel blazers, crisp shirts, and minimal accessories — the uniform of someone who means business.",
    styleDirection: "corporate_sharp",
    auraLeakTags: ["professional_mismatch", "low_premium_signal", "color_mismatch"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "watch", "belt"],
    searchQuery: "slim blazer dress shirt tailored trousers formal shoes corporate",
    budgetMax: 12000,
  },
  {
    id: "hrithik-dating-warm",
    label: "Date Night Warmth",
    celebrity: "Warm & Approachable",
    imageSrc: "/celebs/hrithik-dating-warm.jpg",
    avatarLabel: "HR",
    avatarGradient: "from-amber-200 via-orange-300 to-rose-400",
    region: "India",
    trendDateLabel: "February 2026",
    sourceLabel: "Vogue India date night style guide",
    sourceUrl: "https://www.vogue.in/content/date-night-outfit-ideas-men-2026",
    summary:
      "Warm earth tones, textured knits, clean denim, and leather boots — approachable, masculine, and visually interesting without overdoing it.",
    styleDirection: "dating_warm",
    auraLeakTags: ["dating_warmth_missing", "too_plain", "color_mismatch"],
    recommendedCategories: ["shirt", "jeans", "watch", "jacket", "sneakers"],
    searchQuery: "earth tones knitwear leather boots warm date night outfit",
    budgetMax: 9000,
  },
  {
    id: "siddharth-ethnic-clean",
    label: "Modern Ethnic Clean",
    celebrity: "Festive Season Edit",
    imageSrc: "/celebs/siddharth-ethnic-clean.jpg",
    avatarLabel: "SM",
    avatarGradient: "from-emerald-200 via-teal-300 to-cyan-400",
    region: "India",
    trendDateLabel: "May 2026",
    sourceLabel: "Vogue India wedding guest style",
    sourceUrl: "https://www.vogue.in/content/wedding-guest-outfit-ideas-men-2026",
    summary:
      "Clean-lined kurtas, churidars with a modern drape, and minimal mojari — ethnic wear stripped of clutter, built for the contemporary man.",
    styleDirection: "ethnic_clean",
    auraLeakTags: ["professional_mismatch", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["kurta", "trousers", "watch", "belt", "sneakers"],
    searchQuery: "clean kurta churidar ethnic wear minimal wedding guest",
    budgetMax: 7000,
  },
  {
    id: "virat-gym-casual",
    label: "Gym-to-Street Athleisure",
    celebrity: "Athlete Off-Duty",
    imageSrc: "/celebs/virat-gym-casual.jpg",
    avatarLabel: "VK",
    avatarGradient: "from-gray-600 via-zinc-500 to-slate-400",
    region: "India",
    trendDateLabel: "June 2026",
    sourceLabel: "GQ India athleisure style guide",
    sourceUrl: "https://www.gqindia.com/content/best-athleisure-style-men-2026",
    summary:
      "Performance fabrics that look sharp off the field: joggers with structure, tech-fabric tees, sleek trainers, and minimal accessories.",
    styleDirection: "gym_casual",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["tshirt", "sneakers", "hoodie", "jacket", "watch"],
    searchQuery: "tech joggers performance tee athleisure sneakers gym street style",
    budgetMax: 6000,
  },
  {
    id: "kartik-mumbai-street",
    label: "Mumbai Street Luxe",
    celebrity: "Mumbai Street Energy",
    imageSrc: "/celebs/kartik-mumbai-street.jpg",
    avatarLabel: "KA",
    avatarGradient: "from-sky-200 via-blue-300 to-indigo-400",
    region: "India",
    trendDateLabel: "April 2026",
    sourceLabel: "GQ India street style picks",
    sourceUrl: "https://www.gqindia.com/content/street-style-trends-mumbai-2026",
    summary:
      "Lightweight bombers, distressed denim, graphic tees, and chunky sneakers — the Mumbai street look that filters from Versace to the high street.",
    styleDirection: "urban_aspirational",
    auraLeakTags: ["too_plain", "creator_energy_missing", "outfit_inconsistency"],
    recommendedCategories: ["jacket", "jeans", "tshirt", "sneakers", "sunglasses"],
    searchQuery: "lightweight bomber distressed denim graphic tee chunky sneakers",
    budgetMax: 8000,
  },
  {
    id: "harry-quiet-luxury",
    label: "Quiet Luxury Travel",
    celebrity: "Quiet Luxury Edit",
    imageSrc: "/celebs/harry-quiet-luxury.jpg",
    avatarLabel: "HS",
    avatarGradient: "from-peach-200 via-coral-300 to-rose-400",
    region: "Global",
    trendDateLabel: "March 2026",
    sourceLabel: "Vogue quiet luxury trend report",
    sourceUrl: "https://www.vogue.com/article/quiet-luxury-travel-wardrobe-2026",
    summary:
      "Understated investment pieces: unlined blazers, fine-gauge knits, tailored wide trousers, and leather accessories that whisper status.",
    styleDirection: "premium_minimal",
    auraLeakTags: ["low_premium_signal", "too_plain", "professional_mismatch"],
    recommendedCategories: ["jacket", "tshirt", "trousers", "watch", "belt"],
    searchQuery: "unlined blazer fine knit cashmere wide trousers quiet luxury",
    budgetMax: 15000,
  },
  {
    id: "dev-effortless-date",
    label: "Effortless Date Night",
    celebrity: "Effortless Charisma",
    imageSrc: "/celebs/dev-effortless-date.jpg",
    avatarLabel: "DP",
    avatarGradient: "from-olive-200 via-amber-300 to-brown-400",
    region: "Global",
    trendDateLabel: "May 2026",
    sourceLabel: "GQ date night outfit guide",
    sourceUrl: "https://www.gq.com/story/date-night-outfits-men-2026",
    summary:
      "Smart without stiffness: a great overshirt, dark jeans, clean white sneakers, and a leather jacket — the uniform of quiet charisma.",
    styleDirection: "understated_confident",
    auraLeakTags: ["dating_warmth_missing", "outfit_inconsistency", "too_plain"],
    recommendedCategories: ["overshirt", "jeans", "sneakers", "jacket", "watch"],
    searchQuery: "overshirt dark wash jeans white sneakers leather jacket date night",
    budgetMax: 10000,
  },
  {
    id: "global-street-tech",
    label: "Tokyo Street Tech",
    celebrity: "Global Street Style",
    imageSrc: "/celebs/global-street-tech.jpg",
    avatarLabel: "GS",
    avatarGradient: "from-lime-200 via-green-300 to-cyan-400",
    region: "Global",
    trendDateLabel: "June 2026",
    sourceLabel: "Hypebeast streetwear roundup",
    sourceUrl: "https://hypebeast.com/2026/streetwear-trends-2026",
    summary:
      "Tech fabrics, cargo silhouettes, neons accents, and futuristic sneakers — streetwear that nods to Harajuku while staying wearable.",
    styleDirection: "street_smart",
    auraLeakTags: ["creator_energy_missing", "too_plain", "outfit_inconsistency"],
    recommendedCategories: ["jacket", "tshirt", "sneakers", "hoodie", "sunglasses"],
    searchQuery: "tech cargo pants graphic hoodie futuristic sneakers streetwear harajuku",
    budgetMax: 10000,
  },
  {
    id: "south-soft-luxury",
    label: "South Indian Soft Luxury",
    celebrity: "Southern Sophistication",
    imageSrc: "/celebs/south-soft-luxury.jpg",
    avatarLabel: "DQ",
    avatarGradient: "from-amber-100 via-yellow-200 to-orange-300",
    region: "India",
    trendDateLabel: "June 2026",
    sourceLabel: "Vogue India south style guide",
    sourceUrl: "https://www.vogue.in/content/south-indian-fashion-trends-2026",
    summary:
      "Cream linen, clean chinos, leather loafers, and minimal accessories — the understated South Indian gentleman's uniform.",
    styleDirection: "soft_luxury",
    auraLeakTags: ["low_premium_signal", "too_plain", "dating_warmth_missing"],
    recommendedCategories: ["shirt", "chinos", "formal_shoes", "watch", "belt"],
    searchQuery: "cream linen shirt beige chinos loafers minimal watch soft luxury",
    budgetMax: 8000,
  },
  {
    id: "first-date-essentials",
    label: "First Date Essentials",
    celebrity: "First Impression Ready",
    imageSrc: "/celebs/first-date-essentials.jpg",
    avatarLabel: "FD",
    avatarGradient: "from-rose-200 via-pink-300 to-red-400",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ first date style tips",
    sourceUrl: "https://www.gq.com/story/first-date-outfit-guide-2026",
    summary:
      "Navy polo, dark jeans, clean white sneakers, and a minimal watch — confident without trying too hard.",
    styleDirection: "dating_warm",
    auraLeakTags: ["dating_warmth_missing", "too_plain", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "jeans", "sneakers", "watch", "perfume"],
    searchQuery: "navy polo dark jeans white sneakers dating casual clean",
    budgetMax: 5000,
  },
  {
    id: "interview-power-look",
    label: "Interview Power Look",
    celebrity: "Interview Ready",
    imageSrc: "/celebs/interview-power-look.jpg",
    avatarLabel: "IL",
    avatarGradient: "from-blue-300 via-indigo-400 to-slate-500",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ interview dressing guide",
    sourceUrl: "https://www.gq.com/story/job-interview-outfit-guide-2026",
    summary:
      "Light blue Oxford, grey trousers, brown leather shoes, and a clean belt — you walk in looking like you already got the job.",
    styleDirection: "corporate_sharp",
    auraLeakTags: ["professional_mismatch", "low_premium_signal", "outfit_inconsistency"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "belt", "watch"],
    searchQuery: "light blue oxford grey trousers brown formal shoes interview",
    budgetMax: 8000,
  },
  {
    id: "weekend-brunch-casual",
    label: "Weekend Brunch Casual",
    celebrity: "Weekend Easy",
    imageSrc: "/celebs/weekend-brunch-casual.jpg",
    avatarLabel: "WB",
    avatarGradient: "from-yellow-200 via-amber-300 to-orange-400",
    region: "Global",
    trendDateLabel: "June 2026",
    sourceLabel: "GQ weekend style picks",
    sourceUrl: "https://www.gq.com/story/weekend-brunch-outfit-ideas-2026",
    summary:
      "Beige tee, olive chinos, white canvas sneakers, and aviator sunglasses — laid-back but put together.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "chinos", "sneakers", "sunglasses", "belt"],
    searchQuery: "beige tshirt olive chinos white canvas sneakers aviator casual",
    budgetMax: 4000,
  },
  {
    id: "night-out-urban",
    label: "Night Out Urban Edge",
    celebrity: "After Dark Edit",
    imageSrc: "/celebs/night-out-urban.jpg",
    avatarLabel: "NO",
    avatarGradient: "from-purple-400 via-violet-500 to-indigo-600",
    region: "Global",
    trendDateLabel: "June 2026",
    sourceLabel: "GQ nightlife style guide",
    sourceUrl: "https://www.gq.com/story/night-out-outfit-men-2026",
    summary:
      "Black casual shirt, black slim jeans, black sneakers, and a silver chain — monochrome power for the night.",
    styleDirection: "urban_aspirational",
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency", "too_plain"],
    recommendedCategories: ["shirt", "jeans", "sneakers", "jewellery", "perfume"],
    searchQuery: "black casual shirt black slim jeans black sneakers silver chain night",
    budgetMax: 6000,
  },
  {
    id: "diwali-fusion",
    label: "Diwali Fusion Look",
    celebrity: "Festival Ready",
    imageSrc: "/celebs/diwali-fusion.jpg",
    avatarLabel: "DF",
    avatarGradient: "from-orange-300 via-amber-400 to-yellow-500",
    region: "India",
    trendDateLabel: "October 2026",
    sourceLabel: "Vogue India festive dressing guide",
    sourceUrl: "https://www.vogue.in/content/diwali-outfit-ideas-men-2026",
    summary:
      "White kurta, Nehru jacket, clean mojari, and a minimal watch — modern ethnic that commands respect at every family gathering.",
    styleDirection: "ethnic_clean",
    auraLeakTags: ["outfit_inconsistency", "low_premium_signal", "color_mismatch"],
    recommendedCategories: ["kurta", "jacket", "formal_shoes", "watch", "belt"],
    searchQuery: "white kurta nehru jacket mojari ethnic clean festival wedding",
    budgetMax: 8000,
  },
  {
    id: "instagram-photoshoot",
    label: "Instagram Photo Ready",
    celebrity: "Content Creator Kit",
    imageSrc: "/celebs/instagram-photoshoot.jpg",
    avatarLabel: "IG",
    avatarGradient: "from-pink-300 via-fuchsia-400 to-purple-500",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ social media style tips",
    sourceUrl: "https://www.gq.com/story/instagram-photo-style-guide-2026",
    summary:
      "Black tee, beige overshirt, dark jeans, white sneakers, and a ring light — the content creator's wardrobe starter pack.",
    styleDirection: "creator_bold",
    auraLeakTags: ["weak_lighting", "busy_background", "too_plain"],
    recommendedCategories: ["tshirt", "overshirt", "jeans", "sneakers", "photo_accessory"],
    searchQuery: "black tshirt beige overshirt dark jeans white sneakers ring light",
    budgetMax: 6000,
  },
  {
    id: "summer-minimal",
    label: "Summer Minimal Cool",
    celebrity: "Heat Wave Ready",
    imageSrc: "/celebs/summer-minimal.jpg",
    avatarLabel: "SM",
    avatarGradient: "from-cyan-200 via-sky-300 to-blue-400",
    region: "India",
    trendDateLabel: "May 2026",
    sourceLabel: "Vogue India summer style guide",
    sourceUrl: "https://www.vogue.in/content/summer-wardrobe-essentials-men-2026",
    summary:
      "White linen shirt, beige chinos, canvas sneakers, and wayfarer sunglasses — stay cool without sacrificing style.",
    styleDirection: "premium_minimal",
    auraLeakTags: ["too_plain", "low_premium_signal", "color_mismatch"],
    recommendedCategories: ["shirt", "chinos", "sneakers", "sunglasses", "perfume"],
    searchQuery: "white linen shirt beige chinos canvas sneakers wayfarer summer",
    budgetMax: 5000,
  },
  {
    id: "layered-winter-smart",
    label: "Winter Layering Done Right",
    celebrity: "Cold Weather Sharp",
    imageSrc: "/celebs/layered-winter-smart.jpg",
    avatarLabel: "WL",
    avatarGradient: "from-slate-300 via-gray-400 to-zinc-500",
    region: "India",
    trendDateLabel: "December 2026",
    sourceLabel: "GQ India winter layering guide",
    sourceUrl: "https://www.gqindia.com/content/winter-layering-style-guide-2026",
    summary:
      "Grey hoodie under a black bomber jacket, dark jeans, and black sneakers — structured winter layering that looks intentional.",
    styleDirection: "street_smart",
    auraLeakTags: ["outfit_inconsistency", "too_plain", "low_premium_signal"],
    recommendedCategories: ["hoodie", "jacket", "jeans", "sneakers", "watch"],
    searchQuery: "grey hoodie black bomber jacket dark jeans black sneakers winter layering",
    budgetMax: 7000,
  },
  {
    id: "budget-glow-up",
    label: "Budget Glow-Up Starter",
    celebrity: "Under 3K Makeover",
    imageSrc: "/celebs/budget-glow-up.jpg",
    avatarLabel: "BG",
    avatarGradient: "from-emerald-200 via-green-300 to-teal-400",
    region: "India",
    trendDateLabel: "July 2026",
    sourceLabel: "AuraCheck budget style guide",
    sourceUrl: "https://fixmyaura.shop/wardrobe",
    summary:
      "White tee, dark jeans, white sneakers, and a grooming kit — the highest-impact wardrobe reset for under ₹3,000.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "weak_clarity"],
    recommendedCategories: ["tshirt", "jeans", "sneakers", "grooming", "belt"],
    searchQuery: "white tshirt dark jeans white sneakers grooming kit budget basic",
    budgetMax: 3000,
  },
  {
    id: "photo-upgrade-kit",
    label: "Photo Quality Upgrade Kit",
    celebrity: "Better Photos Instantly",
    imageSrc: "/celebs/photo-upgrade-kit.jpg",
    avatarLabel: "PQ",
    avatarGradient: "from-violet-200 via-purple-300 to-fuchsia-400",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "AuraCheck photo improvement guide",
    sourceUrl: "https://fixmyaura.shop/wardrobe",
    summary:
      "Ring light, phone tripod, lens cloth, neutral background cloth, and a warm lamp — fix your photos before fixing your wardrobe.",
    styleDirection: "clean_basic",
    auraLeakTags: ["weak_lighting", "busy_background", "weak_clarity", "weak_framing"],
    recommendedCategories: ["photo_accessory", "background_item", "grooming"],
    searchQuery: "ring light phone tripod lens cloth background cloth warm lamp photo",
    budgetMax: 3000,
  },
  {
    id: "premium-date-dinner",
    label: "Premium Dinner Date",
    celebrity: "Fine Dining Ready",
    imageSrc: "/celebs/premium-date-dinner.jpg",
    avatarLabel: "PD",
    avatarGradient: "from-amber-300 via-yellow-400 to-orange-500",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ dinner date style guide",
    sourceUrl: "https://www.gq.com/story/dinner-date-outfit-guide-2026",
    summary:
      "White Oxford shirt, navy chinos, brown loafers, minimal watch, and a fresh fragrance — classic and effortlessly put together.",
    styleDirection: "dating_warm",
    auraLeakTags: ["dating_warmth_missing", "low_premium_signal", "professional_mismatch"],
    recommendedCategories: ["shirt", "chinos", "formal_shoes", "watch", "perfume"],
    searchQuery: "white oxford navy chinos brown loafers watch perfume dinner date",
    budgetMax: 10000,
  },
];
