import type { AuraLeakTag, AuraStyleDirection, WardrobeCategory } from "@/types/commerce";

export interface CelebrityTrendPreset {
  id: string;
  label: string;
  celebrity: string;
  imageSrc: string;
  avatarLabel: string;
  avatarGradient: string;
  region: "India" | "Global";
  trendDateLabel: string;
  sourceLabel: string;
  sourceUrl: string;
  summary: string;
  styleDirection: AuraStyleDirection;
  auraLeakTags: AuraLeakTag[];
  recommendedCategories: WardrobeCategory[];
  searchQuery: string;
  budgetMax?: number;
}

export const CELEBRITY_TREND_PRESETS: CelebrityTrendPreset[] = [
  {
    id: "oscars-wide-leg-tailoring",
    label: "Relaxed Red Carpet Tailoring",
    celebrity: "Red Carpet Approved",
    imageSrc: "/celebs/oscars-wide-leg-tailoring.jpg",
    avatarLabel: "MB",
    avatarGradient: "from-slate-200 via-zinc-300 to-amber-200",
    region: "Global",
    trendDateLabel: "March 2026",
    sourceLabel: "GQ Oscars 2026 best-dressed",
    sourceUrl: "https://www.gq.com/story/oscars-2026-best-dressed-celebrities-red-carpet-menswear",
    summary:
      "Wide-leg tailoring and cleaner formal lines are the smarter 2026 move versus stiff, old-school slim formalwear.",
    styleDirection: "understated_confident",
    auraLeakTags: ["professional_mismatch", "low_premium_signal", "too_plain"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "watch", "jacket"],
    searchQuery: "wide leg trousers relaxed tailoring formal shoes understated confident",
    budgetMax: 15000,
  },
  {
    id: "timothee-clean-minimal",
    label: "Effortless Clean Basics",
    celebrity: "Off-Duty Minimalist",
    imageSrc: "/celebs/timothee-clean-minimal.jpg",
    avatarLabel: "TC",
    avatarGradient: "from-stone-200 via-neutral-300 to-gray-400",
    region: "Global",
    trendDateLabel: "May 2026",
    sourceLabel: "GQ relaxed tailoring trend",
    sourceUrl: "https://www.gq.com/story/relaxed-tailoring-trend-2026",
    summary:
      "Oversized tees, raw-hem trousers, and layered lightweight outerwear — the art of looking undone without looking unkempt.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "trousers", "sneakers", "jacket", "hoodie"],
    searchQuery: "oversized tshirt relaxed trousers clean basics minimalist menswear",
    budgetMax: 6000,
  },
  {
    id: "hrithik-resort-luxe",
    label: "Soft Luxury Resort Wear",
    celebrity: "Resort-Ready Edit",
    imageSrc: "/celebs/hrithik-dating-warm.jpg",
    avatarLabel: "HR",
    avatarGradient: "from-amber-200 via-orange-300 to-rose-400",
    region: "India",
    trendDateLabel: "February 2026",
    sourceLabel: "Vogue India resort collection trends",
    sourceUrl: "https://www.vogue.in/content/resort-collection-trends-2026",
    summary:
      "Linen shirts, tailored shorts, and premium accessories — resort wear that transitions from brunch to evening effortlessly.",
    styleDirection: "soft_luxury",
    auraLeakTags: ["low_premium_signal", "color_mismatch", "dating_warmth_missing"],
    recommendedCategories: ["shirt", "trousers", "sunglasses", "watch", "perfume"],
    searchQuery: "linen shirt tailored shorts resort wear pastel luxury summer",
    budgetMax: 10000,
  },
  {
    id: "ranveer-creator-bold",
    label: "Bold Creator Edge",
    celebrity: "Bold & Unapologetic",
    imageSrc: "/celebs/ranveer-creator-bold.jpg",
    avatarLabel: "RS",
    avatarGradient: "from-yellow-300 via-orange-400 to-red-500",
    region: "India",
    trendDateLabel: "April 2026",
    sourceLabel: "GQ India bold print styling",
    sourceUrl: "https://www.gqindia.com/content/ranveer-singh-bold-print-fashion-trend",
    summary:
      "Bold prints, clashing textures, and fearless colour-blocking — for when you want your outfit to start the conversation.",
    styleDirection: "creator_bold",
    auraLeakTags: ["over_flex", "color_mismatch", "creator_energy_missing"],
    recommendedCategories: ["jacket", "tshirt", "sneakers", "sunglasses", "watch"],
    searchQuery: "printed shirt bold colors statement jacket sneakers street style",
    budgetMax: 10000,
  },
  {
    id: "ibrahim-college-casual",
    label: "Campus Cool Refresh",
    celebrity: "Campus Street Energy",
    imageSrc: "/celebs/ibrahim-college-casual.jpg",
    avatarLabel: "IA",
    avatarGradient: "from-blue-200 via-indigo-300 to-slate-400",
    region: "India",
    trendDateLabel: "March 2026",
    sourceLabel: "Vogue India college street style",
    sourceUrl: "https://www.vogue.in/content/college-street-style-trends-2026",
    summary:
      "Clean denim, retro sneakers, boxy tees, and bomber jackets — the freshest campus look that says effortless without trying.",
    styleDirection: "college_casual",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["jeans", "tshirt", "sneakers", "jacket", "hoodie"],
    searchQuery: "clean denim retro sneakers bomber jacket campus streetwear",
    budgetMax: 7000,
  },
  {
    id: "shahid-corporate-sharp",
    label: "Boardroom Sharp Edit",
    celebrity: "Power Dressing Edit",
    imageSrc: "/celebs/shahid-corporate-sharp.jpg",
    avatarLabel: "SK",
    avatarGradient: "from-gray-300 via-zinc-400 to-blue-600",
    region: "India",
    trendDateLabel: "January 2026",
    sourceLabel: "GQ India sharp suiting trend",
    sourceUrl: "https://www.gqindia.com/content/sharp-suiting-trends-workwear-2026",
    summary:
      "Precise tailoring, slim-lapel blazers, crisp shirts, and minimal accessories — the uniform of someone who means business.",
    styleDirection: "corporate_sharp",
    auraLeakTags: ["professional_mismatch", "low_premium_signal", "color_mismatch"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "watch", "belt"],
    searchQuery: "slim blazer dress shirt tailored trousers formal shoes corporate",
    budgetMax: 12000,
  },
  {
    id: "hrithik-dating-warm",
    label: "Date Night Warmth",
    celebrity: "Warm & Approachable",
    imageSrc: "/celebs/hrithik-dating-warm.jpg",
    avatarLabel: "HR",
    avatarGradient: "from-amber-200 via-orange-300 to-rose-400",
    region: "India",
    trendDateLabel: "February 2026",
    sourceLabel: "Vogue India date night style guide",
    sourceUrl: "https://www.vogue.in/content/date-night-outfit-ideas-men-2026",
    summary:
      "Warm earth tones, textured knits, clean denim, and leather boots — approachable, masculine, and visually interesting without overdoing it.",
    styleDirection: "dating_warm",
    auraLeakTags: ["dating_warmth_missing", "too_plain", "color_mismatch"],
    recommendedCategories: ["shirt", "jeans", "watch", "jacket", "sneakers"],
    searchQuery: "earth tones knitwear leather boots warm date night outfit",
    budgetMax: 9000,
  },
  {
    id: "siddharth-ethnic-clean",
    label: "Modern Ethnic Clean",
    celebrity: "Festive Season Edit",
    imageSrc: "/celebs/siddharth-ethnic-clean.jpg",
    avatarLabel: "SM",
    avatarGradient: "from-emerald-200 via-teal-300 to-cyan-400",
    region: "India",
    trendDateLabel: "May 2026",
    sourceLabel: "Vogue India wedding guest style",
    sourceUrl: "https://www.vogue.in/content/wedding-guest-outfit-ideas-men-2026",
    summary:
      "Clean-lined kurtas, churidars with a modern drape, and minimal mojari — ethnic wear stripped of clutter, built for the contemporary man.",
    styleDirection: "ethnic_clean",
    auraLeakTags: ["professional_mismatch", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["kurta", "trousers", "watch", "belt", "sneakers"],
    searchQuery: "clean kurta churidar ethnic wear minimal wedding guest",
    budgetMax: 7000,
  },
  {
    id: "virat-gym-casual",
    label: "Gym-to-Street Athleisure",
    celebrity: "Athlete Off-Duty",
    imageSrc: "/celebs/virat-gym-casual.jpg",
    avatarLabel: "VK",
    avatarGradient: "from-gray-600 via-zinc-500 to-slate-400",
    region: "India",
    trendDateLabel: "June 2026",
    sourceLabel: "GQ India athleisure style guide",
    sourceUrl: "https://www.gqindia.com/content/best-athleisure-style-men-2026",
    summary:
      "Performance fabrics that look sharp off the field: joggers with structure, tech-fabric tees, sleek trainers, and minimal accessories.",
    styleDirection: "gym_casual",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["tshirt", "sneakers", "hoodie", "jacket", "watch"],
    searchQuery: "tech joggers performance tee athleisure sneakers gym street style",
    budgetMax: 6000,
  },
  {
    id: "kartik-mumbai-street",
    label: "Mumbai Street Luxe",
    celebrity: "Mumbai Street Energy",
    imageSrc: "/celebs/kartik-mumbai-street.jpg",
    avatarLabel: "KA",
    avatarGradient: "from-sky-200 via-blue-300 to-indigo-400",
    region: "India",
    trendDateLabel: "April 2026",
    sourceLabel: "GQ India street style picks",
    sourceUrl: "https://www.gqindia.com/content/street-style-trends-mumbai-2026",
    summary:
      "Lightweight bombers, distressed denim, graphic tees, and chunky sneakers — the Mumbai street look that filters from Versace to the high street.",
    styleDirection: "urban_aspirational",
    auraLeakTags: ["too_plain", "creator_energy_missing", "outfit_inconsistency"],
    recommendedCategories: ["jacket", "jeans", "tshirt", "sneakers", "sunglasses"],
    searchQuery: "lightweight bomber distressed denim graphic tee chunky sneakers",
    budgetMax: 8000,
  },
  {
    id: "harry-quiet-luxury",
    label: "Quiet Luxury Travel",
    celebrity: "Quiet Luxury Edit",
    imageSrc: "/celebs/harry-quiet-luxury.jpg",
    avatarLabel: "HS",
    avatarGradient: "from-peach-200 via-coral-300 to-rose-400",
    region: "Global",
    trendDateLabel: "March 2026",
    sourceLabel: "Vogue quiet luxury trend report",
    sourceUrl: "https://www.vogue.com/article/quiet-luxury-travel-wardrobe-2026",
    summary:
      "Understated investment pieces: unlined blazers, fine-gauge knits, tailored wide trousers, and leather accessories that whisper status.",
    styleDirection: "premium_minimal",
    auraLeakTags: ["low_premium_signal", "too_plain", "professional_mismatch"],
    recommendedCategories: ["jacket", "tshirt", "trousers", "watch", "belt"],
    searchQuery: "unlined blazer fine knit cashmere wide trousers quiet luxury",
    budgetMax: 15000,
  },
  {
    id: "dev-effortless-date",
    label: "Effortless Date Night",
    celebrity: "Effortless Charisma",
    imageSrc: "/celebs/dev-effortless-date.jpg",
    avatarLabel: "DP",
    avatarGradient: "from-olive-200 via-amber-300 to-brown-400",
    region: "Global",
    trendDateLabel: "May 2026",
    sourceLabel: "GQ date night outfit guide",
    sourceUrl: "https://www.gq.com/story/date-night-outfits-men-2026",
    summary:
      "Smart without stiffness: a great overshirt, dark jeans, clean white sneakers, and a leather jacket — the uniform of quiet charisma.",
    styleDirection: "understated_confident",
    auraLeakTags: ["dating_warmth_missing", "outfit_inconsistency", "too_plain"],
    recommendedCategories: ["overshirt", "jeans", "sneakers", "jacket", "watch"],
    searchQuery: "overshirt dark wash jeans white sneakers leather jacket date night",
    budgetMax: 10000,
  },
  {
    id: "global-street-tech",
    label: "Tokyo Street Tech",
    celebrity: "Global Street Style",
    imageSrc: "/celebs/global-street-tech.jpg",
    avatarLabel: "GS",
    avatarGradient: "from-lime-200 via-green-300 to-cyan-400",
    region: "Global",
    trendDateLabel: "June 2026",
    sourceLabel: "Hypebeast streetwear roundup",
    sourceUrl: "https://hypebeast.com/2026/streetwear-trends-2026",
    summary:
      "Tech fabrics, cargo silhouettes, neons accents, and futuristic sneakers — streetwear that nods to Harajuku while staying wearable.",
    styleDirection: "street_smart",
    auraLeakTags: ["creator_energy_missing", "too_plain", "outfit_inconsistency"],
    recommendedCategories: ["jacket", "tshirt", "sneakers", "hoodie", "sunglasses"],
    searchQuery: "tech cargo pants graphic hoodie futuristic sneakers streetwear harajuku",
    budgetMax: 10000,
  },
  {
    id: "south-soft-luxury",
    label: "South Indian Soft Luxury",
    celebrity: "Southern Sophistication",
    imageSrc: "/celebs/south-soft-luxury.jpg",
    avatarLabel: "DQ",
    avatarGradient: "from-amber-100 via-yellow-200 to-orange-300",
    region: "India",
    trendDateLabel: "June 2026",
    sourceLabel: "Vogue India south style guide",
    sourceUrl: "https://www.vogue.in/content/south-indian-fashion-trends-2026",
    summary:
      "Cream linen, clean chinos, leather loafers, and minimal accessories — the understated South Indian gentleman's uniform.",
    styleDirection: "soft_luxury",
    auraLeakTags: ["low_premium_signal", "too_plain", "dating_warmth_missing"],
    recommendedCategories: ["shirt", "chinos", "formal_shoes", "watch", "belt"],
    searchQuery: "cream linen shirt beige chinos loafers minimal watch soft luxury",
    budgetMax: 8000,
  },
  {
    id: "first-date-essentials",
    label: "First Date Essentials",
    celebrity: "First Impression Ready",
    imageSrc: "/celebs/first-date-essentials.jpg",
    avatarLabel: "FD",
    avatarGradient: "from-rose-200 via-pink-300 to-red-400",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ first date style tips",
    sourceUrl: "https://www.gq.com/story/first-date-outfit-guide-2026",
    summary:
      "Navy polo, dark jeans, clean white sneakers, and a minimal watch — confident without trying too hard.",
    styleDirection: "dating_warm",
    auraLeakTags: ["dating_warmth_missing", "too_plain", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "jeans", "sneakers", "watch", "perfume"],
    searchQuery: "navy polo dark jeans white sneakers dating casual clean",
    budgetMax: 5000,
  },
  {
    id: "interview-power-look",
    label: "Interview Power Look",
    celebrity: "Interview Ready",
    imageSrc: "/celebs/interview-power-look.jpg",
    avatarLabel: "IL",
    avatarGradient: "from-blue-300 via-indigo-400 to-slate-500",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ interview dressing guide",
    sourceUrl: "https://www.gq.com/story/job-interview-outfit-guide-2026",
    summary:
      "Light blue Oxford, grey trousers, brown leather shoes, and a clean belt — you walk in looking like you already got the job.",
    styleDirection: "corporate_sharp",
    auraLeakTags: ["professional_mismatch", "low_premium_signal", "outfit_inconsistency"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "belt", "watch"],
    searchQuery: "light blue oxford grey trousers brown formal shoes interview",
    budgetMax: 8000,
  },
  {
    id: "weekend-brunch-casual",
    label: "Weekend Brunch Casual",
    celebrity: "Weekend Easy",
    imageSrc: "/celebs/weekend-brunch-casual.jpg",
    avatarLabel: "WB",
    avatarGradient: "from-yellow-200 via-amber-300 to-orange-400",
    region: "Global",
    trendDateLabel: "June 2026",
    sourceLabel: "GQ weekend style picks",
    sourceUrl: "https://www.gq.com/story/weekend-brunch-outfit-ideas-2026",
    summary:
      "Beige tee, olive chinos, white canvas sneakers, and aviator sunglasses — laid-back but put together.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "chinos", "sneakers", "sunglasses", "belt"],
    searchQuery: "beige tshirt olive chinos white canvas sneakers aviator casual",
    budgetMax: 4000,
  },
  {
    id: "night-out-urban",
    label: "Night Out Urban Edge",
    celebrity: "After Dark Edit",
    imageSrc: "/celebs/night-out-urban.jpg",
    avatarLabel: "NO",
    avatarGradient: "from-purple-400 via-violet-500 to-indigo-600",
    region: "Global",
    trendDateLabel: "June 2026",
    sourceLabel: "GQ nightlife style guide",
    sourceUrl: "https://www.gq.com/story/night-out-outfit-men-2026",
    summary:
      "Black casual shirt, black slim jeans, black sneakers, and a silver chain — monochrome power for the night.",
    styleDirection: "urban_aspirational",
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency", "too_plain"],
    recommendedCategories: ["shirt", "jeans", "sneakers", "jewellery", "perfume"],
    searchQuery: "black casual shirt black slim jeans black sneakers silver chain night",
    budgetMax: 6000,
  },
  {
    id: "diwali-fusion",
    label: "Diwali Fusion Look",
    celebrity: "Festival Ready",
    imageSrc: "/celebs/diwali-fusion.jpg",
    avatarLabel: "DF",
    avatarGradient: "from-orange-300 via-amber-400 to-yellow-500",
    region: "India",
    trendDateLabel: "October 2026",
    sourceLabel: "Vogue India festive dressing guide",
    sourceUrl: "https://www.vogue.in/content/diwali-outfit-ideas-men-2026",
    summary:
      "White kurta, Nehru jacket, clean mojari, and a minimal watch — modern ethnic that commands respect at every family gathering.",
    styleDirection: "ethnic_clean",
    auraLeakTags: ["outfit_inconsistency", "low_premium_signal", "color_mismatch"],
    recommendedCategories: ["kurta", "jacket", "formal_shoes", "watch", "belt"],
    searchQuery: "white kurta nehru jacket mojari ethnic clean festival wedding",
    budgetMax: 8000,
  },
  {
    id: "instagram-photoshoot",
    label: "Instagram Photo Ready",
    celebrity: "Content Creator Kit",
    imageSrc: "/celebs/instagram-photoshoot.jpg",
    avatarLabel: "IG",
    avatarGradient: "from-pink-300 via-fuchsia-400 to-purple-500",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ social media style tips",
    sourceUrl: "https://www.gq.com/story/instagram-photo-style-guide-2026",
    summary:
      "Black tee, beige overshirt, dark jeans, white sneakers, and a ring light — the content creator's wardrobe starter pack.",
    styleDirection: "creator_bold",
    auraLeakTags: ["weak_lighting", "busy_background", "too_plain"],
    recommendedCategories: ["tshirt", "overshirt", "jeans", "sneakers", "photo_accessory"],
    searchQuery: "black tshirt beige overshirt dark jeans white sneakers ring light",
    budgetMax: 6000,
  },
  {
    id: "summer-minimal",
    label: "Summer Minimal Cool",
    celebrity: "Heat Wave Ready",
    imageSrc: "/celebs/summer-minimal.jpg",
    avatarLabel: "SM",
    avatarGradient: "from-cyan-200 via-sky-300 to-blue-400",
    region: "India",
    trendDateLabel: "May 2026",
    sourceLabel: "Vogue India summer style guide",
    sourceUrl: "https://www.vogue.in/content/summer-wardrobe-essentials-men-2026",
    summary:
      "White linen shirt, beige chinos, canvas sneakers, and wayfarer sunglasses — stay cool without sacrificing style.",
    styleDirection: "premium_minimal",
    auraLeakTags: ["too_plain", "low_premium_signal", "color_mismatch"],
    recommendedCategories: ["shirt", "chinos", "sneakers", "sunglasses", "perfume"],
    searchQuery: "white linen shirt beige chinos canvas sneakers wayfarer summer",
    budgetMax: 5000,
  },
  {
    id: "layered-winter-smart",
    label: "Winter Layering Done Right",
    celebrity: "Cold Weather Sharp",
    imageSrc: "/celebs/layered-winter-smart.jpg",
    avatarLabel: "WL",
    avatarGradient: "from-slate-300 via-gray-400 to-zinc-500",
    region: "India",
    trendDateLabel: "December 2026",
    sourceLabel: "GQ India winter layering guide",
    sourceUrl: "https://www.gqindia.com/content/winter-layering-style-guide-2026",
    summary:
      "Grey hoodie under a black bomber jacket, dark jeans, and black sneakers — structured winter layering that looks intentional.",
    styleDirection: "street_smart",
    auraLeakTags: ["outfit_inconsistency", "too_plain", "low_premium_signal"],
    recommendedCategories: ["hoodie", "jacket", "jeans", "sneakers", "watch"],
    searchQuery: "grey hoodie black bomber jacket dark jeans black sneakers winter layering",
    budgetMax: 7000,
  },
  {
    id: "budget-glow-up",
    label: "Budget Glow-Up Starter",
    celebrity: "Under 3K Makeover",
    imageSrc: "/celebs/budget-glow-up.jpg",
    avatarLabel: "BG",
    avatarGradient: "from-emerald-200 via-green-300 to-teal-400",
    region: "India",
    trendDateLabel: "July 2026",
    sourceLabel: "AuraCheck budget style guide",
    sourceUrl: "https://fixmyaura.shop/wardrobe",
    summary:
      "White tee, dark jeans, white sneakers, and a grooming kit — the highest-impact wardrobe reset for under ₹3,000.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "weak_clarity"],
    recommendedCategories: ["tshirt", "jeans", "sneakers", "grooming", "belt"],
    searchQuery: "white tshirt dark jeans white sneakers grooming kit budget basic",
    budgetMax: 3000,
  },
  {
    id: "photo-upgrade-kit",
    label: "Photo Quality Upgrade Kit",
    celebrity: "Better Photos Instantly",
    imageSrc: "/celebs/photo-upgrade-kit.jpg",
    avatarLabel: "PQ",
    avatarGradient: "from-violet-200 via-purple-300 to-fuchsia-400",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "AuraCheck photo improvement guide",
    sourceUrl: "https://fixmyaura.shop/wardrobe",
    summary:
      "Ring light, phone tripod, lens cloth, neutral background cloth, and a warm lamp — fix your photos before fixing your wardrobe.",
    styleDirection: "clean_basic",
    auraLeakTags: ["weak_lighting", "busy_background", "weak_clarity", "weak_framing"],
    recommendedCategories: ["photo_accessory", "background_item", "grooming"],
    searchQuery: "ring light phone tripod lens cloth background cloth warm lamp photo",
    budgetMax: 3000,
  },
  {
    id: "premium-date-dinner",
    label: "Premium Dinner Date",
    celebrity: "Fine Dining Ready",
    imageSrc: "/celebs/premium-date-dinner.jpg",
    avatarLabel: "PD",
    avatarGradient: "from-amber-300 via-yellow-400 to-orange-500",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ dinner date style guide",
    sourceUrl: "https://www.gq.com/story/dinner-date-outfit-guide-2026",
    summary:
      "White Oxford shirt, navy chinos, brown loafers, minimal watch, and a fresh fragrance — classic and effortlessly put together.",
    styleDirection: "dating_warm",
    auraLeakTags: ["dating_warmth_missing", "low_premium_signal", "professional_mismatch"],
    recommendedCategories: ["shirt", "chinos", "formal_shoes", "watch", "perfume"],
    searchQuery: "white oxford navy chinos brown loafers watch perfume dinner date",
    budgetMax: 10000,
  },
  {
    id: "sporty-luxe-athleisure",
    label: "Sporty Luxe Athleisure",
    celebrity: "Athleisure Elevated",
    imageSrc: "/celebs/ananya-sporty-luxe.jpg",
    avatarLabel: "SL",
    avatarGradient: "from-teal-200 via-cyan-300 to-emerald-400",
    region: "India",
    trendDateLabel: "June 2026",
    sourceLabel: "Vogue India athleisure trends",
    sourceUrl: "https://www.vogue.in/content/athleisure-fashion-trends-2026",
    summary:
      "Tech-fabric joggers, fitted polo, clean white sneakers, and a sports watch — athletic polish without the gym-bro energy.",
    styleDirection: "gym_casual",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["tshirt", "sneakers", "watch", "hoodie", "sunglasses"],
    searchQuery: "polo tshirt joggers white sneakers sports watch athleisure",
    budgetMax: 5000,
  },
  {
    id: "soft-power-dressing",
    label: "Soft Power Dressing",
    celebrity: "Quiet Authority",
    imageSrc: "/celebs/deepika-soft-luxury.jpg",
    avatarLabel: "SP",
    avatarGradient: "from-rose-200 via-pink-300 to-fuchsia-400",
    region: "India",
    trendDateLabel: "May 2026",
    sourceLabel: "GQ India soft power trend",
    sourceUrl: "https://www.gqindia.com/content/soft-power-dressing-2026",
    summary:
      "Cream linen shirt, tailored trousers, brown loafers, and a leather belt — authority through understatement, not volume.",
    styleDirection: "soft_luxury",
    auraLeakTags: ["low_premium_signal", "professional_mismatch", "too_plain"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "belt", "watch"],
    searchQuery: "cream linen shirt tailored trousers brown loafers leather belt",
    budgetMax: 10000,
  },
  {
    id: "track-street-transition",
    label: "Track-to-Street Flex",
    celebrity: "Sport Meets Street",
    imageSrc: "/celebs/kendall-hailey-track.jpg",
    avatarLabel: "TS",
    avatarGradient: "from-lime-200 via-green-300 to-emerald-400",
    region: "Global",
    trendDateLabel: "April 2026",
    sourceLabel: "Hypebeast track style roundup",
    sourceUrl: "https://hypebeast.com/2026/track-style-streetwear-2026",
    summary:
      "Black joggers, graphic tee, bomber jacket, and chunky sneakers — the track-to-street pipeline that never misses.",
    styleDirection: "street_smart",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "creator_energy_missing"],
    recommendedCategories: ["tshirt", "jacket", "sneakers", "hoodie", "sunglasses"],
    searchQuery: "black joggers graphic tee bomber jacket chunky sneakers street",
    budgetMax: 6000,
  },
  {
    id: "global-red-carpet",
    label: "Red Carpet Confidence",
    celebrity: "Event Night Edit",
    imageSrc: "/celebs/priyanka-soft-power.jpg",
    avatarLabel: "RC",
    avatarGradient: "from-red-200 via-rose-300 to-pink-400",
    region: "Global",
    trendDateLabel: "March 2026",
    sourceLabel: "GQ event dressing guide",
    sourceUrl: "https://www.gq.com/story/event-night-menswear-2026",
    summary:
      "Formal white shirt, black trousers, polished formal shoes, and a statement watch — red carpet energy for real life events.",
    styleDirection: "understated_confident",
    auraLeakTags: ["professional_mismatch", "low_premium_signal", "outfit_inconsistency"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "watch", "perfume"],
    searchQuery: "formal white shirt black trousers polished formal shoes watch",
    budgetMax: 15000,
  },
  {
    id: "monsoon-ready-casual",
    label: "Monsoon-Ready Casual",
    celebrity: "Rain Season Edit",
    imageSrc: "/celebs/monsoon-ready-casual.jpg",
    avatarLabel: "MR",
    avatarGradient: "from-cyan-200 via-teal-300 to-blue-400",
    region: "India",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ India monsoon dressing guide",
    sourceUrl: "https://www.gqindia.com/content/monsoon-dressing-tips-2026",
    summary:
      "Dark tshirt, black jeans, black sneakers, and a lightweight hoodie — monsoon-proof without sacrificing style.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "jeans", "sneakers", "hoodie", "belt"],
    searchQuery: "dark tshirt black jeans black sneakers lightweight hoodie monsoon",
    budgetMax: 4000,
  },
  {
    id: "airport-lounge-look",
    label: "Airport Lounge Look",
    celebrity: "Travel Smart Edit",
    imageSrc: "/celebs/airport-lounge-look.jpg",
    avatarLabel: "AL",
    avatarGradient: "from-gray-200 via-slate-300 to-zinc-400",
    region: "Global",
    trendDateLabel: "June 2026",
    sourceLabel: "GQ travel style guide",
    sourceUrl: "https://www.gq.com/story/airport-outfit-ideas-men-2026",
    summary:
      "Grey hoodie, black jeans, clean sneakers, and a minimal watch — first-class energy in economy.",
    styleDirection: "premium_minimal",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["hoodie", "jeans", "sneakers", "watch", "sunglasses"],
    searchQuery: "grey hoodie black jeans clean sneakers minimal watch travel airport",
    budgetMax: 6000,
  },
  {
    id: "cafe-hopping-casual",
    label: "Cafe Hopping Casual",
    celebrity: "Weekend Chill Edit",
    imageSrc: "/celebs/cafe-hopping-casual.jpg",
    avatarLabel: "CH",
    avatarGradient: "from-amber-100 via-orange-200 to-brown-300",
    region: "India",
    trendDateLabel: "June 2026",
    sourceLabel: "Vogue India weekend style",
    sourceUrl: "https://www.vogue.in/content/weekend-cafe-outfit-ideas-2026",
    summary:
      "Beige tshirt, navy chinos, white sneakers, and wayfarer sunglasses — the café regular who always looks effortless.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "chinos", "sneakers", "sunglasses", "watch"],
    searchQuery: "beige tshirt navy chinos white sneakers wayfarer sunglasses cafe",
    budgetMax: 4000,
  },
  {
    id: "office-friday-smart",
    label: "Office Friday Smart",
    celebrity: "Casual Friday Done Right",
    imageSrc: "/celebs/office-friday-smart.jpg",
    avatarLabel: "OF",
    avatarGradient: "from-blue-200 via-indigo-300 to-slate-400",
    region: "Global",
    trendDateLabel: "May 2026",
    sourceLabel: "GQ casual Friday style guide",
    sourceUrl: "https://www.gq.com/story/casual-friday-outfit-guide-2026",
    summary:
      "Navy polo, beige chinos, brown loafers, and a leather belt — casual enough for Friday, sharp enough for the 3pm client call.",
    styleDirection: "corporate_sharp",
    auraLeakTags: ["professional_mismatch", "too_plain", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "chinos", "formal_shoes", "belt", "watch"],
    searchQuery: "navy polo beige chinos brown loafers leather belt office casual",
    budgetMax: 6000,
  },
  {
    id: "college-fest-standout",
    label: "College Fest Standout",
    celebrity: "Campus Spotlight",
    imageSrc: "/celebs/college-fest-standout.jpg",
    avatarLabel: "CF",
    avatarGradient: "from-orange-200 via-amber-300 to-yellow-400",
    region: "India",
    trendDateLabel: "August 2026",
    sourceLabel: "Vogue India college style trends",
    sourceUrl: "https://www.vogue.in/content/college-fest-outfit-ideas-2026",
    summary:
      "Graphic tee, denim jacket, dark jeans, and high-top sneakers — the outfit that gets you remembered at the fest.",
    styleDirection: "college_casual",
    auraLeakTags: ["too_plain", "creator_energy_missing", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "jacket", "jeans", "sneakers", "sunglasses"],
    searchQuery: "graphic tee denim jacket dark jeans high top sneakers college fest",
    budgetMax: 5000,
  },
  {
    id: "wedding-guest-modern",
    label: "Modern Wedding Guest",
    celebrity: "Wedding Season Ready",
    imageSrc: "/celebs/wedding-guest-modern.jpg",
    avatarLabel: "WG",
    avatarGradient: "from-yellow-200 via-amber-300 to-orange-400",
    region: "India",
    trendDateLabel: "November 2026",
    sourceLabel: "Vogue India wedding guest style",
    sourceUrl: "https://www.vogue.in/content/wedding-guest-outfit-ideas-men-2026",
    summary:
      "Nehru jacket over white kurta, clean trousers, mojari, and a minimal watch — modern Indian wedding guest done right.",
    styleDirection: "ethnic_clean",
    auraLeakTags: ["outfit_inconsistency", "low_premium_signal", "color_mismatch"],
    recommendedCategories: ["kurta", "jacket", "trousers", "formal_shoes", "watch"],
    searchQuery: "nehru jacket white kurta trousers mojari wedding guest ethnic",
    budgetMax: 10000,
  },
  {
    id: "goa-beach-vacation",
    label: "Goa Beach Vacation",
    celebrity: "Vacation Mode On",
    imageSrc: "/celebs/goa-beach-vacation.jpg",
    avatarLabel: "GB",
    avatarGradient: "from-cyan-200 via-sky-300 to-blue-400",
    region: "India",
    trendDateLabel: "December 2026",
    sourceLabel: "GQ India vacation style guide",
    sourceUrl: "https://www.gqindia.com/content/goa-vacation-outfit-ideas-2026",
    summary:
      "White linen shirt open over a plain tee, beige shorts, canvas sneakers, and aviators — the Goa uniform that always works.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["shirt", "tshirt", "sneakers", "sunglasses", "perfume"],
    searchQuery: "white linen shirt plain tee canvas sneakers aviator sunglasses beach",
    budgetMax: 4000,
  },
  {
    id: "startup-founder-look",
    label: "Startup Founder Look",
    celebrity: "Pitch Day Ready",
    imageSrc: "/celebs/startup-founder-look.jpg",
    avatarLabel: "SF",
    avatarGradient: "from-purple-200 via-violet-300 to-indigo-400",
    region: "Global",
    trendDateLabel: "April 2026",
    sourceLabel: "GQ tech founder dressing guide",
    sourceUrl: "https://www.gq.com/story/tech-founder-style-guide-2026",
    summary:
      "Black tee, grey chinos, clean white sneakers, and a minimal watch — the Steve Jobs energy without the turtleneck.",
    styleDirection: "premium_minimal",
    auraLeakTags: ["too_plain", "professional_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "chinos", "sneakers", "watch", "belt"],
    searchQuery: "black tshirt grey chinos white sneakers minimal watch startup",
    budgetMax: 5000,
  },
  {
    id: "gym-to-coffee-run",
    label: "Gym to Coffee Run",
    celebrity: "Morning Routine Edit",
    imageSrc: "/celebs/gym-to-coffee-run.jpg",
    avatarLabel: "GC",
    avatarGradient: "from-indigo-200 via-blue-300 to-slate-400",
    region: "India",
    trendDateLabel: "June 2026",
    sourceLabel: "GQ India athleisure morning style",
    sourceUrl: "https://www.gqindia.com/content/gym-to-street-morning-style-2026",
    summary:
      "Olive tshirt, black joggers, white sneakers, and a sports watch — from the bench press to the barista without changing.",
    styleDirection: "gym_casual",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["tshirt", "sneakers", "watch", "hoodie", "sunglasses"],
    searchQuery: "olive tshirt black joggers white sneakers sports watch gym casual",
    budgetMax: 3500,
  },
  {
    id: "sunday-chill-comfort",
    label: "Sunday Chill Comfort",
    celebrity: "Zero Plans Energy",
    imageSrc: "/celebs/sunday-chill-comfort.jpg",
    avatarLabel: "SC",
    avatarGradient: "from-yellow-100 via-amber-200 to-orange-300",
    region: "India",
    trendDateLabel: "July 2026",
    sourceLabel: "Vogue India comfort style guide",
    sourceUrl: "https://www.vogue.in/content/comfortable-weekend-outfits-2026",
    summary:
      "Grey tshirt, beige shorts, white sneakers, and a baseball cap — because Sundays are for looking good doing nothing.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["tshirt", "chinos", "sneakers", "sunglasses", "watch"],
    searchQuery: "grey tshirt comfortable shorts white sneakers casual sunday",
    budgetMax: 2500,
  },
  {
    id: "rooftop-party-vibes",
    label: "Rooftop Party Vibes",
    celebrity: "Rooftop After Dark",
    imageSrc: "/celebs/rooftop-party-vibes.jpg",
    avatarLabel: "RP",
    avatarGradient: "from-indigo-400 via-purple-500 to-pink-600",
    region: "India",
    trendDateLabel: "September 2026",
    sourceLabel: "GQ India party dressing guide",
    sourceUrl: "https://www.gqindia.com/content/rooftop-party-outfit-ideas-2026",
    summary:
      "Black overshirt over white tee, dark slim jeans, black sneakers, and a silver chain — moody rooftop energy in one outfit.",
    styleDirection: "urban_aspirational",
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency", "too_plain"],
    recommendedCategories: ["overshirt", "tshirt", "jeans", "sneakers", "jewellery"],
    searchQuery: "black overshirt white tee dark jeans black sneakers silver chain party",
    budgetMax: 6000,
  },
  {
    id: "streetwear-starter-pack",
    label: "Streetwear Starter Pack",
    celebrity: "Street Entry Level",
    imageSrc: "/celebs/streetwear-starter-pack.jpg",
    avatarLabel: "SS",
    avatarGradient: "from-gray-600 via-zinc-700 to-orange-500",
    region: "Global",
    trendDateLabel: "May 2026",
    sourceLabel: "Hypebeast streetwear beginner guide",
    sourceUrl: "https://hypebeast.com/2026/streetwear-starter-guide-2026",
    summary:
      "Black hoodie, dark cargo pants, chunky sneakers, and a cap — the entry ticket to streetwear that won't break the bank.",
    styleDirection: "street_smart",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "creator_energy_missing"],
    recommendedCategories: ["hoodie", "jeans", "sneakers", "tshirt", "sunglasses"],
    searchQuery: "black hoodie cargo pants chunky sneakers streetwear basic",
    budgetMax: 5000,
  },
  {
    id: "smart-casual-friday",
    label: "Smart Casual Daily",
    celebrity: "Everyday Polish",
    imageSrc: "/celebs/smart-casual-friday.jpg",
    avatarLabel: "SC",
    avatarGradient: "from-blue-200 via-sky-300 to-indigo-400",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ smart casual guide",
    sourceUrl: "https://www.gq.com/story/smart-casual-outfit-guide-2026",
    summary:
      "Light blue Oxford, dark jeans, brown leather belt, and white sneakers — the default smart-casual that works everywhere.",
    styleDirection: "understated_confident",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["shirt", "jeans", "sneakers", "belt", "watch"],
    searchQuery: "light blue oxford dark jeans white sneakers brown belt smart casual",
    budgetMax: 5000,
  },
  {
    id: "holi-ready-casual",
    label: "Holi-Ready Casual",
    celebrity: "Festival Colors",
    imageSrc: "/celebs/holi-ready-casual.jpg",
    avatarLabel: "HC",
    avatarGradient: "from-pink-400 via-purple-500 to-orange-400",
    region: "India",
    trendDateLabel: "March 2026",
    sourceLabel: "Vogue India Holi style tips",
    sourceUrl: "https://www.vogue.in/content/holi-outfit-ideas-2026",
    summary:
      "White tee, white shorts, white sneakers — the all-white canvas that makes every color splash look intentional.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "chinos", "sneakers", "sunglasses", "grooming"],
    searchQuery: "white tshirt white shorts white sneakers holi festival casual",
    budgetMax: 2500,
  },
  {
    id: "concert-crowd-ready",
    label: "Concert Crowd Ready",
    celebrity: "Live Music Energy",
    imageSrc: "/celebs/concert-crowd-ready.jpg",
    avatarLabel: "CR",
    avatarGradient: "from-slate-700 via-indigo-800 to-rose-500",
    region: "Global",
    trendDateLabel: "August 2026",
    sourceLabel: "GQ concert outfit guide",
    sourceUrl: "https://www.gq.com/story/concert-outfit-ideas-men-2026",
    summary:
      "Black graphic tee, dark jeans, black boots, and a leather jacket — pit-ready energy with actual style.",
    styleDirection: "creator_bold",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "creator_energy_missing"],
    recommendedCategories: ["tshirt", "jeans", "jacket", "sneakers", "jewellery"],
    searchQuery: "black graphic tee dark jeans leather jacket boots concert",
    budgetMax: 7000,
  },
  {
    id: "minimalist-everyday",
    label: "Minimalist Everyday",
    celebrity: "Less Is More",
    imageSrc: "/celebs/minimalist-everyday.jpg",
    avatarLabel: "ME",
    avatarGradient: "from-gray-100 via-stone-200 to-neutral-300",
    region: "Global",
    trendDateLabel: "June 2026",
    sourceLabel: "GQ minimalist wardrobe guide",
    sourceUrl: "https://www.gq.com/story/minimalist-wardrobe-essentials-2026",
    summary:
      "Plain white tee, black jeans, white sneakers — the three-piece uniform that never fails, never ages, never tries too hard.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "low_premium_signal", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "jeans", "sneakers", "watch", "belt"],
    searchQuery: "plain white tshirt black jeans white sneakers minimalist basic",
    budgetMax: 3000,
  },
  {
    id: "second-date-upgrade",
    label: "Second Date Upgrade",
    celebrity: "Getting Serious Edit",
    imageSrc: "/celebs/second-date-upgrade.jpg",
    avatarLabel: "SD",
    avatarGradient: "from-rose-200 via-red-300 to-pink-400",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ dating style tips",
    sourceUrl: "https://www.gq.com/story/second-date-outfit-guide-2026",
    summary:
      "Navy overshirt, white tee underneath, dark chinos, brown loafers, and a fragrance — levelling up without looking like you rehearsed.",
    styleDirection: "dating_warm",
    auraLeakTags: ["dating_warmth_missing", "too_plain", "outfit_inconsistency"],
    recommendedCategories: ["overshirt", "tshirt", "chinos", "formal_shoes", "perfume"],
    searchQuery: "navy overshirt white tee dark chinos brown loafers perfume date",
    budgetMax: 7000,
  },
  {
    id: "convocation-sharp",
    label: "Convocation Sharp",
    celebrity: "Graduation Day Ready",
    imageSrc: "/celebs/convocation-sharp.jpg",
    avatarLabel: "CS",
    avatarGradient: "from-indigo-700 via-blue-800 to-slate-300",
    region: "India",
    trendDateLabel: "April 2026",
    sourceLabel: "GQ India graduation dressing guide",
    sourceUrl: "https://www.gqindia.com/content/graduation-outfit-ideas-2026",
    summary:
      "White formal shirt, navy trousers, black formal shoes, and a clean belt — under the gown, you still need to look sharp.",
    styleDirection: "corporate_sharp",
    auraLeakTags: ["professional_mismatch", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "belt", "watch"],
    searchQuery: "white formal shirt navy trousers black formal shoes belt graduation",
    budgetMax: 6000,
  },
  {
    id: "biker-edge-casual",
    label: "Biker Edge Casual",
    celebrity: "Ride & Style",
    imageSrc: "/celebs/biker-edge-casual.jpg",
    avatarLabel: "BE",
    avatarGradient: "from-stone-600 via-brown-700 to-amber-800",
    region: "India",
    trendDateLabel: "September 2026",
    sourceLabel: "GQ India biker style guide",
    sourceUrl: "https://www.gqindia.com/content/biker-style-fashion-guide-2026",
    summary:
      "Black leather jacket, dark tee, black jeans, and black boots — weekend ride energy that works off the bike too.",
    styleDirection: "street_smart",
    auraLeakTags: ["outfit_inconsistency", "too_plain", "over_flex"],
    recommendedCategories: ["jacket", "tshirt", "jeans", "sneakers", "sunglasses"],
    searchQuery: "black leather jacket dark tee black jeans boots biker casual",
    budgetMax: 8000,
  },
  {
    id: "vacation-resort-easy",
    label: "Vacation Resort Easy",
    celebrity: "Resort Checkout Ready",
    imageSrc: "/celebs/vacation-resort-easy.jpg",
    avatarLabel: "VR",
    avatarGradient: "from-sky-200 via-cyan-300 to-teal-400",
    region: "Global",
    trendDateLabel: "December 2026",
    sourceLabel: "Vogue resort dressing guide",
    sourceUrl: "https://www.vogue.com/article/resort-menswear-2026",
    summary:
      "Cream linen shirt, beige chinos, canvas sneakers, and a leather watch — resort lobby to poolside bar without a wardrobe change.",
    styleDirection: "soft_luxury",
    auraLeakTags: ["low_premium_signal", "too_plain", "color_mismatch"],
    recommendedCategories: ["shirt", "chinos", "sneakers", "watch", "sunglasses"],
    searchQuery: "cream linen shirt beige chinos canvas sneakers leather watch resort",
    budgetMax: 6000,
  },
  {
    id: "nightclub-dark-luxe",
    label: "Nightclub Dark Luxe",
    celebrity: "After Midnight Edit",
    imageSrc: "/celebs/nightclub-dark-luxe.jpg",
    avatarLabel: "NL",
    avatarGradient: "from-gray-900 via-indigo-900 to-violet-600",
    region: "Global",
    trendDateLabel: "October 2026",
    sourceLabel: "GQ nightclub style guide",
    sourceUrl: "https://www.gq.com/story/nightclub-outfit-men-2026",
    summary:
      "All-black: slim shirt, black jeans, black formal shoes, silver chain, and a dark fragrance — monochrome dominance for the dance floor.",
    styleDirection: "urban_aspirational",
    auraLeakTags: ["low_premium_signal", "outfit_inconsistency", "too_plain"],
    recommendedCategories: ["shirt", "jeans", "formal_shoes", "jewellery", "perfume"],
    searchQuery: "black shirt black jeans black formal shoes silver chain dark perfume",
    budgetMax: 8000,
  },
  {
    id: "temple-visit-ethnic",
    label: "Temple Visit Traditional",
    celebrity: "Sacred & Styled",
    imageSrc: "/celebs/temple-visit-ethnic.jpg",
    avatarLabel: "TV",
    avatarGradient: "from-orange-200 via-amber-300 to-yellow-400",
    region: "India",
    trendDateLabel: "August 2026",
    sourceLabel: "Vogue India ethnic wear guide",
    sourceUrl: "https://www.vogue.in/content/traditional-ethnic-wear-men-2026",
    summary:
      "White kurta, white trousers, clean mojari — simple, respectful, and effortlessly elegant for temple visits and puja.",
    styleDirection: "ethnic_clean",
    auraLeakTags: ["outfit_inconsistency", "color_mismatch", "low_premium_signal"],
    recommendedCategories: ["kurta", "trousers", "formal_shoes", "watch", "grooming"],
    searchQuery: "white kurta white trousers mojari ethnic clean traditional temple",
    budgetMax: 5000,
  },
  {
    id: "linkedin-headshot-ready",
    label: "LinkedIn Headshot Ready",
    celebrity: "Profile Photo Edit",
    imageSrc: "/celebs/linkedin-headshot-ready.jpg",
    avatarLabel: "LH",
    avatarGradient: "from-blue-200 via-indigo-300 to-slate-500",
    region: "Global",
    trendDateLabel: "July 2026",
    sourceLabel: "GQ professional photo guide",
    sourceUrl: "https://www.gq.com/story/linkedin-headshot-style-tips-2026",
    summary:
      "Light blue shirt, groomed look, clean background, and good lighting — the headshot upgrade that gets recruiters clicking.",
    styleDirection: "corporate_sharp",
    auraLeakTags: ["weak_lighting", "busy_background", "professional_mismatch", "weak_framing"],
    recommendedCategories: ["shirt", "grooming", "photo_accessory", "background_item", "watch"],
    searchQuery: "light blue shirt grooming kit ring light background cloth headshot",
    budgetMax: 4000,
  },
];
