import type { AuraLeakTag, AuraStyleDirection, WardrobeCategory } from "@/types/commerce";

export interface CelebrityTrendPreset {
  id: string;
  label: string;
  celebrity: string;
  imageSrc: string;
  avatarLabel: string;
  avatarGradient: string;
  region: "India" | "Global";
  trendDateLabel: string;
  sourceLabel: string;
  sourceUrl: string;
  summary: string;
  styleDirection: AuraStyleDirection;
  auraLeakTags: AuraLeakTag[];
  recommendedCategories: WardrobeCategory[];
  searchQuery: string;
  budgetMax?: number;
}

export const CELEBRITY_TREND_PRESETS: CelebrityTrendPreset[] = [
  {
    id: "ananya-sporty-luxe",
    label: "Sporty Luxe Reset",
    celebrity: "India Trending Now",
    imageSrc: "/celebs/ananya-sporty-luxe.jpg",
    avatarLabel: "AP",
    avatarGradient: "from-fuchsia-400 via-rose-300 to-orange-200",
    region: "India",
    trendDateLabel: "June 2026",
    sourceLabel: "Vogue India sportswear staples",
    sourceUrl: "https://www.vogue.in/content/11-luxury-sportswear-staples-for-your-everyday-wardrobe",
    summary:
      "Sport-coded dressing is trending hard: football jerseys, track jackets, polos, and fashion sneakers that still feel polished.",
    styleDirection: "urban_aspirational",
    auraLeakTags: ["too_plain", "low_premium_signal", "outfit_inconsistency"],
    recommendedCategories: ["jacket", "tshirt", "sneakers", "sunglasses", "watch"],
    searchQuery: "track jacket polo fashion sneakers sporty luxe",
    budgetMax: 8000,
  },
  {
    id: "priyanka-soft-power",
    label: "Soft Power Tailoring",
    celebrity: "Boardroom-Ready Edit",
    imageSrc: "/celebs/priyanka-soft-power.jpg",
    avatarLabel: "PC",
    avatarGradient: "from-amber-300 via-orange-300 to-rose-300",
    region: "India",
    trendDateLabel: "January 2026",
    sourceLabel: "Vogue India best dressed list",
    sourceUrl: "https://www.vogue.in/content/the-vogue-best-dressed-2025-list-belongs-to-those-who-dress-with-purpose",
    summary:
      "Classic tailoring with richer colours and subtle statement details is reading premium without looking try-hard.",
    styleDirection: "premium_minimal",
    auraLeakTags: ["low_premium_signal", "professional_mismatch", "color_mismatch"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "watch", "belt"],
    searchQuery: "brown blazer tailored trousers premium minimal smart luxury",
    budgetMax: 12000,
  },
  {
    id: "kendall-hailey-track",
    label: "Off-Duty Track Energy",
    celebrity: "Off-Duty Icon Energy",
    imageSrc: "/celebs/kendall-hailey-track.jpg",
    avatarLabel: "KH",
    avatarGradient: "from-sky-300 via-cyan-300 to-blue-400",
    region: "Global",
    trendDateLabel: "April 2026",
    sourceLabel: "Vogue sporty celebrity outfits",
    sourceUrl: "https://www.vogue.com/article/sporty-celebrity-outfits",
    summary:
      "Track jackets, bold track pants, throwback sneakers, and sleek sunglasses are back as a clean celebrity streetwear formula.",
    styleDirection: "street_smart",
    auraLeakTags: ["creator_energy_missing", "too_plain", "outfit_inconsistency"],
    recommendedCategories: ["jacket", "hoodie", "sneakers", "sunglasses", "tshirt"],
    searchQuery: "track pants bomber jacket retro sneakers off duty celebrity",
    budgetMax: 9000,
  },
  {
    id: "oscars-wide-leg-tailoring",
    label: "Relaxed Red Carpet Tailoring",
    celebrity: "Red Carpet Approved",
    imageSrc: "/celebs/oscars-wide-leg-tailoring.jpg",
    avatarLabel: "MB",
    avatarGradient: "from-slate-200 via-zinc-300 to-amber-200",
    region: "Global",
    trendDateLabel: "March 2026",
    sourceLabel: "GQ Oscars 2026 best-dressed",
    sourceUrl: "https://www.gq.com/story/oscars-2026-best-dressed-celebrities-red-carpet-menswear",
    summary:
      "Wide-leg tailoring and cleaner formal lines are the smarter 2026 move versus stiff, old-school slim formalwear.",
    styleDirection: "understated_confident",
    auraLeakTags: ["professional_mismatch", "low_premium_signal", "too_plain"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "watch", "jacket"],
    searchQuery: "wide leg trousers relaxed tailoring formal shoes understated confident",
    budgetMax: 15000,
  },
  {
    id: "timothee-clean-minimal",
    label: "Effortless Clean Basics",
    celebrity: "Off-Duty Minimalist",
    imageSrc: "/celebs/timothee-clean-minimal.jpg",
    avatarLabel: "TC",
    avatarGradient: "from-stone-200 via-neutral-300 to-gray-400",
    region: "Global",
    trendDateLabel: "May 2026",
    sourceLabel: "GQ relaxed tailoring trend",
    sourceUrl: "https://www.gq.com/story/relaxed-tailoring-trend-2026",
    summary:
      "Oversized tees, raw-hem trousers, and layered lightweight outerwear — the art of looking undone without looking unkempt.",
    styleDirection: "clean_basic",
    auraLeakTags: ["too_plain", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["tshirt", "trousers", "sneakers", "jacket", "hoodie"],
    searchQuery: "oversized tshirt relaxed trousers clean basics minimalist menswear",
    budgetMax: 6000,
  },
  {
    id: "deepika-soft-luxury",
    label: "Soft Luxury Resort Wear",
    celebrity: "Resort-Ready Edit",
    imageSrc: "/celebs/deepika-soft-luxury.jpg",
    avatarLabel: "DP",
    avatarGradient: "from-rose-200 via-pink-300 to-purple-400",
    region: "India",
    trendDateLabel: "February 2026",
    sourceLabel: "Vogue India resort collection trends",
    sourceUrl: "https://www.vogue.in/content/resort-collection-trends-2026",
    summary:
      "Flowing silhouettes, muted pastels, and premium natural fabrics — resort wear that transitions from brunch to evening effortlessly.",
    styleDirection: "soft_luxury",
    auraLeakTags: ["low_premium_signal", "color_mismatch", "dating_warmth_missing"],
    recommendedCategories: ["shirt", "trousers", "sunglasses", "watch", "perfume"],
    searchQuery: "linen shirt tailored shorts resort wear pastel luxury summer",
    budgetMax: 10000,
  },
  {
    id: "ranveer-creator-bold",
    label: "Bold Creator Edge",
    celebrity: "Bold & Unapologetic",
    imageSrc: "/celebs/ranveer-creator-bold.jpg",
    avatarLabel: "RS",
    avatarGradient: "from-yellow-300 via-orange-400 to-red-500",
    region: "India",
    trendDateLabel: "April 2026",
    sourceLabel: "GQ India bold print styling",
    sourceUrl: "https://www.gqindia.com/content/ranveer-singh-bold-print-fashion-trend",
    summary:
      "Bold prints, clashing textures, and fearless colour-blocking — for when you want your outfit to start the conversation.",
    styleDirection: "creator_bold",
    auraLeakTags: ["over_flex", "color_mismatch", "creator_energy_missing"],
    recommendedCategories: ["jacket", "tshirt", "sneakers", "sunglasses", "watch"],
    searchQuery: "printed shirt bold colors statement jacket sneakers street style",
    budgetMax: 10000,
  },
  {
    id: "ibrahim-college-casual",
    label: "Campus Cool Refresh",
    celebrity: "Campus Street Energy",
    imageSrc: "/celebs/ibrahim-college-casual.jpg",
    avatarLabel: "IA",
    avatarGradient: "from-blue-200 via-indigo-300 to-slate-400",
    region: "India",
    trendDateLabel: "March 2026",
    sourceLabel: "Vogue India college street style",
    sourceUrl: "https://www.vogue.in/content/college-street-style-trends-2026",
    summary:
      "Clean denim, retro sneakers, boxy tees, and bomber jackets — the freshest campus look that says effortless without trying.",
    styleDirection: "college_casual",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["jeans", "tshirt", "sneakers", "jacket", "hoodie"],
    searchQuery: "clean denim retro sneakers bomber jacket campus streetwear",
    budgetMax: 7000,
  },
  {
    id: "shahid-corporate-sharp",
    label: "Boardroom Sharp Edit",
    celebrity: "Power Dressing Edit",
    imageSrc: "/celebs/shahid-corporate-sharp.jpg",
    avatarLabel: "SK",
    avatarGradient: "from-gray-300 via-zinc-400 to-blue-600",
    region: "India",
    trendDateLabel: "January 2026",
    sourceLabel: "GQ India sharp suiting trend",
    sourceUrl: "https://www.gqindia.com/content/sharp-suiting-trends-workwear-2026",
    summary:
      "Precise tailoring, slim-lapel blazers, crisp shirts, and minimal accessories — the uniform of someone who means business.",
    styleDirection: "corporate_sharp",
    auraLeakTags: ["professional_mismatch", "low_premium_signal", "color_mismatch"],
    recommendedCategories: ["shirt", "trousers", "formal_shoes", "watch", "belt"],
    searchQuery: "slim blazer dress shirt tailored trousers formal shoes corporate",
    budgetMax: 12000,
  },
  {
    id: "hrithik-dating-warm",
    label: "Date Night Warmth",
    celebrity: "Warm & Approachable",
    imageSrc: "/celebs/hrithik-dating-warm.jpg",
    avatarLabel: "HR",
    avatarGradient: "from-amber-200 via-orange-300 to-rose-400",
    region: "India",
    trendDateLabel: "February 2026",
    sourceLabel: "Vogue India date night style guide",
    sourceUrl: "https://www.vogue.in/content/date-night-outfit-ideas-men-2026",
    summary:
      "Warm earth tones, textured knits, clean denim, and leather boots — approachable, masculine, and visually interesting without overdoing it.",
    styleDirection: "dating_warm",
    auraLeakTags: ["dating_warmth_missing", "too_plain", "color_mismatch"],
    recommendedCategories: ["shirt", "jeans", "watch", "jacket", "sneakers"],
    searchQuery: "earth tones knitwear leather boots warm date night outfit",
    budgetMax: 9000,
  },
  {
    id: "siddharth-ethnic-clean",
    label: "Modern Ethnic Clean",
    celebrity: "Festive Season Edit",
    imageSrc: "/celebs/siddharth-ethnic-clean.jpg",
    avatarLabel: "SM",
    avatarGradient: "from-emerald-200 via-teal-300 to-cyan-400",
    region: "India",
    trendDateLabel: "May 2026",
    sourceLabel: "Vogue India wedding guest style",
    sourceUrl: "https://www.vogue.in/content/wedding-guest-outfit-ideas-men-2026",
    summary:
      "Clean-lined kurtas, churidars with a modern drape, and minimal mojari — ethnic wear stripped of clutter, built for the contemporary man.",
    styleDirection: "ethnic_clean",
    auraLeakTags: ["professional_mismatch", "color_mismatch", "outfit_inconsistency"],
    recommendedCategories: ["kurta", "trousers", "watch", "belt", "sneakers"],
    searchQuery: "clean kurta churidar ethnic wear minimal wedding guest",
    budgetMax: 7000,
  },
  {
    id: "virat-gym-casual",
    label: "Gym-to-Street Athleisure",
    celebrity: "Athlete Off-Duty",
    imageSrc: "/celebs/virat-gym-casual.jpg",
    avatarLabel: "VK",
    avatarGradient: "from-gray-600 via-zinc-500 to-slate-400",
    region: "India",
    trendDateLabel: "June 2026",
    sourceLabel: "GQ India athleisure style guide",
    sourceUrl: "https://www.gqindia.com/content/best-athleisure-style-men-2026",
    summary:
      "Performance fabrics that look sharp off the field: joggers with structure, tech-fabric tees, sleek trainers, and minimal accessories.",
    styleDirection: "gym_casual",
    auraLeakTags: ["too_plain", "outfit_inconsistency", "low_premium_signal"],
    recommendedCategories: ["tshirt", "sneakers", "hoodie", "jacket", "watch"],
    searchQuery: "tech joggers performance tee athleisure sneakers gym street style",
    budgetMax: 6000,
  },
  {
    id: "kartik-mumbai-street",
    label: "Mumbai Street Luxe",
    celebrity: "Mumbai Street Energy",
    imageSrc: "/celebs/kartik-mumbai-street.jpg",
    avatarLabel: "KA",
    avatarGradient: "from-sky-200 via-blue-300 to-indigo-400",
    region: "India",
    trendDateLabel: "April 2026",
    sourceLabel: "GQ India street style picks",
    sourceUrl: "https://www.gqindia.com/content/street-style-trends-mumbai-2026",
    summary:
      "Lightweight bombers, distressed denim, graphic tees, and chunky sneakers — the Mumbai street look that filters from Versace to the high street.",
    styleDirection: "urban_aspirational",
    auraLeakTags: ["too_plain", "creator_energy_missing", "outfit_inconsistency"],
    recommendedCategories: ["jacket", "jeans", "tshirt", "sneakers", "sunglasses"],
    searchQuery: "lightweight bomber distressed denim graphic tee chunky sneakers",
    budgetMax: 8000,
  },
  {
    id: "harry-quiet-luxury",
    label: "Quiet Luxury Travel",
    celebrity: "Quiet Luxury Edit",
    imageSrc: "/celebs/harry-quiet-luxury.jpg",
    avatarLabel: "HS",
    avatarGradient: "from-peach-200 via-coral-300 to-rose-400",
    region: "Global",
    trendDateLabel: "March 2026",
    sourceLabel: "Vogue quiet luxury trend report",
    sourceUrl: "https://www.vogue.com/article/quiet-luxury-travel-wardrobe-2026",
    summary:
      "Understated investment pieces: unlined blazers, fine-gauge knits, tailored wide trousers, and leather accessories that whisper status.",
    styleDirection: "premium_minimal",
    auraLeakTags: ["low_premium_signal", "too_plain", "professional_mismatch"],
    recommendedCategories: ["jacket", "tshirt", "trousers", "watch", "belt"],
    searchQuery: "unlined blazer fine knit cashmere wide trousers quiet luxury",
    budgetMax: 15000,
  },
  {
    id: "dev-effortless-date",
    label: "Effortless Date Night",
    celebrity: "Effortless Charisma",
    imageSrc: "/celebs/dev-effortless-date.jpg",
    avatarLabel: "DP",
    avatarGradient: "from-olive-200 via-amber-300 to-brown-400",
    region: "Global",
    trendDateLabel: "May 2026",
    sourceLabel: "GQ date night outfit guide",
    sourceUrl: "https://www.gq.com/story/date-night-outfits-men-2026",
    summary:
      "Smart without stiffness: a great overshirt, dark jeans, clean white sneakers, and a leather jacket — the uniform of quiet charisma.",
    styleDirection: "understated_confident",
    auraLeakTags: ["dating_warmth_missing", "outfit_inconsistency", "too_plain"],
    recommendedCategories: ["overshirt", "jeans", "sneakers", "jacket", "watch"],
    searchQuery: "overshirt dark wash jeans white sneakers leather jacket date night",
    budgetMax: 10000,
  },
  {
    id: "global-street-tech",
    label: "Tokyo Street Tech",
    celebrity: "Global Street Style",
    imageSrc: "/celebs/global-street-tech.jpg",
    avatarLabel: "GS",
    avatarGradient: "from-lime-200 via-green-300 to-cyan-400",
    region: "Global",
    trendDateLabel: "June 2026",
    sourceLabel: "Hypebeast streetwear roundup",
    sourceUrl: "https://hypebeast.com/2026/streetwear-trends-2026",
    summary:
      "Tech fabrics, cargo silhouettes, neons accents, and futuristic sneakers — streetwear that nods to Harajuku while staying wearable.",
    styleDirection: "street_smart",
    auraLeakTags: ["creator_energy_missing", "too_plain", "outfit_inconsistency"],
    recommendedCategories: ["jacket", "tshirt", "sneakers", "hoodie", "sunglasses"],
    searchQuery: "tech cargo pants graphic hoodie futuristic sneakers streetwear harajuku",
    budgetMax: 10000,
  },
];
