import type { Challenge } from "@/types/challenge";

export const CHALLENGES: Challenge[] = [
  {
    id: "find-status-leak",
    title: "Find Your Biggest Status Leak",
    slug: "find-status-leak",
    description: "Upload a photo and discover the single thing quietly weakening your first impression.",
    type: "status_leak",
    entryRequirement: "Free Aura Score generated on any photo audit.",
    rewardText: "Know your #1 status leak and get a quick fix.",
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "premium-under-5000",
    title: "Look Premium Under ₹5,000",
    slug: "premium-under-5000",
    description: "Prove you can look polished without spending big. Style upgrades under ₹5,000 only.",
    type: "budget_upgrade",
    entryRequirement: "Full Aura Report with a budget upgrade plan.",
    rewardText: "See how far ₹5,000 can take your signal.",
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "clean-background",
    title: "Clean Background Challenge",
    slug: "clean-background",
    description: "Declutter your frame. A clean background instantly upgrades any photo.",
    type: "best_background",
    entryRequirement: "A before/after pair showing background improvement.",
    rewardText: "Master the cheapest upgrade: a clean frame.",
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "no-iphone-premium",
    title: "No iPhone Premium Look",
    slug: "no-iphone-premium",
    description: "You don't need an iPhone to look premium. Show your best shot taken on any Android device.",
    type: "no_iphone_premium",
    entryRequirement: "Photo taken on a non-iPhone device with a Full Aura Report score.",
    rewardText: "Prove premium is about skill, not the phone.",
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "dating-profile-cleanup",
    title: "Dating Profile Cleanup",
    slug: "dating-profile-cleanup",
    description: "Clean up your bio, reorder your photos, remove clichés. Enter your Dating Audit result.",
    type: "dating_profile_fix",
    entryRequirement: "Dating/Profile Audit result with bio feedback.",
    rewardText: "A dating profile that actually represents you.",
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "college-aura",
    title: "College Aura Check",
    slug: "college-aura",
    description: "Hostel room lighting, college campus backgrounds — show your best student-era shot.",
    type: "college_aura",
    entryRequirement: "Photo taken in a college/hostel setting with a free Aura Score.",
    rewardText: "See how you present in your college environment.",
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "glowup-start",
    title: "30-Day Glow-Up Start",
    slug: "glowup-start",
    description: "Kick off your 30-day plan. Take your baseline photo and unlock your glow-up roadmap.",
    type: "glowup_before_after",
    entryRequirement: "30-Day Glow-Up Plan unlocked for your audit.",
    rewardText: "A complete roadmap for your 30-day transformation.",
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "before-after-upgrade",
    title: "Before/After Aura Upgrade",
    slug: "before-after-upgrade",
    description: "Taken a second photo after following advice? Compare your before and after scores.",
    type: "glowup_before_after",
    entryRequirement: "Two audits with free scores to compare progress.",
    rewardText: "See your actual score improvement.",
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
];

export function getChallengeBySlug(slug: string): Challenge | undefined {
  return CHALLENGES.find((c) => c.slug === slug);
}
