import type { BudgetRange } from "@/types";
import type { Product } from "@/types/product";

const now = "2026-01-01T00:00:00Z";

export const PRODUCTS: Product[] = [
  {
    id: "white-sneakers",
    title: "Clean White Sneakers",
    category: "shoes",
    price: 1499,
    priceLabel: "₹1,499",
    description: "Minimal white sneakers that go with almost any outfit. Keep them clean for maximum impact.",
    whyItWorks: "White sneakers signal intentional grooming and freshness. They are the single highest-visibility footwear upgrade per rupee.",
    visualSignalImproved: "Overall freshness, outfit cohesion, foot presentation",
    statusLeakTags: ["grooming", "outfit"],
    goalTags: ["dating", "instagram", "college", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "instagram"],
    budgetTags: ["2000"],
    priorityScore: 85,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "black-overshirt",
    title: "Black Overshirt / Layer Jacket",
    category: "outfit",
    price: 1899,
    priceLabel: "₹1,899",
    description: "A well-fitted black overshirt that adds structure and intentionality to any casual outfit.",
    whyItWorks: "Layering instantly upgrades perceived effort. A dark layer creates contrast and frames the upper body well in photos.",
    visualSignalImproved: "Outfit depth, upper body framing, contrast in frame",
    statusLeakTags: ["outfit"],
    goalTags: ["dating", "instagram", "college", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "instagram", "dating"],
    budgetTags: ["2000"],
    priorityScore: 82,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "plain-solid-tshirt",
    title: "Plain Solid T-Shirt (Neutral Tone)",
    category: "outfit",
    price: 599,
    priceLabel: "₹599",
    description: "A plain solid-color t-shirt in black, white, or grey. No logos, no text.",
    whyItWorks: "Solid colors reduce visual noise and keep attention on your face. Logos and text are status leaks in profile photos.",
    visualSignalImproved: "Facial focus, signal cleanliness, frame simplicity",
    statusLeakTags: ["outfit", "clarity"],
    goalTags: ["dating", "instagram", "college", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating"],
    budgetTags: ["0", "2000"],
    priorityScore: 90,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "basic-metal-watch",
    title: "Minimal Metal Watch",
    category: "accessory",
    price: 1299,
    priceLabel: "₹1,299",
    description: "A simple silver or black metal watch with a clean dial. No digital or sports watches.",
    whyItWorks: "A metal watch signals maturity and attention to detail. It is visible in hand gestures and cropped shots.",
    visualSignalImproved: "Perceived maturity, detail orientation, wrist presentation",
    statusLeakTags: ["accessory"],
    goalTags: ["dating", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating"],
    budgetTags: ["2000", "5000"],
    priorityScore: 65,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "minimal-black-belt",
    title: "Minimal Black Belt",
    category: "accessory",
    price: 499,
    priceLabel: "₹499",
    description: "A plain black belt with a simple buckle. No logos or large branding.",
    whyItWorks: "A belt is a small detail that signals intentionality. A worn or missing belt is a subtle status leak.",
    visualSignalImproved: "Outfit completeness, attention to detail",
    statusLeakTags: ["outfit"],
    goalTags: ["dating", "office", "college", "glowup"],
    auditTypeTags: ["photo", "outfit"],
    budgetTags: ["0", "2000"],
    priorityScore: 55,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "clean-phone-case",
    title: "Clean Minimal Phone Case",
    category: "phone_accessory",
    price: 299,
    priceLabel: "₹299",
    description: "A solid-color phone case without cracks, prints, or branding. Keep it clean.",
    whyItWorks: "Your phone is visible in many photos. A cracked or dirty case signals neglect. A clean case is a cheap fix.",
    visualSignalImproved: "Hand-held object presentation, perceived cleanliness",
    statusLeakTags: ["grooming", "clarity"],
    goalTags: ["dating", "instagram", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating"],
    budgetTags: ["0", "2000"],
    priorityScore: 70,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "lens-cleaning-kit",
    title: "Lens Cleaning Kit",
    category: "photo_setup",
    price: 199,
    priceLabel: "₹199",
    description: "A microfiber cloth and small spray solution to keep your phone camera lens clean.",
    whyItWorks: "A dirty lens is the #1 cause of hazy, low-clarity photos. This is the cheapest clarity upgrade available.",
    visualSignalImproved: "Image sharpness, clarity, perceived effort",
    statusLeakTags: ["clarity"],
    goalTags: ["dating", "instagram", "college", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating", "outfit", "background"],
    budgetTags: ["0", "2000"],
    priorityScore: 95,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "basic-tripod",
    title: "Basic Phone Tripod",
    category: "photo_setup",
    price: 699,
    priceLabel: "₹699",
    description: "A small adjustable tripod for your phone. Enables steady hands-free shots.",
    whyItWorks: "Steady shots eliminate blur and allow consistent framing. A tripod is the cheapest photography upgrade.",
    visualSignalImproved: "Image sharpness, framing consistency, composition control",
    statusLeakTags: ["clarity", "framing"],
    goalTags: ["dating", "instagram", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating", "outfit"],
    budgetTags: ["0", "2000"],
    priorityScore: 88,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "clip-on-ring-light",
    title: "Clip-On Ring Light",
    category: "photo_setup",
    price: 899,
    priceLabel: "₹899",
    description: "A small LED ring light that clips onto your phone for even facial lighting.",
    whyItWorks: "Ring lights eliminate harsh shadows and create even skin lighting. Single highest lighting upgrade per rupee.",
    visualSignalImproved: "Facial lighting, shadow reduction, skin tone evenness",
    statusLeakTags: ["lighting"],
    goalTags: ["dating", "instagram", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating"],
    budgetTags: ["0", "2000"],
    priorityScore: 92,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "room-led-lamp",
    title: "Warm LED Desk Lamp",
    category: "room",
    price: 499,
    priceLabel: "₹499",
    description: "A warm-tone LED lamp for softer, more flattering indoor lighting.",
    whyItWorks: "Harsh overhead light creates unflattering shadows. A warm lamp placed in front of you creates premium soft lighting.",
    visualSignalImproved: "Room lighting, facial lighting, background warmth",
    statusLeakTags: ["lighting", "background"],
    goalTags: ["dating", "instagram", "college", "glowup"],
    auditTypeTags: ["photo", "instagram", "background"],
    budgetTags: ["0", "2000"],
    priorityScore: 85,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "neutral-bedsheet-backdrop",
    title: "Neutral Bedsheet / Backdrop Cloth",
    category: "room",
    price: 399,
    priceLabel: "₹399",
    description: "A solid-color bedsheet or cloth in white, grey, or beige to use as a clean background.",
    whyItWorks: "A messy room is a major status leak. A plain backdrop instantly eliminates background distractions.",
    visualSignalImproved: "Background cleanliness, subject focus, frame simplicity",
    statusLeakTags: ["background"],
    goalTags: ["dating", "instagram", "college", "glowup"],
    auditTypeTags: ["photo", "background", "dating"],
    budgetTags: ["0", "2000"],
    priorityScore: 90,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "basic-grooming-kit",
    title: "Basic Grooming Kit (Nail, Brow, Skin)",
    category: "grooming",
    price: 349,
    priceLabel: "₹349",
    description: "A small kit with nail clippers, brow scissors, and basic skincare essentials.",
    whyItWorks: "Grooming details are visible in close-up photos. Clean nails and brows signal self-respect.",
    visualSignalImproved: "Hand presentation, facial grooming, perceived cleanliness",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "instagram", "office", "glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: ["0", "2000"],
    priorityScore: 88,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "hair-styling-clay",
    title: "Hair Styling Clay / Wax",
    category: "grooming",
    price: 449,
    priceLabel: "₹449",
    description: "A matte hair clay or wax for a natural, styled look without shine.",
    whyItWorks: "Styled hair signals intentional grooming. Even a small improvement in hair presentation changes first impression.",
    visualSignalImproved: "Hair grooming, overall freshness, facial framing",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "instagram", "office", "glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: ["0", "2000"],
    priorityScore: 75,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "basic-deodorant",
    title: "Daily Deodorant / Perfume",
    category: "fragrance",
    price: 699,
    priceLabel: "₹699",
    description: "A mild daily deodorant or budget-friendly perfume. Fresh scent signals preparedness.",
    whyItWorks: "Scent is a subtle but powerful signal. It suggests the person is prepared for social interaction.",
    visualSignalImproved: "Perceived freshness, overall presentation",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "instagram", "office", "glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: ["0", "2000"],
    priorityScore: 60,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "simple-backpack",
    title: "Clean Simple Backpack",
    category: "bag",
    price: 999,
    priceLabel: "₹999",
    description: "A solid-color backpack without frayed straps, patches, or visible wear.",
    whyItWorks: "Your bag is visible in many candid shots. A worn or dirty bag signals neglect.",
    visualSignalImproved: "Overall freshness, carried-item presentation",
    statusLeakTags: ["grooming", "outfit"],
    goalTags: ["college", "office", "glowup"],
    auditTypeTags: ["photo", "outfit"],
    budgetTags: ["0", "2000"],
    priorityScore: 50,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sunglasses",
    title: "Classic Sunglasses (Wayfarer Style)",
    category: "accessory",
    price: 799,
    priceLabel: "₹799",
    description: "Simple black wayfarer-style sunglasses. No oversized or heavily tinted fashion frames.",
    whyItWorks: "Sunglasses add perceived coolness and work well in outdoor shots. They also hide tired eyes in candid photos.",
    visualSignalImproved: "Outdoor shot quality, perceived confidence, face framing",
    statusLeakTags: ["lighting", "framing"],
    goalTags: ["instagram", "dating", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating"],
    budgetTags: ["0", "2000"],
    priorityScore: 45,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "collar-shirt",
    title: "Well-Fitted Collar Shirt",
    category: "outfit",
    price: 1499,
    priceLabel: "₹1,499",
    description: "A solid-color collared shirt that fits well at shoulders and neck. White or light blue recommended.",
    whyItWorks: "A collared shirt instantly upgrades perceived formality and intentionality in profile photos.",
    visualSignalImproved: "Outfit formality, upper body framing, perceived effort",
    statusLeakTags: ["outfit"],
    goalTags: ["dating", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating"],
    budgetTags: ["2000", "5000"],
    priorityScore: 78,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "slim-wallet",
    title: "Minimal Slim Wallet",
    category: "accessory",
    price: 399,
    priceLabel: "₹399",
    description: "A slim cardholder or minimalist wallet. No bulging or worn-out bifolds.",
    whyItWorks: "A slim wallet is a subtle signal of organization and modernity. Bulging wallets visible in pants create a poor silhouette.",
    visualSignalImproved: "Pants silhouette, perceived organization",
    statusLeakTags: ["grooming", "outfit"],
    goalTags: ["dating", "office", "college", "glowup"],
    auditTypeTags: ["photo", "outfit"],
    budgetTags: ["0", "2000"],
    priorityScore: 40,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "iron-steamer",
    title: "Clothes Iron / Steamer",
    category: "room",
    price: 1299,
    priceLabel: "₹1,299",
    description: "A basic clothes iron or handheld steamer to remove wrinkles from shirts and t-shirts.",
    whyItWorks: "Wrinkled clothes signal neglect regardless of outfit quality. Wrinkle-free clothes look intentional.",
    visualSignalImproved: "Outfit freshness, perceived effort, fabric presentation",
    statusLeakTags: ["grooming", "outfit"],
    goalTags: ["dating", "office", "glowup"],
    auditTypeTags: ["photo", "outfit"],
    budgetTags: ["2000", "5000"],
    priorityScore: 72,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "local-haircut",
    title: "Professional Haircut (Local Salon)",
    category: "service",
    price: 300,
    priceLabel: "₹300",
    description: "A visit to a local barber or salon for a fresh, clean haircut.",
    whyItWorks: "A fresh haircut is the highest-impact visual upgrade available at any budget. It changes facial framing instantly.",
    visualSignalImproved: "Facial framing, overall freshness, perceived grooming",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "instagram", "college", "office", "glowup"],
    auditTypeTags: ["photo", "dating", "instagram"],
    budgetTags: ["0", "2000", "5000", "10000", "25000"],
    priorityScore: 96,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "local-photoshoot",
    title: "Local Profile Photoshoot Session",
    category: "service",
    price: 2999,
    priceLabel: "₹2,999",
    description: "A local photographer session for 2-3 high-quality profile photos.",
    whyItWorks: "Professional photos eliminate most status leaks at once: lighting, framing, clarity, and background.",
    visualSignalImproved: "Lighting, clarity, framing, background, overall signal",
    statusLeakTags: ["lighting", "clarity", "framing", "background"],
    goalTags: ["dating", "instagram", "office", "glowup"],
    auditTypeTags: ["photo", "instagram", "dating", "outfit", "background"],
    budgetTags: ["5000", "10000", "25000"],
    priorityScore: 94,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "room-declutter-storage",
    title: "Room Declutter Storage Boxes",
    category: "room",
    price: 599,
    priceLabel: "₹599",
    description: "Basic storage boxes to organize visible clutter in your room or background.",
    whyItWorks: "Visible clutter is a major background status leak. Organizing it costs very little but changes the entire frame.",
    visualSignalImproved: "Background cleanliness, perceived organization, space quality",
    statusLeakTags: ["background"],
    goalTags: ["dating", "instagram", "college", "glowup"],
    auditTypeTags: ["background", "photo", "dating"],
    budgetTags: ["0", "2000"],
    priorityScore: 86,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "hoodie-neutral",
    title: "Solid Hoodie (No Logos)",
    category: "outfit",
    price: 999,
    priceLabel: "₹999",
    description: "A plain hoodie without logos or graphics. Black, grey, or navy recommended.",
    whyItWorks: "A clean hoodie works for casual shots. Logos and graphics are visual noise that distract from your face.",
    visualSignalImproved: "Facial focus, outfit simplicity, casual signal",
    statusLeakTags: ["outfit"],
    goalTags: ["college", "instagram", "glowup"],
    auditTypeTags: ["photo", "outfit"],
    budgetTags: ["0", "2000"],
    priorityScore: 65,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "wireless-earbuds",
    title: "Basic Wireless Earbuds",
    category: "phone_accessory",
    price: 799,
    priceLabel: "₹799",
    description: "Simple wireless earbuds. No dangling wires visible in photos.",
    whyItWorks: "Wired earphones visible in photos signal dated tech. Wireless earbuds suggest modernity.",
    visualSignalImproved: "Tech modernity, clean look in candid shots",
    statusLeakTags: ["grooming"],
    goalTags: ["instagram", "college", "glowup"],
    auditTypeTags: ["photo", "instagram"],
    budgetTags: ["0", "2000"],
    priorityScore: 40,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "white-casual-shirt",
    title: "White Casual Shirt",
    category: "outfit",
    price: 1299,
    priceLabel: "₹1,299",
    description: "A well-fitted white casual shirt. The most versatile upper-wear item for any goal.",
    whyItWorks: "White reads as clean and intentional in every context. It works for dating, office, and casual profile photos.",
    visualSignalImproved: "Outfit versatility, brightness in frame, perceived cleanliness",
    statusLeakTags: ["outfit", "lighting"],
    goalTags: ["dating", "instagram", "college", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating", "instagram"],
    budgetTags: ["2000", "5000"],
    priorityScore: 80,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "gym-fitness-basic",
    title: "Basic Fitness / Gym Session Pack",
    category: "service",
    price: 1999,
    priceLabel: "₹1,999",
    description: "A month of basic gym or home workout consistency for better physique presentation.",
    whyItWorks: "Fitness is the longest-term visual upgrade. Even one month of consistency improves posture, confidence, and frame.",
    visualSignalImproved: "Posture, body composition, perceived discipline, confidence",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating"],
    budgetTags: ["2000", "5000", "10000", "25000"],
    priorityScore: 80,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "dark-wash-jeans",
    title: "Dark Wash Slim Jeans",
    category: "outfit",
    price: 1499,
    priceLabel: "₹1,499",
    description: "Dark wash slim-fit jeans without rips, tears, or heavy fading.",
    whyItWorks: "Dark jeans read as more formal and intentional than light wash or ripped jeans in photos.",
    visualSignalImproved: "Lower body presentation, outfit coherence, formality signal",
    statusLeakTags: ["outfit"],
    goalTags: ["dating", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating"],
    budgetTags: ["2000", "5000"],
    priorityScore: 70,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "leather-loafers",
    title: "Basic Leather Loafers",
    category: "shoes",
    price: 2499,
    priceLabel: "₹2,499",
    description: "Simple black or brown leather loafers. Clean silhouette, minimal design.",
    whyItWorks: "Loafers signal maturity and style awareness. They work for both casual and semi-formal settings.",
    visualSignalImproved: "Footwear sophistication, outfit completion, maturity signal",
    statusLeakTags: ["grooming", "outfit"],
    goalTags: ["dating", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating"],
    budgetTags: ["5000"],
    priorityScore: 68,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "skincare-starter",
    title: "Skincare Starter Kit",
    category: "grooming",
    price: 999,
    priceLabel: "₹999",
    description: "Basic cleanser, moisturizer, and sunscreen. No medical claims.",
    whyItWorks: "Healthy skin signals good habits and self-care. It improves facial close-ups in all photo types.",
    visualSignalImproved: "Skin clarity, facial presentation, perceived health",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "instagram", "glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: ["0", "2000", "5000"],
    priorityScore: 75,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "lightweight-jacket",
    title: "Lightweight Bomber Jacket",
    category: "outfit",
    price: 2199,
    priceLabel: "₹2,199",
    description: "A minimal bomber jacket in olive, navy, or black. No patches or branding.",
    whyItWorks: "A bomber jacket adds structure and edge to casual outfits. It photographs well in upper-body shots.",
    visualSignalImproved: "Outfit structure, shoulder framing, casual confidence",
    statusLeakTags: ["outfit"],
    goalTags: ["dating", "instagram", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating"],
    budgetTags: ["5000"],
    priorityScore: 74,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "posture-corrector",
    title: "Posture Awareness Guide",
    category: "service",
    price: 0,
    priceLabel: "Free",
    description: "Simple posture tips: stand straight, shoulders back, chin slightly up. Practice in front of a mirror.",
    whyItWorks: "Posture is visible in every photo and video. Good posture signals confidence instantly and costs nothing.",
    visualSignalImproved: "Perceived confidence, height perception, overall presence",
    statusLeakTags: ["grooming", "framing"],
    goalTags: ["dating", "instagram", "college", "office", "glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: ["0"],
    priorityScore: 85,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "smile-practice",
    title: "Smile Practice Guide",
    category: "service",
    price: 0,
    priceLabel: "Free",
    description: "Practice smiling naturally in front of a mirror. Relax your jaw and eyes. Take 10 test shots.",
    whyItWorks: "A genuine-looking smile is the single highest-ROI facial expression upgrade and it costs nothing.",
    visualSignalImproved: "Facial warmth, perceived approachability, photo engagement",
    statusLeakTags: ["grooming", "framing"],
    goalTags: ["dating", "instagram", "college", "office", "glowup"],
    auditTypeTags: ["photo", "dating", "instagram"],
    budgetTags: ["0"],
    priorityScore: 90,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "denim-jacket",
    title: "Classic Denim Jacket",
    category: "outfit",
    price: 2499,
    priceLabel: "₹2,499",
    description: "A classic blue denim jacket that fits well at shoulders. Minimal fading preferred.",
    whyItWorks: "Denim jackets are timeless and photograph well. They add texture and depth without being loud.",
    visualSignalImproved: "Outfit depth, casual style signal, upper body framing",
    statusLeakTags: ["outfit"],
    goalTags: ["dating", "instagram", "college", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating"],
    budgetTags: ["5000"],
    priorityScore: 72,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "face-moisturizer",
    title: "Basic Face Moisturizer",
    category: "grooming",
    price: 299,
    priceLabel: "₹299",
    description: "A basic moisturizer for daily use. Keeps skin looking healthy in close-up photos.",
    whyItWorks: "Moisturized skin reflects light better and looks healthier in photos. Extremely cheap per-use cost.",
    visualSignalImproved: "Skin appearance, facial close-up quality",
    statusLeakTags: ["grooming"],
    goalTags: ["dating", "instagram", "glowup"],
    auditTypeTags: ["photo", "dating"],
    budgetTags: ["0", "2000"],
    priorityScore: 70,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "water-bottle",
    title: "Clean Reusable Water Bottle",
    category: "accessory",
    price: 299,
    priceLabel: "₹299",
    description: "A clean, modern reusable water bottle. No visible wear or stains.",
    whyItWorks: "A clean water bottle visible in shots signals health awareness. A stained or plastic bottle signals neglect.",
    visualSignalImproved: "Health consciousness signal, carried-item presentation",
    statusLeakTags: ["grooming"],
    goalTags: ["college", "office", "glowup"],
    auditTypeTags: ["photo", "outfit"],
    budgetTags: ["0", "2000"],
    priorityScore: 35,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "wardrobe-capsule-plan",
    title: "Wardrobe Capsule Planning Guide",
    category: "service",
    price: 0,
    priceLabel: "Free",
    description: "A guide to building a 10-piece capsule wardrobe: mix-and-match outfits from minimal items.",
    whyItWorks: "A capsule wardrobe ensures every photo shows a fresh, intentional outfit without needing 50 items.",
    visualSignalImproved: "Outfit variety, perceived style, intentionality across photos",
    statusLeakTags: ["outfit"],
    goalTags: ["dating", "instagram", "college", "office", "glowup"],
    auditTypeTags: ["photo", "outfit", "dating", "instagram"],
    budgetTags: ["0"],
    priorityScore: 78,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "basic-phone-stand",
    title: "Basic Phone Stand",
    category: "photo_setup",
    price: 349,
    priceLabel: "₹349",
    description: "A small desktop phone stand for stable hands-free video calls and self-timer shots.",
    whyItWorks: "Phone stands free your hands and enable consistent framing. Useful for video calls and profile shots.",
    visualSignalImproved: "Shot stability, framing consistency, video call presentation",
    statusLeakTags: ["clarity", "framing"],
    goalTags: ["dating", "instagram", "office", "glowup"],
    auditTypeTags: ["photo", "instagram"],
    budgetTags: ["0", "2000"],
    priorityScore: 60,
    affiliateUrl: "#",
    isSponsored: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category === category && p.isActive);
}

export function getProductsByBudget(budget: string): Product[] {
  return PRODUCTS.filter((p) => p.budgetTags.includes(budget as BudgetRange) && p.isActive);
}
