import type { ProofExample } from "@/types/proof";

export const PROOF_EXAMPLES: ProofExample[] = [
  {
    id: "lighting-fix-01",
    title: "Lighting Fix",
    category: "lighting_fix",
    beforeScore: 42,
    afterScore: 71,
    scoreDelta: 29,
    biggestLeak: "Flat overhead lighting washing out facial bone structure",
    fixApplied: "Shifted to 45° Rembrandt window light at chin height, killed overhead fixtures, added sheer curtain as diffuser",
    costLabel: "₹0",
    timeLabel: "Immediate",
    productSuggested: "quick_fix",
    beforeVisualDescription: "Single overhead fluorescent creating harsh shadows under brow ridge and nose. Skin appears sallow with yellow-green color cast. Jawline disappears into neck shadow. Eye sockets read as hollow. No catch light in eyes — they look flat and lifeless.",
    afterVisualDescription: "45-degree window light creates Rembrandt triangle on far cheek, sculpting cheekbones naturally. Catch lights appear in both eyes, adding life and depth. Skin tone reads warm and even. Jawline definition improves by 2 stops. Nose shadow falls diagonally — the most universally flattering angle.",
    keyLesson: "Portrait lighting follows the same physics regardless of camera quality. A 45-degree side light at chin height creates what photographers call the Rembrandt triangle — a small inverted triangle of light on the shadow-side cheek. This single shadow pattern scours cheekbones and jawline without any editing. Overhead lights destroy this by casting brow shadows into eye sockets. Kill every light above you, face a window, and your bone structure appears to change. This costs ₹0 and improves your score more than any wardrobe upgrade.",
    ctaText: "Unlock Quick Aura Fix — ₹25",
    ctaHref: "/unlock?product=quick_fix",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "background-fix-01",
    title: "Background Fix",
    category: "background_fix",
    beforeScore: 48,
    afterScore: 74,
    scoreDelta: 26,
    biggestLeak: "Background complexity at 82/100 — 7+ competing visual elements diluting subject presence",
    fixApplied: "Relocated to neutral-toned wall, removed 7 distracting objects, shot at f/2.8 equivalent to blur residual background detail",
    costLabel: "₹0–₹500",
    timeLabel: "15 minutes",
    productSuggested: "quick_fix",
    beforeVisualDescription: "Unmade bed with wrinkled sheets in lower third. Door with visible hinges center-left. Stack of Amazon boxes right edge. Clothes hanging on chair back. Power cord crossing frame horizontally. Each element pulls the eye away from the subject — the visual cortex processes every object before settling on the face.",
    afterVisualDescription: "Subject against a plain off-white wall at 45 degrees. Wall texture provides subtle depth without competition. Single color temperature throughout. The eye goes directly to the face because there is nowhere else to go. Background-to-subject separation is clean — the person owns 100% of the visual hierarchy.",
    keyLesson: "Your background is not just 'behind you' — it is processed by the viewer's visual cortex before your face is. In eye-tracking studies, busy backgrounds cause the viewer's gaze to scatter for 0.3-0.8 seconds before landing on the subject. That delay is enough to lose the first impression. Every object in your frame — a door hinge, a power cord, a stack of boxes — competes for attention. A professional photographer would call this 'visual noise' and eliminate it. The cheapest fix is moving to a plain wall. The next cheapest is removing the 5-7 objects your brain has learned to ignore but a stranger's eye catches instantly.",
    ctaText: "Unlock Quick Aura Fix — ₹25",
    ctaHref: "/unlock?product=quick_fix",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "crop-framing-01",
    title: "Crop / Framing Fix",
    category: "crop_fix",
    beforeScore: 51,
    afterScore: 72,
    scoreDelta: 21,
    biggestLeak: "Subject occupies only 34% of frame — wasted visual real estate diluting presence",
    fixApplied: "Recomposed to 4:5 vertical, eyes positioned at upper-third line, 15% headroom, shoulders filling lower frame edge",
    costLabel: "₹0",
    timeLabel: "5 minutes",
    productSuggested: "aura_report",
    beforeVisualDescription: "Horizontal crop with subject centered at 35% frame occupancy. Excessive headroom creating 'floating head' effect. Shoulders cut off at frame edge. Background occupies 66% of visual space. The composition says 'I am small in this frame' — a visual signal of low confidence regardless of what the person is actually wearing.",
    afterVisualDescription: "Vertical 4:5 crop. Eyes positioned at upper-third intersection — the natural focal point where viewers look first. Shoulders fill the lower edge, anchoring the composition. Headroom is tight but sufficient (15% of frame height). Subject now occupies 70% of frame. The composition says 'I belong here' — intentional, centered, confident.",
    keyLesson: "Framing is the silent confidence signal. In portrait photography, the 'rule of thirds' places the eyes at the upper-third intersection — this is where the human eye naturally gravitates. When you leave excessive headroom, the composition reads as accidental rather than intentional. A 4:5 vertical crop with the subject occupying 65-75% of the frame is the standard for professional headshots across LinkedIn, dating apps, and Instagram. The frame ratio itself communicates something: horizontal says 'scenic, distant' while vertical says 'personal, direct.' For profile photos, vertical is almost always correct. This takes 5 minutes to fix in any photo editor and costs nothing.",
    ctaText: "Get Full Aura Report — ₹50",
    ctaHref: "/products/aura-report",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "premium-minimal-01",
    title: "Premium Minimal Fix",
    category: "outfit_consistency",
    beforeScore: 53,
    afterScore: 78,
    scoreDelta: 25,
    biggestLeak: "Visual signal conflict — 4+ competing brand logos, 3 color temperatures, and background noise creating cognitive overload",
    fixApplied: "Shifted to monochrome palette (3 colors max), removed all visible logos, matched outfit temperature to background, reduced accessory count from 5 to 2",
    costLabel: "Under ₹2,000",
    timeLabel: "1 day",
    productSuggested: "aura_report",
    beforeVisualDescription: "Nike graphic tee with large Swoosh competing with gold chain, branded cap, and logo belt. Background has posters and clutter adding 3 more visual elements. Total competing signals: 9+. The viewer's brain cannot process who you are because it is too busy processing what you are wearing. Each brand logo triggers a separate cognitive association — the brain scatters.",
    afterVisualDescription: "Solid navy crew neck (no logos) with clean white sneakers. Single silver chain at collarbone. Background is a plain warm-toned wall. Total visual elements: 4 (face, top, accessory, background). The viewer's eye goes face → outfit → detail → done. Processing time drops from 1.2 seconds to 0.4 seconds. The brain registers 'person' before 'clothes' — which is the entire point.",
    keyLesson: "Premium signal is not about price — it is about visual hierarchy. A stylist calls this 'the three-element rule': in any frame, the viewer should process no more than 3-4 intentional elements. Each logo, each brand mark, each accessory adds cognitive load. When you wear a Nike tee, a gold chain, a branded cap, and a logo belt, the viewer's brain processes 4 separate brand associations before it even registers your face. A designer would call this 'signal noise.' The fix is subtraction, not addition. Remove logos, reduce to 3 color temperatures maximum, and let your face be the first thing processed. This is why minimalism reads as premium — not because minimal items are expensive, but because they remove competition for attention.",
    ctaText: "Get Full Aura Report — ₹50",
    ctaHref: "/products/aura-report",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "dating-profile-order-01",
    title: "Dating Profile Order Fix",
    category: "profile_order_fix",
    beforeScore: 44,
    afterScore: 70,
    scoreDelta: 26,
    biggestLeak: "First photo is a group shot with 4 people — viewer spends 1.8 seconds identifying who the profile belongs to, then swipes left",
    fixApplied: "Reordered: solo portrait (best lighting) → full body lifestyle → activity/hobby → social proof → conversation starter. Added face-clear first photo rule.",
    costLabel: "₹0",
    timeLabel: "10 minutes",
    productSuggested: "dating_audit",
    beforeVisualDescription: "Photo 1: group of 5 friends at a bar — viewer cannot tell which person owns the profile. Photo 2: blurry mirror selfie with flash glare. Photo 3: distant landscape with person barely visible. Each photo fails the '0.3-second test' — the time it takes a viewer to decide interest. Result: left-swipe before bio is read.",
    afterVisualDescription: "Photo 1: solo portrait with window light, slight smile, eye contact — instant clarity on who this person is. Photo 2: full body shot showing outfit and physique in context. Photo 3: activity shot (cooking, hiking, playing guitar) — conversation starter. Photo 4: social proof with friends (but clearly identifiable). Photo 5: close-up showing genuine expression. Each photo passes the 0.3-second test independently.",
    keyLesson: "Dating app data from 2024-2025 shows the average user spends 0.3-0.7 seconds on a profile photo before swiping. If your first photo requires cognitive effort to identify you — a group shot, a distant photo, a blurry selfie — the viewer swipes left before reading your bio. The optimal photo order follows a narrative arc: (1) clear solo portrait for instant identification, (2) full body for physical context, (3) activity for conversation hooks, (4) social proof for trust, (5) close-up for intimacy. Each photo must pass the '0.3-second test' independently. If any photo in the sequence fails, it breaks the narrative and drops your match rate. This costs ₹0 — it is pure reordering.",
    ctaText: "Unlock Dating/Profile Audit — ₹299",
    ctaHref: "/products/dating-audit",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "instagram-consistency-01",
    title: "Instagram Consistency Fix",
    category: "lighting_fix",
    beforeScore: 46,
    afterScore: 73,
    scoreDelta: 27,
    biggestLeak: "Feed visual inconsistency — 6 different lighting conditions, 4 filter styles, 3 color temperatures across 9 posts",
    fixApplied: "Established consistent warm-white balance (5500K equivalent), standardized to golden-hour lighting window, applied unified warm preset across all posts",
    costLabel: "₹0–₹1,000",
    timeLabel: "1 week",
    productSuggested: "aura_report",
    beforeVisualDescription: "Post 1: blue-tinted fluorescent indoor. Post 2: warm sunset golden hour. Post 3: harsh midday overhead. Post 4: flash-lit dark room. Post 5: cool-toned overcast. No two photos share a color temperature. The feed reads as 6 different people. A brand strategist would call this 'identity fragmentation' — the visual equivalent of stuttering.",
    afterVisualDescription: "All 9 posts share consistent warm color temperature (5200-5800K range). Lighting direction is consistently 45-degree side or front-lit. Background tones are neutral (whites, creams, warm grays). The feed reads as one coherent person with a recognizable visual signature. A designer would call this 'brand cohesion.' The brain processes the feed as a single identity rather than a collection of strangers.",
    keyLesson: "Instagram is a visual portfolio, not a photo album. A brand strategist would say your feed is your 'visual identity system' — it should communicate who you are in under 2 seconds of scrolling. When every post has different lighting, filters, and color temperatures, the viewer's brain cannot form a coherent impression. Each inconsistency is a micro-interruption. The fix is establishing a 'color temperature anchor' — a consistent white balance (warm at 5500K is universally flattering) and a lighting direction (45-degree side light). Apply this across every post. The result is that your feed reads as one person with intention, not a collection of random moments. Consistency is the most underrated growth signal on visual platforms.",
    ctaText: "Get Full Aura Report — ₹50",
    ctaHref: "/products/aura-report",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "glowup-system-01",
    title: "30-Day System Fix",
    category: "glowup_system",
    beforeScore: 41,
    afterScore: 79,
    scoreDelta: 38,
    biggestLeak: "No systematic approach — sporadic efforts with no compounding structure, each session starting from zero",
    fixApplied: "Implemented 4-week progressive system: Week 1 (lighting + framing basics), Week 2 (wardrobe color palette + fit audit), Week 3 (grooming routine + skincare), Week 4 (consistency system + batch shooting)",
    costLabel: "Budget-aware",
    timeLabel: "30 days",
    productSuggested: "glowup_plan",
    beforeVisualDescription: "Week 1: new haircut, good lighting photo. Week 2: back to old clothes, overhead lighting. Week 3: bought an expensive jacket, wore it with clashing pants. Week 4: mirror selfie with messy room. Each week is an island — no learning carries forward. The score oscillates between 42-58 with no upward trend. Improvement does not compound because there is no system connecting the sessions.",
    afterVisualDescription: "Week 1: 41 → 52 (lighting fix alone adds 11 points). Week 2: 52 → 61 (wardrobe color consistency adds 9). Week 3: 61 → 70 (grooming + skincare adds 9). Week 4: 70 → 79 (consistency system locks in gains). Each week builds on the previous. The 38-point improvement is not from one dramatic change — it is from 4 focused weeks of compounding small fixes. The system creates habits that persist beyond the 30 days.",
    keyLesson: "The difference between a glow-up and a makeover is structure. A makeover is a one-time event — new clothes, new haircut, one good photo. A glow-up is a system that compounds. In behavioral psychology, habit stacking works by attaching new behaviors to existing ones. Week 1 establishes the foundation (lighting and framing — the ₹0 fixes). Week 2 adds wardrobe consistency (color palette + fit — the ₹500-2000 fixes). Week 3 adds grooming (skincare + hair — the ₹200-1000 fixes). Week 4 creates the persistence system (batch shooting + weekly review). Each week's change is small enough to be sustainable but large enough to show measurable score improvement. The 38-point average gain comes from compounding — not from any single dramatic change.",
    ctaText: "Start 30-Day Reset — ₹499",
    ctaHref: "/products/glowup-plan",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "avoid-waste-01",
    title: "Avoid Waste Example",
    category: "background_fix",
    beforeScore: 43,
    afterScore: 44,
    scoreDelta: 1,
    biggestLeak: "Expensive accessory (₹15,000 watch) layered on broken foundations — poor lighting, cluttered background, weak framing",
    fixApplied: "Added ₹15,000 watch without addressing lighting (score 38), background (score 29), or framing (score 45). Foundation score remained 37/100.",
    costLabel: "High — wasted",
    timeLabel: "N/A",
    productSuggested: "quick_fix",
    beforeVisualDescription: "Overhead fluorescent creating harsh shadows. Background cluttered with furniture and visible mess. Framing is a wide horizontal shot with excessive empty space. The person bought a premium watch hoping it would elevate the photo. The watch is barely visible because the lighting washes out the metal details. The cluttered background makes the wrist invisible. The weak framing means the viewer never looks at the wrist.",
    afterVisualDescription: "The watch is technically present but the score moved only 1 point (43→44). The lighting still creates harsh facial shadows. The background still competes for attention. The framing still wastes space. The expensive watch is the most expensive invisible object in the photo. The foundational issues — lighting, background, framing — suppress every other signal. No accessory can overcome broken basics.",
    keyLesson: "This is the most expensive mistake in personal presentation. A ₹15,000 watch on a photo with lighting score 38, background score 29, and framing score 45 gains exactly 1 point. The foundational issues suppress every upgrade. A photographer would say: 'Lighting is the canvas — nothing else matters until the canvas is right.' A designer would say: 'The background is 60% of your visual real estate — get it right first.' A stylist would say: 'Accessories are the final 5% — they only work when the other 95% is solid.' The correct order is: (1) fix lighting (₹0), (2) fix background (₹0-500), (3) fix framing (₹0), (4) fix outfit (₹500-2000), (5) add accessories (₹500+). Skipping to step 5 wastes money.",
    ctaText: "Unlock Quick Aura Fix — ₹25",
    ctaHref: "/unlock?product=quick_fix",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
];
