import type { ProofExample } from "@/types/proof";

export const PROOF_EXAMPLES: ProofExample[] = [
  {
    id: "lighting-fix-01",
    title: "Lighting Fix",
    category: "lighting_fix",
    beforeScore: 58,
    afterScore: 73,
    scoreDelta: 15,
    biggestLeak: "Weak lighting",
    fixApplied: "Face window light + clean lens",
    costLabel: "₹0",
    timeLabel: "Immediate",
    productSuggested: "quick_fix",
    beforeVisualDescription: "Dark, uneven shadows across the face. Low contrast. Harsh overhead light creating unflattering angles.",
    afterVisualDescription: "Soft natural light from the side. Warm tones. Clear face visibility with better depth and dimension.",
    keyLesson: "You do not need an expensive camera. Moving near a window can improve your score more than any accessory.",
    ctaText: "Unlock Quick Aura Fix — ₹25",
    ctaHref: "/unlock?product=quick_fix",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "background-fix-01",
    title: "Background Fix",
    category: "background_fix",
    beforeScore: 61,
    afterScore: 77,
    scoreDelta: 16,
    biggestLeak: "Busy background",
    fixApplied: "Plain wall + decluttered frame",
    costLabel: "₹0–₹500",
    timeLabel: "15 minutes",
    productSuggested: "quick_fix",
    beforeVisualDescription: "Cluttered room with visible laundry, unmade bed, and random objects competing for attention.",
    afterVisualDescription: "Clean plain wall. Minimal distractions. The subject becomes the clear focal point of the frame.",
    keyLesson: "A busy background is the fastest way to weaken a strong face or outfit. Decluttering costs nothing.",
    ctaText: "Unlock Quick Aura Fix — ₹25",
    ctaHref: "/unlock?product=quick_fix",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "crop-framing-01",
    title: "Crop / Framing Fix",
    category: "crop_fix",
    beforeScore: 64,
    afterScore: 76,
    scoreDelta: 12,
    biggestLeak: "Weak framing",
    fixApplied: "4:5 vertical crop + centered frame",
    costLabel: "₹0",
    timeLabel: "5 minutes",
    productSuggested: "aura_report",
    beforeVisualDescription: "Wide wasteful crop. Subject too far from camera. Distracting empty space around the edges.",
    afterVisualDescription: "Tight 4:5 vertical frame. Subject centered with clean headroom. Intentional composition draws focus.",
    keyLesson: "How you frame yourself signals how you see yourself. A centered, intentional crop projects confidence.",
    ctaText: "Get Full Aura Report — ₹50",
    ctaHref: "/products/aura-report",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "premium-minimal-01",
    title: "Premium Minimal Fix",
    category: "outfit_consistency",
    beforeScore: 66,
    afterScore: 80,
    scoreDelta: 14,
    biggestLeak: "Loud / mismatched visual signal",
    fixApplied: "Neutral outfit + cleaner background",
    costLabel: "Under ₹2,000",
    timeLabel: "1 day",
    productSuggested: "aura_report",
    beforeVisualDescription: "Brand-heavy outfit with clashing colors. Logos compete with the face for attention. Background amplifies the noise.",
    afterVisualDescription: "Solid neutral colors. Clean fit without logos. Background fades into the frame, letting the person stand out.",
    keyLesson: "Premium does not mean loud. A neutral outfit with good fit signals confidence better than expensive logos.",
    ctaText: "Get Full Aura Report — ₹50",
    ctaHref: "/products/aura-report",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "dating-profile-order-01",
    title: "Dating Profile Order Fix",
    category: "profile_order_fix",
    beforeScore: 62,
    afterScore: 74,
    scoreDelta: 12,
    biggestLeak: "Weak first photo order",
    fixApplied: "Clear solo photo first, lifestyle second",
    costLabel: "₹0",
    timeLabel: "10 minutes",
    productSuggested: "dating_audit",
    beforeVisualDescription: "First photo is a group shot. Hard to tell who the profile belongs to. Second photo is a blurry mirror selfie.",
    afterVisualDescription: "First photo is a clear solo shot with good lighting. Second photo shows an activity. Order tells a story.",
    keyLesson: "Your first photo should be your strongest. If the first image is unclear, the viewer swipes before reading your bio.",
    ctaText: "Unlock Dating/Profile Audit — ₹299",
    ctaHref: "/products/dating-audit",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "instagram-consistency-01",
    title: "Instagram Consistency Fix",
    category: "lighting_fix",
    beforeScore: 60,
    afterScore: 75,
    scoreDelta: 15,
    biggestLeak: "Random visual style",
    fixApplied: "Consistent lighting + color palette",
    costLabel: "₹0–₹1,000",
    timeLabel: "1 week",
    productSuggested: "aura_report",
    beforeVisualDescription: "Photos with wildly different lighting, filters, and moods. No visual thread linking the feed together.",
    afterVisualDescription: "Consistent warm lighting. Cohesive color palette. Every photo feels like it belongs to the same person.",
    keyLesson: "Inconsistent visuals make you look unfocused. A consistent style builds recognition and trust faster than any single photo.",
    ctaText: "Get Full Aura Report — ₹50",
    ctaHref: "/products/aura-report",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "glowup-system-01",
    title: "30-Day System Fix",
    category: "glowup_system",
    beforeScore: 57,
    afterScore: 82,
    scoreDelta: 25,
    biggestLeak: "Repeated inconsistency",
    fixApplied: "4-week base + outfit + photo system",
    costLabel: "Budget-aware",
    timeLabel: "30 days",
    productSuggested: "glowup_plan",
    beforeVisualDescription: "One week good, next week back to old habits. No system. Improvement does not compound because there is no structure.",
    afterVisualDescription: "Steady visible improvement across weeks. Outfits improve. Photos get better. Grooming becomes consistent. The system works.",
    keyLesson: "Sporadic effort does not compound. A structured 30-day system creates habits that last far beyond the first week.",
    ctaText: "Start 30-Day Reset — ₹499",
    ctaHref: "/products/glowup-plan",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "avoid-waste-01",
    title: "Avoid Waste Example",
    category: "background_fix",
    beforeScore: 59,
    afterScore: 60,
    scoreDelta: 1,
    biggestLeak: "Lighting / background ignored",
    fixApplied: "Expensive accessory instead of fixing basics",
    costLabel: "High — wasted",
    timeLabel: "N/A",
    productSuggested: "quick_fix",
    beforeVisualDescription: "Poor lighting and cluttered background. The subject bought an expensive watch hoping it would distract from the weak frame.",
    afterVisualDescription: "The watch is visible but the poor lighting and clutter still dominate. The expensive item cannot fix broken photo basics.",
    keyLesson: "Expensive items do not fix poor photo basics. Fix lighting and background first. Accessories only add value when the foundation is solid.",
    ctaText: "Unlock Quick Aura Fix — ₹25",
    ctaHref: "/unlock?product=quick_fix",
    isDemo: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
];
