import type { StoreConnectorConfig } from "@/types/storeConnector";

export const STORE_CONNECTORS: StoreConnectorConfig[] = [
  {
    key: "myntra",
    displayName: "Myntra",
    storeKey: "myntra",
    sourceType: "official_api",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: false,
    isActive: true,
    notes: "No official public API available. Support CSV/feed import from affiliate dashboards or manual catalog entry.",
    requiredCredentials: [],
    feedFormatHint: "CSV with columns: title, price, mrp, url, category, image_url",
  },
  {
    key: "ajio",
    displayName: "AJIO",
    storeKey: "ajio",
    sourceType: "official_api",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: false,
    isActive: true,
    notes: "Reliance platform. No public API. Support manual CSV/feed import.",
    requiredCredentials: [],
    feedFormatHint: "CSV with columns: title, price, mrp, url, category, image_url",
  },
  {
    key: "amazon_fashion",
    displayName: "Amazon Fashion",
    storeKey: "amazon_fashion",
    sourceType: "official_api",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: true,
    isActive: true,
    notes: "Amazon PA-API available but requires affiliate account. Stub configured for future integration.",
    requiredCredentials: ["amazon_access_key", "amazon_secret_key", "amazon_associate_tag"],
    feedFormatHint: "Amazon PA-API v5 or CSV export from Amazon affiliate dashboard",
    apiDocsUrl: "https://webservices.amazon.com/paapi5/documentation/",
  },
  {
    key: "flipkart_fashion",
    displayName: "Flipkart Fashion",
    storeKey: "flipkart_fashion",
    sourceType: "official_api",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: true,
    isActive: true,
    notes: "Flipkart Affiliate API available. Requires Flipkart affiliate account. Stub configured for future integration.",
    requiredCredentials: ["flipkart_affiliate_id", "flipkart_affiliate_token"],
    feedFormatHint: "Flipkart Affiliate API XML/JSON feed",
    apiDocsUrl: "https://affiliate.flipkart.com/api-docs",
  },
  {
    key: "tata_cliq",
    displayName: "Tata CLiQ",
    storeKey: "tata_cliq",
    sourceType: "official_api",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: false,
    isActive: true,
    notes: "No public API available. Support manual CSV/feed import.",
    requiredCredentials: [],
    feedFormatHint: "CSV with columns: title, price, mrp, url, category, image_url",
  },
  {
    key: "nykaa_fashion",
    displayName: "Nykaa Fashion",
    storeKey: "nykaa_fashion",
    sourceType: "official_api",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: true,
    isActive: true,
    notes: "No public API. Affiliate program available for link-based tracking.",
    requiredCredentials: [],
    feedFormatHint: "CSV with columns: title, price, mrp, url, category, image_url",
  },
  {
    key: "meesho",
    displayName: "Meesho",
    storeKey: "meesho",
    sourceType: "official_api",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: false,
    isActive: true,
    notes: "No public API. Support manual CSV/feed import for budget-friendly catalog.",
    requiredCredentials: [],
    feedFormatHint: "CSV with columns: title, price, mrp, url, category, image_url",
  },
  {
    key: "snitch",
    displayName: "Snitch",
    storeKey: "snitch",
    sourceType: "manual",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: false,
    isActive: true,
    notes: "Independent brand. Manual catalog entry only.",
    requiredCredentials: [],
    feedFormatHint: "JSON or CSV with product details, prices, and store links",
  },
  {
    key: "souled_store",
    displayName: "The Souled Store",
    storeKey: "souled_store",
    sourceType: "manual",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: false,
    isActive: true,
    notes: "Independent brand. Manual catalog entry only.",
    requiredCredentials: [],
    feedFormatHint: "JSON or CSV with product details, prices, and store links",
  },
  {
    key: "bewakoof",
    displayName: "Bewakoof",
    storeKey: "bewakoof",
    sourceType: "manual",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: false,
    isActive: true,
    notes: "Independent brand. Manual catalog entry only.",
    requiredCredentials: [],
    feedFormatHint: "JSON or CSV with product details, prices, and store links",
  },
  {
    key: "hm_india",
    displayName: "H&M India",
    storeKey: "hm_india",
    sourceType: "official_api",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: false,
    isActive: true,
    notes: "No public API available. Support manual CSV/feed import.",
    requiredCredentials: [],
    feedFormatHint: "CSV with columns: title, price, mrp, url, category, image_url",
  },
  {
    key: "narzo_manual",
    displayName: "Narzo / Manual",
    storeKey: "narzo_manual",
    sourceType: "manual",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: false,
    isActive: true,
    notes: "Manual custom source for admin-entered products.",
    requiredCredentials: [],
    feedFormatHint: "JSON or CSV with all product fields",
  },
  {
    key: "other",
    displayName: "Other / Manual",
    storeKey: "other",
    sourceType: "manual",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: false,
    isActive: true,
    notes: "Generic manual source for any store not listed.",
    requiredCredentials: [],
    feedFormatHint: "JSON or CSV with product fields including store name",
  },
  {
    key: "generic_affiliate",
    displayName: "Generic Affiliate Feed",
    storeKey: "other",
    sourceType: "affiliate_feed",
    supportsLiveApi: false,
    supportsFeedImport: true,
    supportsAffiliateLinks: true,
    isActive: true,
    notes: "Generic feed connector for affiliate programs not tied to a specific store.",
    requiredCredentials: ["feed_url", "feed_format"],
    feedFormatHint: "JSON or XML feed with product data and affiliate URLs",
  },
];

export function getConnectorConfig(key: string): StoreConnectorConfig | undefined {
  return STORE_CONNECTORS.find((c) => c.key === key);
}

export function getActiveConnectors(): StoreConnectorConfig[] {
  return STORE_CONNECTORS.filter((c) => c.isActive);
}

export function getConnectorsBySourceType(type: string): StoreConnectorConfig[] {
  return STORE_CONNECTORS.filter((c) => c.sourceType === type);
}
