import type { WardrobeCategory } from "@/types/commerce";

export interface StyleSearchSuggestion {
  id: string;
  label: string;
  query: string;
  primaryCategory: WardrobeCategory;
}

export const STYLE_SEARCH_SUGGESTIONS: StyleSearchSuggestion[] = [
  { id: "old_money", label: "Old Money", query: "old money style clean tailoring loafers premium minimal" , primaryCategory: "trousers" },
  { id: "quiet_luxury", label: "Quiet Luxury", query: "quiet luxury neutral layering premium minimal" , primaryCategory: "shirt" },
  { id: "clean_girl", label: "Clean Girl", query: "clean girl basics sleek neutrals soft luxury" , primaryCategory: "tshirt" },
  { id: "clean_boy", label: "Clean Boy", query: "clean boy style basics neutral layers understated confident" , primaryCategory: "tshirt" },
  { id: "airport_fit", label: "Airport Fit", query: "airport fit roomy tailoring sneakers polished travel look" , primaryCategory: "trousers" },
  { id: "korean_casual", label: "Korean Casual", query: "korean casual oversized shirt clean sneakers soft layers" , primaryCategory: "shirt" },
  { id: "korean_street", label: "Korean Street", query: "korean streetwear cargos oversized hoodie sneakers creator bold" , primaryCategory: "hoodie" },
  { id: "japanese_minimal", label: "Japanese Minimal", query: "japanese minimal loose tailoring clean basics neutral palette" , primaryCategory: "shirt" },
  { id: "scandi_minimal", label: "Scandi Minimal", query: "scandi minimal simple layers clean silhouettes premium minimal" , primaryCategory: "shirt" },
  { id: "parisian", label: "Parisian", query: "parisian style black blazer denim loafers understated confident" , primaryCategory: "jacket" },
  { id: "italian_summer", label: "Italian Summer", query: "italian summer linen shirt trousers loafers soft luxury" , primaryCategory: "shirt" },
  { id: "riviera", label: "Riviera", query: "riviera resort style linen polo sunglasses loafers" , primaryCategory: "shirt" },
  { id: "coastal_grandpa", label: "Coastal Grandpa", query: "coastal grandpa knit polo relaxed trousers loafers" , primaryCategory: "shirt" },
  { id: "mob_wife", label: "Mob Wife", query: "mob wife glam faux fur statement sunglasses bold luxe" , primaryCategory: "jacket" },
  { id: "boho", label: "Boho", query: "boho relaxed layers textured trousers jewellery sandals" , primaryCategory: "shirt" },
  { id: "boho_luxe", label: "Boho Luxe", query: "boho luxe embroidered layers premium accessories soft luxury" , primaryCategory: "shirt" },
  { id: "y2k", label: "Y2K", query: "y2k style baby tee cargos sunglasses statement sneakers" , primaryCategory: "tshirt" },
  { id: "indie_sleaze", label: "Indie Sleaze", query: "indie sleaze leather jacket dark denim party layers" , primaryCategory: "jacket" },
  { id: "grunge", label: "Grunge", query: "grunge plaid overshirt faded denim boots layered tee" , primaryCategory: "shirt" },
  { id: "soft_grunge", label: "Soft Grunge", query: "soft grunge muted layers oversized tee dark sneakers" , primaryCategory: "tshirt" },
  { id: "goth_minimal", label: "Goth Minimal", query: "goth minimal black layers silver jewellery boots" , primaryCategory: "shirt" },
  { id: "dark_academia", label: "Dark Academia", query: "dark academia blazer knit vest trousers loafers" , primaryCategory: "jacket" },
  { id: "light_academia", label: "Light Academia", query: "light academia cardigan pleated trousers shirt loafers" , primaryCategory: "shirt" },
  { id: "college_core", label: "College Core", query: "college core varsity jacket tee jeans sneakers" , primaryCategory: "jacket" },
  { id: "campus_casual", label: "Campus Casual", query: "campus casual tee overshirt jeans sneakers" , primaryCategory: "shirt" },
  { id: "preppy", label: "Preppy", query: "preppy polo chinos sweater loafers clean basic" , primaryCategory: "shirt" },
  { id: "sporty_luxe", label: "Sporty Luxe", query: "sporty luxe track jacket polo fashion sneakers" , primaryCategory: "jacket" },
  { id: "blokecore", label: "Blokecore", query: "blokecore football jersey track pants sneakers" , primaryCategory: "tshirt" },
  { id: "tennis_core", label: "Tennis Core", query: "tennis core polo pleated skirt knit sweater sneakers" , primaryCategory: "shirt" },
  { id: "golf_core", label: "Golf Core", query: "golf core polo chinos visor clean sneakers" , primaryCategory: "shirt" },
  { id: "pilates_princess", label: "Pilates Princess", query: "pilates princess monochrome activewear clean girl layers" , primaryCategory: "tshirt" },
  { id: "gym_casual", label: "Gym Casual", query: "gym casual fitted tee joggers clean sneakers" , primaryCategory: "tshirt" },
  { id: "runner_style", label: "Runner Style", query: "runner style technical jacket shorts sporty sneakers" , primaryCategory: "jacket" },
  { id: "hiking_core", label: "Hiking Core", query: "hiking core utility jacket cargos trail sneakers" , primaryCategory: "jacket" },
  { id: "gorpcore", label: "Gorpcore", query: "gorpcore shell jacket cargo pants outdoors sneakers" , primaryCategory: "jacket" },
  { id: "techwear", label: "Techwear", query: "techwear black cargo layers utility jacket futuristic sneakers" , primaryCategory: "jacket" },
  { id: "streetwear", label: "Streetwear", query: "streetwear hoodie cargos sneakers creator bold" , primaryCategory: "hoodie" },
  { id: "luxury_streetwear", label: "Luxury Streetwear", query: "luxury streetwear bomber cargos premium sneakers" , primaryCategory: "jacket" },
  { id: "minimal_street", label: "Minimal Street", query: "minimal streetwear plain hoodie wide pants clean sneakers" , primaryCategory: "hoodie" },
  { id: "skater", label: "Skater", query: "skater style oversized tee baggy jeans skate sneakers" , primaryCategory: "tshirt" },
  { id: "retro_sports", label: "Retro Sports", query: "retro sports track jacket throwback sneakers sporty luxe" , primaryCategory: "jacket" },
  { id: "vintage_denim", label: "Vintage Denim", query: "vintage denim jacket straight jeans retro sneakers" , primaryCategory: "jacket" },
  { id: "seventies", label: "70s Revival", query: "70s revival suede jacket flared trousers tinted sunglasses" , primaryCategory: "jacket" },
  { id: "eighties", label: "80s Revival", query: "80s revival bomber jacket high top sneakers statement colors" , primaryCategory: "jacket" },
  { id: "nineties", label: "90s Minimal", query: "90s minimal leather jacket straight jeans premium minimal" , primaryCategory: "jacket" },
  { id: "two_thousands", label: "2000s Cool", query: "2000s cool cargos baby tee sunglasses sneakers" , primaryCategory: "tshirt" },
  { id: "office_core", label: "Office Core", query: "office core oxford shirt chinos belt formal shoes" , primaryCategory: "shirt" },
  { id: "corporate_sharp", label: "Corporate Sharp", query: "corporate sharp blazer trousers watch formal shoes" , primaryCategory: "jacket" },
  { id: "business_casual", label: "Business Casual", query: "business casual shirt chinos loafers understated confident" , primaryCategory: "shirt" },
  { id: "smart_casual", label: "Smart Casual", query: "smart casual overshirt polo trousers clean sneakers" , primaryCategory: "shirt" },
  { id: "boardroom", label: "Boardroom", query: "boardroom tailoring crisp shirt leather belt formal shoes" , primaryCategory: "shirt" },
  { id: "startup_founder", label: "Startup Founder", query: "startup founder style premium tee overshirt loafers" , primaryCategory: "shirt" },
  { id: "creative_office", label: "Creative Office", query: "creative office relaxed blazer wide trousers clean sneakers" , primaryCategory: "jacket" },
  { id: "interview", label: "Interview", query: "interview outfit oxford shirt chinos formal shoes clean look" , primaryCategory: "shirt" },
  { id: "presentation_day", label: "Presentation Day", query: "presentation day sharp tailoring polished accessories" , primaryCategory: "jacket" },
  { id: "date_night", label: "Date Night", query: "date night soft shirt trousers warm tones clean shoes" , primaryCategory: "shirt" },
  { id: "first_date", label: "First Date", query: "first date style approachable warm layers clean sneakers" , primaryCategory: "tshirt" },
  { id: "coffee_date", label: "Coffee Date", query: "coffee date casual warm overshirt tee sneakers" , primaryCategory: "shirt" },
  { id: "dinner_date", label: "Dinner Date", query: "dinner date blazer trousers jewellery sleek shoes" , primaryCategory: "jacket" },
  { id: "party", label: "Party", query: "party look statement jacket dark trousers standout accessories" , primaryCategory: "jacket" },
  { id: "club", label: "Club Night", query: "club night black shirt fitted trousers boots" , primaryCategory: "shirt" },
  { id: "concert", label: "Concert", query: "concert fit leather jacket cargos boots statement tee" , primaryCategory: "jacket" },
  { id: "festival", label: "Festival", query: "festival look kurta jacket jewellery ethnic clean" , primaryCategory: "jacket" },
  { id: "wedding_guest", label: "Wedding Guest", query: "wedding guest kurta tailoring festive luxe watch" , primaryCategory: "kurta" },
  { id: "sangeet", label: "Sangeet", query: "sangeet outfit embellished kurta jacket festive shoes" , primaryCategory: "kurta" },
  { id: "haldi", label: "Haldi", query: "haldi outfit ethnic clean yellow kurta sandals" , primaryCategory: "kurta" },
  { id: "mehendi", label: "Mehendi", query: "mehendi outfit green kurta fusion jewellery" , primaryCategory: "kurta" },
  { id: "cocktail", label: "Cocktail Night", query: "cocktail night sleek tailoring dressy shoes luxe accessories" , primaryCategory: "jacket" },
  { id: "ethnic_clean", label: "Ethnic Clean", query: "ethnic clean kurta watch wallet clean festive look" , primaryCategory: "kurta" },
  { id: "indo_western", label: "Indo-Western", query: "indo western fusion jacket kurta trousers statement look" , primaryCategory: "jacket" },
  { id: "bollywood_glam", label: "Bollywood Glam", query: "bollywood glam embellished tailoring luxe accessories" , primaryCategory: "jacket" },
  { id: "south_bombay", label: "South Bombay", query: "south bombay style quiet luxury linen shirts loafers" , primaryCategory: "shirt" },
  { id: "delhi_party", label: "Delhi Party", query: "delhi party blazer shirt dark trousers luxe shoes" , primaryCategory: "shirt" },
  { id: "mumbai_casual", label: "Mumbai Casual", query: "mumbai casual resort shirt relaxed trousers sneakers" , primaryCategory: "shirt" },
  { id: "goa_resort", label: "Goa Resort", query: "goa resort linen shirt shorts sandals sunglasses" , primaryCategory: "shirt" },
  { id: "vacation", label: "Vacation", query: "vacation style breathable layers sunglasses relaxed trousers" , primaryCategory: "shirt" },
  { id: "beach_club", label: "Beach Club", query: "beach club crochet shirt linen pants sandals" , primaryCategory: "shirt" },
  { id: "resort", label: "Resort", query: "resort wear printed shirt linen trousers loafers" , primaryCategory: "shirt" },
  { id: "monsoon", label: "Monsoon", query: "monsoon style lightweight jacket dark trousers weatherproof sneakers" , primaryCategory: "jacket" },
  { id: "winter_layers", label: "Winter Layers", query: "winter layers overcoat knitwear boots premium minimal" , primaryCategory: "jacket" },
  { id: "summer_linen", label: "Summer Linen", query: "summer linen shirt trousers loafers soft luxury" , primaryCategory: "shirt" },
  { id: "rainy_day", label: "Rainy Day", query: "rainy day utility jacket dark jeans clean shoes" , primaryCategory: "jacket" },
  { id: "all_black", label: "All Black", query: "all black outfit layered tee trousers boots goth minimal" , primaryCategory: "tshirt" },
  { id: "monochrome", label: "Monochrome", query: "monochrome outfit tonal layering premium minimal" , primaryCategory: "shirt" },
  { id: "earth_tones", label: "Earth Tones", query: "earth tone style olive beige brown soft luxury" , primaryCategory: "shirt" },
  { id: "neutral_capsule", label: "Neutral Capsule", query: "neutral capsule wardrobe white black navy beige basics" , primaryCategory: "shirt" },
  { id: "color_pop", label: "Color Pop", query: "color pop outfit neutral base statement jacket sneakers" , primaryCategory: "jacket" },
  { id: "red_statement", label: "Red Statement", query: "red statement outfit bold jacket shoes creator bold" , primaryCategory: "jacket" },
  { id: "blue_tones", label: "Blue Tones", query: "blue tone outfit shirt denim sneakers clean look" , primaryCategory: "shirt" },
  { id: "beige_luxury", label: "Beige Luxury", query: "beige luxury tonal tailoring soft luxury" , primaryCategory: "shirt" },
  { id: "all_white", label: "All White", query: "all white outfit premium minimal clean luxury" , primaryCategory: "shirt" },
  { id: "denim_on_denim", label: "Denim on Denim", query: "denim on denim jacket jeans celebrity street style" , primaryCategory: "jacket" },
  { id: "leather_jacket", label: "Leather Jacket", query: "leather jacket outfit black tee jeans boots" , primaryCategory: "jacket" },
  { id: "overshirt", label: "Overshirt", query: "overshirt outfit tee trousers sneakers smart casual" , primaryCategory: "shirt" },
  { id: "polo", label: "Polo Fit", query: "polo fit chinos loafers sporty luxe clean style" , primaryCategory: "shirt" },
  { id: "flannel", label: "Flannel", query: "flannel overshirt denim boots rugged casual" , primaryCategory: "shirt" },
  { id: "linen_shirt", label: "Linen Shirt", query: "linen shirt trousers loafers resort summer style" , primaryCategory: "shirt" },
  { id: "cargo_pants", label: "Cargo Pants", query: "cargo pants hoodie sneakers street smart" , primaryCategory: "trousers" },
  { id: "wide_leg", label: "Wide Leg", query: "wide leg trousers relaxed tailoring understated confident" , primaryCategory: "trousers" },
  { id: "pleated_trousers", label: "Pleated Trousers", query: "pleated trousers knit polo loafers premium minimal" , primaryCategory: "trousers" },
  { id: "loafers", label: "Loafer Look", query: "loafers chinos shirt blazer quiet luxury" , primaryCategory: "formal_shoes" },
  { id: "sneakerhead", label: "Sneakerhead", query: "sneakerhead outfit cargos hoodie statement sneakers" , primaryCategory: "sneakers" },
  { id: "creator_fit", label: "Creator Fit", query: "creator fit statement jacket accessories clean base" , primaryCategory: "jacket" },
  { id: "influencer_core", label: "Influencer Core", query: "influencer core polished basics sunglasses designer vibe" , primaryCategory: "tshirt" },
  { id: "model_off_duty", label: "Model Off Duty", query: "model off duty tank trousers bomber sunglasses" , primaryCategory: "tshirt" },
  { id: "celebrity_errand", label: "Celebrity Errand", query: "celebrity errand outfit bomber jeans sunglasses premium casual" , primaryCategory: "jacket" },
];
