import { Container } from "@/components/ui/Container";
import { SectionHeading } from "@/components/ui/SectionHeading";

export default function TermsPage() {
  return (
    <Container className="py-16">
      <SectionHeading
        title="Terms of Service"
        subtitle="Last updated: 2024"
        align="left"
      />
      <div className="prose prose-invert mx-auto max-w-3xl text-gray-400">
        <p>
          By using AuraCheck, you agree to the following terms.
        </p>
        <h3 className="mt-8 text-white">Service Description</h3>
        <p>
          AuraCheck provides first-impression analysis and visual presentation
          suggestions based on user-uploaded content. All scores and
          recommendations are generated by internal rules and are for
          informational and entertainment purposes only.
        </p>
        <h3 className="mt-8 text-white">No Guarantees</h3>
        <p>
          AuraCheck does not guarantee any specific social, professional, or
          personal outcomes. Scores reflect algorithmic analysis and should
          not be taken as objective truth or professional advice.
        </p>
        <h3 className="mt-8 text-white">User Responsibility</h3>
        <p>
          You are responsible for the content you upload. Do not upload
          images containing sensitive personal data, nudity, or content that
          violates applicable laws.
        </p>
        <h3 className="mt-8 text-white">Paid Services</h3>
        <p>
          Premium reports are unlocked via manual UPI payment. Refunds are
          handled on a case-by-case basis. Contact support for issues.
        </p>
        <h3 className="mt-8 text-white">Changes</h3>
        <p>
          We reserve the right to update these terms at any time. Continued
          use of the service constitutes acceptance of new terms.
        </p>
      </div>
    </Container>
  );
}
