import Link from "next/link";
import type { Metadata } from "next";
import { Container } from "@/components/ui/Container";
import { Button } from "@/components/ui/Button";

export const metadata: Metadata = {
  title: "Terms of Service — AuraCheck",
  description: "AuraCheck terms of service. Usage terms, payment terms, and limitations for the visual first-impression analysis tool.",
};

export default function TermsPage() {
  return (
    <Container className="py-16">
      <div className="mx-auto max-w-3xl">
        <h1 className="mb-2 text-3xl font-bold text-[#1C1917]">Terms of Service</h1>
        <p className="mb-8 text-sm text-[#857b6e]">Last updated: 2024</p>

        <div className="space-y-6 text-sm leading-relaxed text-[#6f675e]">
          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">Service Description</h2>
            <p>
              AuraCheck provides first-impression analysis, presentation guidance, and self-improvement suggestions 
              based on user-uploaded images and profile text. All scores, archetypes, and recommendations are 
              generated by rule-based algorithms running locally in your browser. The service is for informational, 
              entertainment, and self-improvement purposes only.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">No Guaranteed Outcomes</h2>
            <p>
              AuraCheck does not guarantee any specific social, professional, romantic, dating, or financial outcomes. 
              Scores and recommendations reflect algorithmic analysis of visual presentation signals. They are not 
              objective truth, professional advice, or a measure of human worth or attractiveness.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">User Responsibility</h2>
            <p>
              You are responsible for the content you upload. By using AuraCheck, you confirm:
            </p>
            <ul className="mt-2 list-inside list-disc space-y-1 text-[#6f675e]">
              <li>You own the uploaded image or have permission to analyze it</li>
              <li>You are using AuraCheck for self-improvement/presentation guidance</li>
              <li>You will not use AuraCheck to harass, shame, or publicly rank others</li>
              <li>You will not upload images containing nudity, explicit content, or sensitive personal data of others</li>
              <li>You acknowledge that scores are not objective truth</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">Prohibited Uses</h2>
            <p>
              You may not use AuraCheck to:
            </p>
            <ul className="mt-2 list-inside list-disc space-y-1 text-[#6f675e]">
              <li>Harass, shame, or judge individuals based on appearance, protected traits, or presentation style</li>
              <li>Upload images of others without their explicit consent for analysis</li>
              <li>Request analysis that infers protected traits (caste, religion, ethnicity, sexuality, health, income)</li>
              <li>Attempt to manipulate or exploit others through presentation feedback</li>
              <li>Use the service for any illegal purpose or in violation of applicable laws</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">Paid Services & Manual Payment</h2>
            <p>
              Premium reports and modules are unlocked via manual UPI transfer. Key terms:
            </p>
            <ul className="mt-2 list-inside list-disc space-y-1 text-[#6f675e]">
              <li>Payment is processed through your UPI app outside of AuraCheck — the app does not process payments</li>
              <li>Unlock codes are provided manually after payment confirmation by the owner</li>
              <li>Refunds are handled on a case-by-case basis. Contact support with your order details</li>
              <li>AuraCheck does not automatically verify payment — it relies on manual confirmation</li>
              <li>Prices and product availability may change without notice</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">Local Data Risk</h2>
            <p>
              AuraCheck stores all data locally in your browser&apos;s localStorage. This means:
            </p>
            <ul className="mt-2 list-inside list-disc space-y-1 text-[#6f675e]">
              <li>Clearing browser data will permanently remove your audits, reports, and orders</li>
              <li>Data is specific to the browser/device you use — it does not sync across devices</li>
              <li>We recommend exporting a backup before clearing browser data</li>
              <li>The app cannot recover data once localStorage is cleared</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">Limitation of Liability</h2>
            <p>
              AuraCheck is provided &quot;as is&quot; without warranty of any kind. The app is an MVP 
              (minimum viable product) for testing and feedback purposes. To the maximum extent permitted 
              by law, the creators of AuraCheck shall not be liable for any damages arising from the use 
              or inability to use the service, including data loss, incorrect analysis, or reliance on scores.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">Not Professional Advice</h2>
            <p>
              AuraCheck is not a substitute for professional financial, medical, legal, dating, or career advice. 
              The analysis and suggestions provided are for entertainment and self-improvement guidance only. 
              Always consult qualified professionals for serious decisions.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">Changes to Terms</h2>
            <p>
              We reserve the right to update these terms at any time. Continued use of the service after changes 
              constitutes acceptance of the new terms. Significant changes will be communicated through the app.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-[#1C1917]">Contact & Support</h2>
            {process.env.NEXT_PUBLIC_SUPPORT_EMAIL ? (
              <p>
                For support, refund requests, or questions about these terms, contact{" "}
                <span className="text-red-300">{process.env.NEXT_PUBLIC_SUPPORT_EMAIL}</span>.
              </p>
            ) : (
              <p>
                For support, refund requests, or questions about these terms, reach us through the{" "}
                <a href="/help" className="text-red-300 underline">Help &amp; Support</a> page.
              </p>
            )}
          </section>
        </div>

        <div className="mt-8 flex flex-wrap gap-4">
          <Link href="/privacy"><Button variant="outline" size="sm">Privacy Policy</Button></Link>
          <Link href="/help"><Button variant="outline" size="sm">Help & FAQ</Button></Link>
        </div>
      </div>
    </Container>
  );
}
