/**
 * Builds a self-contained, printable "Dating Profile Playbook" HTML file — the
 * keepable artifact for the Dating Audit: score, rewritten bios, photo order,
 * opening hooks and platform tactics in one document they can save and act on.
 */
import type { DatingProfileReport } from "@/types/audit";

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] as string));
}

export function buildDatingPlaybookHtml(r: DatingProfileReport): string {
  const bios = r.suggestedBios
    .map((b) => `<div class="card"><div class="tag">${esc(b.version)}</div><p class="quote">${esc(b.text)}</p><p class="why">${esc(b.whyItWorks)}</p></div>`)
    .join("");
  const flags = r.redFlags
    .map((f) => `<li><b>${esc(f.type)}</b> — ${esc(f.explanation)}<br><small>Fix: ${esc(f.fixSuggestion)}</small></li>`)
    .join("");
  const sequence = (r.photoStrategy?.sequence || [])
    .map((s) => `<li><b>${esc(s.slot)}</b> — ${esc(s.show)}</li>`)
    .join("");
  const avoid = (r.photoStrategy?.avoid || []).map((a) => `<li>${esc(a)}</li>`).join("");
  const hooks = (r.openingHooks || []).map((h) => `<li>${esc(h)}</li>`).join("");
  const platforms = (r.platformTips || [])
    .map((p) => `<div class="card"><b>${esc(p.platform)}</b><p style="margin:4px 0 0">${esc(p.tip)}</p></div>`)
    .join("");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>My Dating Profile Playbook — AuraCheck</title>
<style>
  :root { --ink:#1C1917; --muted:#6f675e; --accent:#E14434; --line:rgba(28,25,23,0.12); --bg:#FBF8F2; }
  * { box-sizing:border-box; }
  body { margin:0; font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; color:var(--ink); background:var(--bg); }
  .wrap { max-width:720px; margin:0 auto; padding:32px 20px 56px; }
  header { border-bottom:2px solid var(--ink); padding-bottom:14px; margin-bottom:20px; }
  .brand { font-size:12px; letter-spacing:.16em; text-transform:uppercase; color:var(--accent); font-weight:700; }
  h1 { font-size:28px; margin:6px 0 2px; }
  h2 { font-size:17px; border-bottom:1px solid var(--line); padding-bottom:6px; margin-top:26px; }
  .score { font-size:40px; font-weight:800; }
  .score small { font-size:14px; color:var(--muted); font-weight:400; }
  .advice { background:#fff; border:1px solid var(--line); border-radius:12px; padding:14px 16px; margin:14px 0; }
  ul { padding-left:18px; }
  li { margin:6px 0; }
  small { color:var(--muted); }
  .card { background:#fff; border:1px solid var(--line); border-radius:12px; padding:12px 14px; margin:10px 0; }
  .tag { font-size:11px; text-transform:uppercase; letter-spacing:.08em; color:var(--accent); font-weight:700; }
  .quote { margin:6px 0; }
  .why { margin:0; font-size:12px; color:var(--muted); }
  footer { margin-top:32px; font-size:11px; color:#9c9184; text-align:center; }
  @media print { body { background:#fff; } .wrap { padding:0; } }
</style></head>
<body><div class="wrap">
  <header>
    <div class="brand">AuraCheck · Dating Profile Playbook</div>
    <h1>My Profile Playbook</h1>
    <div class="score">${r.textScore}<small>/100 profile-text score</small></div>
  </header>

  <div class="advice">${esc(r.overallAdvice)}</div>

  ${bios ? `<h2>Ready-to-paste bios</h2>${bios}` : ""}

  ${r.photoStrategy ? `
  <h2>Photo strategy</h2>
  <p><b>Lead photo — </b>${esc(r.photoStrategy.leadPhoto)}</p>
  <p style="margin-top:10px"><b>Your photo order:</b></p>
  <ul>${sequence}</ul>
  <p style="margin-top:10px"><b>Cut these:</b></p>
  <ul>${avoid}</ul>` : ""}

  ${hooks ? `<h2>Opening hooks — get them to message first</h2><ul>${hooks}</ul>` : ""}

  ${flags ? `<h2>Fix these</h2><ul>${flags}</ul>` : ""}

  ${platforms ? `<h2>Platform playbook</h2>${platforms}` : ""}

  <footer>Generated by AuraCheck · fixmyaura.shop · Update your profile, then re-run to see your score climb.</footer>
</div></body></html>`;
}
