export async function downloadComparisonPng(
  originalDataUrl: string,
  bestDataUrl: string,
  originalScore: number,
  bestScore: number,
  bestVariantName: string
): Promise<void> {
  const loadImage = (src: string): Promise<HTMLImageElement> =>
    new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = reject;
      img.src = src;
    });

  const [origImg, bestImg] = await Promise.all([
    loadImage(originalDataUrl),
    loadImage(bestDataUrl),
  ]);

  const thumbW = 400;
  const gap = 12;
  const pad = 32;
  const headerH = 60;
  const footerH = 56;

  const origAspect = origImg.width / origImg.height;
  const thumbH = Math.round(thumbW / origAspect);

  const canvasW = thumbW * 2 + gap + pad * 2;
  const canvasH = headerH + thumbH + footerH + pad * 2;

  const canvas = document.createElement("canvas");
  canvas.width = canvasW;
  canvas.height = canvasH;
  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  // Background
  ctx.fillStyle = "#0a0a0a";
  ctx.fillRect(0, 0, canvasW, canvasH);

  // Header
  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 20px -apple-system, sans-serif";
  ctx.textAlign = "center";
  ctx.fillText("Aura Twin Comparison", canvasW / 2, pad + 30);

  // Draw images side by side
  const leftX = pad;
  const rightX = pad + thumbW + gap;
  const imgY = pad + headerH;

  ctx.drawImage(origImg, leftX, imgY, thumbW, thumbH);
  ctx.drawImage(bestImg, rightX, imgY, thumbW, thumbH);

  // Labels below images
  ctx.font = "14px -apple-system, sans-serif";
  ctx.fillStyle = "#888888";
  ctx.textAlign = "center";
  ctx.fillText(`Original — Score ${originalScore}`, leftX + thumbW / 2, imgY + thumbH + 18);
  ctx.fillStyle = "#a855f7";
  ctx.fillText(`${bestVariantName} — Score ${bestScore}`, rightX + thumbW / 2, imgY + thumbH + 18);

  // Footer
  ctx.fillStyle = "#555555";
  ctx.font = "11px -apple-system, sans-serif";
  ctx.textAlign = "center";
  ctx.fillText("Generated by Aura Twin Simulator — local processing only", canvasW / 2, canvasH - 14);

  // Download
  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `aura-twin-comparison-${Date.now()}.png`;
    a.click();
    URL.revokeObjectURL(url);
  }, "image/png");
}
